export const candidates: Record<string, Array<{ artist: string; title: string }>> = {
  "rock": [
    // Classic Rock / 60s-70s
    { artist: "The Beatles", title: "Abbey Road" },
    { artist: "The Beatles", title: "Revolver" },
    { artist: "The Beatles", title: "Sgt. Pepper's Lonely Hearts Club Band" },
    { artist: "The Beatles", title: "The White Album" },
    { artist: "The Beatles", title: "Rubber Soul" },
    { artist: "Led Zeppelin", title: "Led Zeppelin IV" },
    { artist: "Led Zeppelin", title: "Physical Graffiti" },
    { artist: "Led Zeppelin", title: "Houses of the Holy" },
    { artist: "Pink Floyd", title: "The Dark Side of the Moon" },
    { artist: "Pink Floyd", title: "Wish You Were Here" },
    { artist: "Pink Floyd", title: "The Wall" },
    { artist: "The Rolling Stones", title: "Exile on Main St." },
    { artist: "The Rolling Stones", title: "Let It Bleed" },
    { artist: "The Rolling Stones", title: "Sticky Fingers" },
    { artist: "The Who", title: "Who's Next" },
    { artist: "The Who", title: "Tommy" },
    { artist: "Jimi Hendrix", title: "Are You Experienced" },
    { artist: "Jimi Hendrix", title: "Electric Ladyland" },
    { artist: "The Doors", title: "The Doors" },
    { artist: "The Velvet Underground", title: "The Velvet Underground & Nico" },
    { artist: "David Bowie", title: "The Rise and Fall of Ziggy Stardust and the Spiders From Mars" },
    { artist: "David Bowie", title: "Low" },
    { artist: "David Bowie", title: "Heroes" },
    { artist: "David Bowie", title: "Station to Station" },
    { artist: "King Crimson", title: "In the Court of the Crimson King" },
    { artist: "Yes", title: "Close to the Edge" },
    { artist: "Genesis", title: "The Lamb Lies Down on Broadway" },
    { artist: "Cream", title: "Disraeli Gears" },
    { artist: "The Kinks", title: "The Kinks Are the Village Green Preservation Society" },
    { artist: "The Band", title: "Music from Big Pink" },
    { artist: "Creedence Clearwater Revival", title: "Cosmo's Factory" },
    { artist: "Fleetwood Mac", title: "Rumours" },
    { artist: "Neil Young", title: "After the Gold Rush" },
    { artist: "Neil Young & Crazy Horse", title: "Rust Never Sleeps" },
    { artist: "Black Sabbath", title: "Paranoid" },
    { artist: "Deep Purple", title: "Machine Head" },
    { artist: "AC/DC", title: "Back in Black" },
    { artist: "The Stooges", title: "Fun House" },
    { artist: "MC5", title: "Kick Out the Jams" },
    { artist: "Can", title: "Tago Mago" },
    { artist: "Can", title: "Ege Bamyasi" },
    { artist: "Neu!", title: "Neu!" },
    { artist: "Faust", title: "Faust IV" },
    { artist: "Bruce Springsteen", title: "Born to Run" },
    { artist: "Bruce Springsteen", title: "Darkness on the Edge of Town" },
    { artist: "Television", title: "Marquee Moon" },
    // Punk / Post-Punk / New Wave
    { artist: "The Clash", title: "London Calling" },
    { artist: "Sex Pistols", title: "Never Mind the Bollocks, Here's the Sex Pistols" },
    { artist: "Ramones", title: "Ramones" },
    { artist: "Joy Division", title: "Unknown Pleasures" },
    { artist: "Joy Division", title: "Closer" },
    { artist: "Talking Heads", title: "Remain in Light" },
    { artist: "Talking Heads", title: "Fear of Music" },
    { artist: "Wire", title: "Pink Flag" },
    { artist: "Siouxsie and the Banshees", title: "Juju" },
    { artist: "Bauhaus", title: "In the Flat Field" },
    { artist: "The Cure", title: "Disintegration" },
    { artist: "The Cure", title: "Pornography" },
    { artist: "The Smiths", title: "The Queen Is Dead" },
    { artist: "The Smiths", title: "Meat Is Murder" },
    { artist: "Echo & the Bunnymen", title: "Ocean Rain" },
    { artist: "Cocteau Twins", title: "Heaven or Las Vegas" },
    { artist: "New Order", title: "Power, Corruption & Lies" },
    // Alternative / Indie / 80s-90s
    { artist: "R.E.M.", title: "Murmur" },
    { artist: "R.E.M.", title: "Automatic for the People" },
    { artist: "Pixies", title: "Doolittle" },
    { artist: "Pixies", title: "Surfer Rosa" },
    { artist: "Sonic Youth", title: "Daydream Nation" },
    { artist: "Dinosaur Jr.", title: "You're Living All Over Me" },
    { artist: "The Replacements", title: "Let It Be" },
    { artist: "Hüsker Dü", title: "Zen Arcade" },
    { artist: "Minutemen", title: "Double Nickels on the Dime" },
    { artist: "My Bloody Valentine", title: "Loveless" },
    { artist: "Slowdive", title: "Souvlaki" },
    { artist: "Ride", title: "Nowhere" },
    { artist: "The Jesus and Mary Chain", title: "Psychocandy" },
    { artist: "Pavement", title: "Slanted and Enchanted" },
    { artist: "Pavement", title: "Crooked Rain, Crooked Rain" },
    { artist: "Guided by Voices", title: "Bee Thousand" },
    { artist: "Built to Spill", title: "Perfect from Now On" },
    { artist: "Fugazi", title: "Repeater" },
    { artist: "PJ Harvey", title: "Rid of Me" },
    { artist: "PJ Harvey", title: "Stories from the City, Stories from the Sea" },
    // Grunge / 90s Rock
    { artist: "Nirvana", title: "Nevermind" },
    { artist: "Nirvana", title: "In Utero" },
    { artist: "Pearl Jam", title: "Ten" },
    { artist: "Soundgarden", title: "Superunknown" },
    { artist: "Alice in Chains", title: "Dirt" },
    { artist: "Smashing Pumpkins", title: "Siamese Dream" },
    { artist: "Smashing Pumpkins", title: "Mellon Collie and the Infinite Sadness" },
    { artist: "Weezer", title: "Weezer (Blue Album)" },
    { artist: "Radiohead", title: "OK Computer" },
    { artist: "Radiohead", title: "The Bends" },
    { artist: "Radiohead", title: "Kid A" },
    { artist: "Radiohead", title: "In Rainbows" },
    { artist: "Jeff Buckley", title: "Grace" },
    { artist: "Neutral Milk Hotel", title: "In the Aeroplane Over the Sea" },
    { artist: "Elliott Smith", title: "Either/Or" },
    { artist: "Modest Mouse", title: "The Lonesome Crowded West" },
    { artist: "The Flaming Lips", title: "The Soft Bulletin" },
    { artist: "Wilco", title: "Yankee Hotel Foxtrot" },
    { artist: "Tool", title: "Lateralus" },
    { artist: "Tool", title: "Ænima" },
    { artist: "Rage Against the Machine", title: "Rage Against the Machine" },
    { artist: "Nine Inch Nails", title: "The Downward Spiral" },
    // 2000s Rock
    { artist: "The Strokes", title: "Is This It" },
    { artist: "Interpol", title: "Turn On the Bright Lights" },
    { artist: "The White Stripes", title: "White Blood Cells" },
    { artist: "The White Stripes", title: "Elephant" },
    { artist: "Arcade Fire", title: "Funeral" },
    { artist: "Arcade Fire", title: "The Suburbs" },
    { artist: "Arctic Monkeys", title: "Whatever People Say I Am, That's What I'm Not" },
    { artist: "Queens of the Stone Age", title: "Songs for the Deaf" },
    { artist: "Muse", title: "Origin of Symmetry" },
    { artist: "Yeah Yeah Yeahs", title: "Fever to Tell" },
    { artist: "LCD Soundsystem", title: "Sound of Silver" },
    { artist: "The National", title: "Boxer" },
    { artist: "The National", title: "High Violet" },
    { artist: "TV on the Radio", title: "Return to Cookie Mountain" },
    { artist: "Deerhunter", title: "Halcyon Digest" },
    { artist: "Animal Collective", title: "Merriweather Post Pavilion" },
    { artist: "Sufjan Stevens", title: "Illinois" },
    { artist: "Sigur Rós", title: "( )" },
    { artist: "Sigur Rós", title: "Ágætis byrjun" },
    { artist: "Godspeed You! Black Emperor", title: "Lift Your Skinny Fists Like Antennas to Heaven" },
    // 2010s-2020s Rock
    { artist: "Tame Impala", title: "Lonerism" },
    { artist: "Tame Impala", title: "Currents" },
    { artist: "King Gizzard & The Lizard Wizard", title: "Nonagon Infinity" },
    { artist: "Fontaines D.C.", title: "Dogrel" },
    { artist: "IDLES", title: "Joy as an Act of Resistance" },
    { artist: "Shame", title: "Songs of Praise" },
    { artist: "black midi", title: "Cavalcade" },
    { artist: "Black Country, New Road", title: "Ants From Up There" },
    { artist: "Dry Cleaning", title: "New Long Leg" },
    { artist: "Parquet Courts", title: "Wide Awake!" },
    { artist: "Car Seat Headrest", title: "Twin Fantasy" },
    { artist: "Courtney Barnett", title: "Sometimes I Sit and Think, and Sometimes I Just Sit" },
    { artist: "St. Vincent", title: "Strange Mercy" },
    { artist: "War on Drugs", title: "Lost in the Dream" },
    { artist: "Turnstile", title: "Glow On" },
    { artist: "Big Thief", title: "Dragon New Warm Mountain I Believe in You" },
    { artist: "Japanese Breakfast", title: "Jubilee" },
    { artist: "Alvvays", title: "Antisocialites" },
    { artist: "King Krule", title: "The OOZ" },
    { artist: "Boris", title: "Flood" },
    { artist: "Thee Oh Sees", title: "Floating Coffin" },
    { artist: "Ty Segall", title: "Manipulator" },
    { artist: "Mac DeMarco", title: "Salad Days" },
    { artist: "Protomartyr", title: "Relatives in Descent" },
    { artist: "Preoccupations", title: "Viet Cong" },
    { artist: "Ought", title: "More than Any Other Day" },
    { artist: "Cloud Nothings", title: "Attack on Memory" },
    { artist: "Dinosaur Jr.", title: "Bug" },
    { artist: "Superchunk", title: "No Pocky for Kitty" },
    { artist: "Yo La Tengo", title: "I Can Hear the Heart Beating as One" },
  ],

  "hip-hop": [
    // Old School / Golden Age
    { artist: "Grandmaster Flash & The Furious Five", title: "The Message" },
    { artist: "Run-D.M.C.", title: "Raising Hell" },
    { artist: "Beastie Boys", title: "Paul's Boutique" },
    { artist: "Beastie Boys", title: "Licensed to Ill" },
    { artist: "Public Enemy", title: "It Takes a Nation of Millions to Hold Us Back" },
    { artist: "Public Enemy", title: "Fear of a Black Planet" },
    { artist: "Eric B. & Rakim", title: "Paid in Full" },
    { artist: "N.W.A", title: "Straight Outta Compton" },
    { artist: "De La Soul", title: "3 Feet High and Rising" },
    { artist: "A Tribe Called Quest", title: "The Low End Theory" },
    { artist: "A Tribe Called Quest", title: "Midnight Marauders" },
    { artist: "Gang Starr", title: "Moment of Truth" },
    { artist: "KRS-One", title: "Return of the Boom Bap" },
    { artist: "Big Daddy Kane", title: "Long Live the Kane" },
    { artist: "Boogie Down Productions", title: "Criminal Minded" },
    // East Coast
    { artist: "Nas", title: "Illmatic" },
    { artist: "Nas", title: "It Was Written" },
    { artist: "The Notorious B.I.G.", title: "Ready to Die" },
    { artist: "The Notorious B.I.G.", title: "Life After Death" },
    { artist: "Wu-Tang Clan", title: "Enter the Wu-Tang (36 Chambers)" },
    { artist: "Raekwon", title: "Only Built 4 Cuban Linx..." },
    { artist: "GZA", title: "Liquid Swords" },
    { artist: "Ghostface Killah", title: "Supreme Clientele" },
    { artist: "Mobb Deep", title: "The Infamous" },
    { artist: "Jay-Z", title: "Reasonable Doubt" },
    { artist: "Jay-Z", title: "The Blueprint" },
    { artist: "Jay-Z", title: "The Black Album" },
    { artist: "Jay-Z", title: "4:44" },
    { artist: "DMX", title: "It's Dark and Hell Is Hot" },
    { artist: "Busta Rhymes", title: "When Disaster Strikes..." },
    // West Coast
    { artist: "Dr. Dre", title: "The Chronic" },
    { artist: "Dr. Dre", title: "2001" },
    { artist: "Snoop Dogg", title: "Doggystyle" },
    { artist: "2Pac", title: "All Eyez on Me" },
    { artist: "2Pac", title: "Me Against the World" },
    { artist: "Ice Cube", title: "AmeriKKKa's Most Wanted" },
    { artist: "Ice Cube", title: "Death Certificate" },
    { artist: "DJ Quik", title: "Quik Is the Name" },
    { artist: "The Pharcyde", title: "Bizarre Ride II the Pharcyde" },
    // Southern
    { artist: "OutKast", title: "Aquemini" },
    { artist: "OutKast", title: "ATLiens" },
    { artist: "OutKast", title: "Stankonia" },
    { artist: "OutKast", title: "Speakerboxxx/The Love Below" },
    { artist: "UGK", title: "Ridin' Dirty" },
    { artist: "Scarface", title: "The Diary" },
    { artist: "Goodie Mob", title: "Soul Food" },
    { artist: "Three 6 Mafia", title: "Mystic Stylez" },
    { artist: "Lil Wayne", title: "Tha Carter III" },
    { artist: "Lil Wayne", title: "Tha Carter II" },
    { artist: "T.I.", title: "King" },
    // Conscious / Underground
    { artist: "Mos Def", title: "Black on Both Sides" },
    { artist: "Black Star", title: "Mos Def & Talib Kweli Are Black Star" },
    { artist: "Common", title: "Be" },
    { artist: "Common", title: "Like Water for Chocolate" },
    { artist: "The Roots", title: "Things Fall Apart" },
    { artist: "The Roots", title: "Illadelph Halflife" },
    { artist: "Lauryn Hill", title: "The Miseducation of Lauryn Hill" },
    { artist: "Fugees", title: "The Score" },
    { artist: "Madvillain", title: "Madvillainy" },
    { artist: "MF DOOM", title: "Mm..Food" },
    { artist: "MF DOOM", title: "Operation: Doomsday" },
    { artist: "Aesop Rock", title: "Labor Days" },
    { artist: "Company Flow", title: "Funcrusher Plus" },
    { artist: "El-P", title: "Fantastic Damage" },
    { artist: "Cannibal Ox", title: "The Cold Vein" },
    { artist: "Deltron 3030", title: "Deltron 3030" },
    { artist: "Hieroglyphics", title: "3rd Eye Vision" },
    // 2000s
    { artist: "Kanye West", title: "The College Dropout" },
    { artist: "Kanye West", title: "Late Registration" },
    { artist: "Kanye West", title: "My Beautiful Dark Twisted Fantasy" },
    { artist: "Kanye West", title: "Graduation" },
    { artist: "Kanye West", title: "808s & Heartbreak" },
    { artist: "Kanye West", title: "Yeezus" },
    { artist: "Eminem", title: "The Marshall Mathers LP" },
    { artist: "Eminem", title: "The Slim Shady LP" },
    { artist: "50 Cent", title: "Get Rich or Die Tryin'" },
    { artist: "Clipse", title: "Hell Hath No Fury" },
    { artist: "Lupe Fiasco", title: "Food & Liquor" },
    { artist: "Kid Cudi", title: "Man on the Moon: The End of Day" },
    // 2010s-2020s
    { artist: "Kendrick Lamar", title: "good kid, m.A.A.d city" },
    { artist: "Kendrick Lamar", title: "To Pimp a Butterfly" },
    { artist: "Kendrick Lamar", title: "DAMN." },
    { artist: "Kendrick Lamar", title: "Mr. Morale & The Big Steppers" },
    { artist: "J. Cole", title: "2014 Forest Hills Drive" },
    { artist: "Drake", title: "Take Care" },
    { artist: "Drake", title: "Nothing Was the Same" },
    { artist: "Travis Scott", title: "Rodeo" },
    { artist: "Travis Scott", title: "Astroworld" },
    { artist: "Tyler, The Creator", title: "Flower Boy" },
    { artist: "Tyler, The Creator", title: "IGOR" },
    { artist: "Tyler, The Creator", title: "Call Me If You Get Lost" },
    { artist: "Frank Ocean", title: "Channel Orange" },
    { artist: "Danny Brown", title: "Atrocity Exhibition" },
    { artist: "Run The Jewels", title: "Run The Jewels 2" },
    { artist: "Vince Staples", title: "Summertime '06" },
    { artist: "Denzel Curry", title: "TA13OO" },
    { artist: "Freddie Gibbs & Madlib", title: "Piñata" },
    { artist: "Freddie Gibbs & The Alchemist", title: "Alfredo" },
    { artist: "Pusha T", title: "Daytona" },
    { artist: "Earl Sweatshirt", title: "Some Rap Songs" },
    { artist: "Joey Bada$$", title: "1999" },
    { artist: "Isaiah Rashad", title: "The Sun's Tirade" },
    { artist: "JID", title: "The Forever Story" },
    { artist: "Little Simz", title: "Sometimes I Might Be Introvert" },
    { artist: "Skepta", title: "Konnichiwa" },
    { artist: "Stormzy", title: "Gang Signs & Prayer" },
    { artist: "Dave", title: "Psychodrama" },
    { artist: "Slowthai", title: "Nothing Great About Britain" },
    { artist: "Playboi Carti", title: "Die Lit" },
    { artist: "Future", title: "DS2" },
    { artist: "Young Thug", title: "Barter 6" },
    { artist: "Rico Nasty", title: "Nightmare Vacation" },
    { artist: "Noname", title: "Room 25" },
    { artist: "Rapsody", title: "Eve" },
    { artist: "Megan Thee Stallion", title: "Good News" },
    { artist: "Baby Keem", title: "The Melodic Blue" },
    { artist: "Nas", title: "King's Disease II" },
    // Bonus International
    { artist: "Dizzee Rascal", title: "Boy in da Corner" },
    { artist: "Roots Manuva", title: "Run Come Save Me" },
    { artist: "Missy Elliott", title: "Supa Dupa Fly" },
    { artist: "Missy Elliott", title: "Miss E... So Addictive" },
    { artist: "Scarface", title: "The Fix" },
    { artist: "Souls of Mischief", title: "93 'til Infinity" },
    { artist: "Pete Rock & CL Smooth", title: "Mecca and the Soul Brother" },
    { artist: "Czarface & MF DOOM", title: "Super What?" },
    { artist: "Boldy James & The Alchemist", title: "The Price of Tea in China" },
    { artist: "Lil' Kim", title: "Hard Core" },
    { artist: "Foxy Brown", title: "Ill Na Na" },
    { artist: "Cam'ron", title: "Purple Haze" },
    { artist: "The Diplomats", title: "Diplomatic Immunity" },
    { artist: "Jadakiss", title: "Kiss tha Game Goodbye" },
    { artist: "Redman", title: "Dare Iz a Darkside" },
    { artist: "Method Man", title: "Tical" },
    { artist: "Ol' Dirty Bastard", title: "Return to the 36 Chambers: The Dirty Version" },
    { artist: "Westside Gunn", title: "Pray for Paris" },
    { artist: "Conway the Machine", title: "From King to a GOD" },
    { artist: "Logic", title: "Under Pressure" },
    { artist: "Cordae", title: "The Lost Boy" },
    { artist: "Killer Mike", title: "R.A.P. Music" },
    { artist: "Big K.R.I.T.", title: "4eva Is a Mighty Long Time" },
    { artist: "Curren$y", title: "Pilot Talk" },
    { artist: "Mac Miller", title: "Swimming" },
    { artist: "Chance the Rapper", title: "Acid Rap" },
    { artist: "Tierra Whack", title: "Whack World" },
    { artist: "Quelle Chris", title: "Being You Is Great, I Wish I Could Be You More Often" },
    { artist: "billy woods & Kenny Segal", title: "Maps" },
    { artist: "Armand Hammer", title: "Haram" },
    { artist: "Ka", title: "Descendants of Cain" },
    { artist: "Saba", title: "Care for Me" },
    { artist: "Smino", title: "blkswn" },
  ],

  "electronic": [
    // Ambient / Early Electronic
    { artist: "Brian Eno", title: "Ambient 1: Music for Airports" },
    { artist: "Brian Eno", title: "Another Green World" },
    { artist: "Brian Eno", title: "Music for Films" },
    { artist: "Tangerine Dream", title: "Phaedra" },
    { artist: "Tangerine Dream", title: "Rubycon" },
    { artist: "Klaus Schulze", title: "Timewind" },
    { artist: "Vangelis", title: "Blade Runner" },
    { artist: "Jean-Michel Jarre", title: "Oxygène" },
    { artist: "Kraftwerk", title: "Trans-Europe Express" },
    { artist: "Kraftwerk", title: "The Man-Machine" },
    { artist: "Kraftwerk", title: "Computer World" },
    { artist: "Kraftwerk", title: "Autobahn" },
    { artist: "Yellow Magic Orchestra", title: "Solid State Survivor" },
    { artist: "Yellow Magic Orchestra", title: "BGM" },
    // Synth-Pop / New Wave Electronic
    { artist: "Depeche Mode", title: "Violator" },
    { artist: "Depeche Mode", title: "Music for the Masses" },
    { artist: "Depeche Mode", title: "Black Celebration" },
    { artist: "New Order", title: "Technique" },
    { artist: "Orchestral Manoeuvres in the Dark", title: "Architecture & Morality" },
    { artist: "Gary Numan", title: "The Pleasure Principle" },
    { artist: "Cabaret Voltaire", title: "Red Mecca" },
    { artist: "Throbbing Gristle", title: "20 Jazz Funk Greats" },
    { artist: "Einstürzende Neubauten", title: "Halber Mensch" },
    { artist: "SPK", title: "Leichenschrei" },
    { artist: "Front 242", title: "Front by Front" },
    // House / Techno
    { artist: "Frankie Knuckles", title: "Beyond the Mix" },
    { artist: "Larry Heard", title: "Amnesia" },
    { artist: "Derrick May", title: "Innovator" },
    { artist: "Jeff Mills", title: "Waveform Transmission Vol. 3" },
    { artist: "Underground Resistance", title: "Revolution for Change" },
    { artist: "Juan Atkins", title: "20 Years: 1985-2005" },
    { artist: "Model 500", title: "Classics" },
    { artist: "The Orb", title: "The Orb's Adventures Beyond the Ultraworld" },
    { artist: "Orbital", title: "Orbital 2" },
    { artist: "Underworld", title: "dubnobasswithmyheadman" },
    { artist: "Underworld", title: "Second Toughest in the Infants" },
    { artist: "The Chemical Brothers", title: "Dig Your Own Hole" },
    { artist: "The Chemical Brothers", title: "Surrender" },
    { artist: "Fatboy Slim", title: "You've Come a Long Way, Baby" },
    { artist: "The Prodigy", title: "The Fat of the Land" },
    { artist: "The Prodigy", title: "Music for the Jilted Generation" },
    { artist: "Daft Punk", title: "Homework" },
    { artist: "Daft Punk", title: "Discovery" },
    { artist: "Daft Punk", title: "Random Access Memories" },
    { artist: "Basement Jaxx", title: "Remedy" },
    { artist: "Laurent Garnier", title: "30" },
    // Trip-Hop
    { artist: "Massive Attack", title: "Blue Lines" },
    { artist: "Massive Attack", title: "Mezzanine" },
    { artist: "Massive Attack", title: "Protection" },
    { artist: "Portishead", title: "Dummy" },
    { artist: "Portishead", title: "Third" },
    { artist: "Tricky", title: "Maxinquaye" },
    { artist: "DJ Shadow", title: "Endtroducing....." },
    { artist: "UNKLE", title: "Psyence Fiction" },
    // IDM / Experimental
    { artist: "Aphex Twin", title: "Selected Ambient Works 85-92" },
    { artist: "Aphex Twin", title: "Selected Ambient Works Volume II" },
    { artist: "Aphex Twin", title: "Richard D. James Album" },
    { artist: "Aphex Twin", title: "Drukqs" },
    { artist: "Autechre", title: "Tri Repetae" },
    { artist: "Autechre", title: "LP5" },
    { artist: "Autechre", title: "Amber" },
    { artist: "Boards of Canada", title: "Music Has the Right to Children" },
    { artist: "Boards of Canada", title: "Geogaddi" },
    { artist: "Squarepusher", title: "Feed Me Weird Things" },
    { artist: "Squarepusher", title: "Hard Normal Daddy" },
    { artist: "μ-Ziq", title: "Lunatic Harness" },
    { artist: "Four Tet", title: "Rounds" },
    { artist: "Four Tet", title: "There Is Love in You" },
    { artist: "Four Tet", title: "New Energy" },
    // Drum & Bass / Jungle
    { artist: "Goldie", title: "Timeless" },
    { artist: "Roni Size / Reprazent", title: "New Forms" },
    { artist: "LTJ Bukem", title: "Logical Progression" },
    { artist: "Photek", title: "Modus Operandi" },
    // Ambient / Drone / Post-2000
    { artist: "Tim Hecker", title: "Harmony in Ultraviolet" },
    { artist: "Tim Hecker", title: "Ravedeath, 1972" },
    { artist: "Tim Hecker", title: "Virgins" },
    { artist: "Fennesz", title: "Endless Summer" },
    { artist: "Stars of the Lid", title: "The Tired Sounds of Stars of the Lid" },
    { artist: "Gas", title: "Pop" },
    { artist: "William Basinski", title: "The Disintegration Loops" },
    { artist: "Oneohtrix Point Never", title: "R Plus Seven" },
    { artist: "Oneohtrix Point Never", title: "Age Of" },
    { artist: "Oneohtrix Point Never", title: "Garden of Delete" },
    // Contemporary Electronic / 2000s-2020s
    { artist: "Burial", title: "Untrue" },
    { artist: "Burial", title: "Burial" },
    { artist: "James Blake", title: "James Blake" },
    { artist: "Flying Lotus", title: "Cosmogramma" },
    { artist: "Flying Lotus", title: "Los Angeles" },
    { artist: "Flying Lotus", title: "You're Dead!" },
    { artist: "Nicolas Jaar", title: "Space Is Only Noise" },
    { artist: "Arca", title: "KiCk i" },
    { artist: "Arca", title: "Arca" },
    { artist: "SOPHIE", title: "Oil of Every Pearl's Un-Insides" },
    { artist: "Kelela", title: "Take Me Apart" },
    { artist: "Kelela", title: "Raven" },
    { artist: "Caribou", title: "Swim" },
    { artist: "Caribou", title: "Our Love" },
    { artist: "Jamie xx", title: "In Colour" },
    { artist: "Disclosure", title: "Settle" },
    { artist: "Flume", title: "Flume" },
    { artist: "Kaytranada", title: "99.9%" },
    { artist: "Jon Hopkins", title: "Immunity" },
    { artist: "Jon Hopkins", title: "Singularity" },
    { artist: "Floating Points", title: "Crush" },
    { artist: "Floating Points, Pharoah Sanders & The London Symphony Orchestra", title: "Promises" },
    { artist: "Andy Stott", title: "Luxury Problems" },
    { artist: "The Avalanches", title: "Since I Left You" },
    { artist: "The Avalanches", title: "Wildflower" },
    { artist: "Björk", title: "Homogenic" },
    { artist: "Björk", title: "Vespertine" },
    { artist: "Björk", title: "Post" },
    { artist: "M83", title: "Hurry Up, We're Dreaming" },
    { artist: "Justice", title: "†" },
    { artist: "Gesaffelstein", title: "Aleph" },
    { artist: "Skrillex", title: "Scary Monsters and Nice Sprites" },
    { artist: "Ryuichi Sakamoto", title: "async" },
    { artist: "Yaeji", title: "What We Drew" },
    { artist: "Helena Hauff", title: "Qualm" },
    { artist: "Peggy Gou", title: "I Hear You" },
    { artist: "Objekt", title: "Cocoon Crush" },
    { artist: "Holly Herndon", title: "PROTO" },
    { artist: "Tirzah", title: "Devotion" },
    // Japanese Electronic
    { artist: "Susumu Yokota", title: "Sakura" },
    { artist: "Cornelius", title: "Fantasma" },
    { artist: "Midori Takada", title: "Through the Looking Glass" },
    // Minimal / Microhouse
    { artist: "Ricardo Villalobos", title: "Alcachofa" },
    { artist: "Actress", title: "R.I.P." },
    { artist: "Actress", title: "Ghettoville" },
    { artist: "Modeselektor", title: "Happy Birthday!" },
    { artist: "Moderat", title: "Moderat" },
    { artist: "Aphex Twin", title: "Syro" },
    { artist: "Plastikman", title: "Sheet One" },
    { artist: "Burial", title: "Kindred" },
    { artist: "Clark", title: "Clark" },
    { artist: "Machinedrum", title: "Vapor City" },
    { artist: "Daniel Avery", title: "Drone Logic" },
    { artist: "Lone", title: "Reality Testing" },
    { artist: "DJ Koze", title: "Knock Knock" },
    { artist: "Bicep", title: "Isles" },
    { artist: "Skee Mask", title: "Compro" },
    { artist: "Overmono", title: "Good Lies" },
    { artist: "Yves Tumor", title: "Heaven to a Tortured Mind" },
    { artist: "The Knife", title: "Silent Shout" },
    { artist: "Fever Ray", title: "Fever Ray" },
    { artist: "Röyksopp", title: "Melody A.M." },
    { artist: "Bonobo", title: "Black Sands" },
    { artist: "Mount Kimbie", title: "Crooks & Lovers" },
    { artist: "Darkside", title: "Psychic" },
    { artist: "Nils Frahm", title: "All Melody" },
  ],

  "jazz": [
    // Swing / Pre-Bop
    { artist: "Duke Ellington", title: "Ellington at Newport" },
    { artist: "Duke Ellington", title: "Money Jungle" },
    { artist: "Duke Ellington", title: "Far East Suite" },
    { artist: "Count Basie", title: "The Atomic Mr. Basie" },
    { artist: "Billie Holiday", title: "Lady in Satin" },
    { artist: "Billie Holiday", title: "Lady Sings the Blues" },
    { artist: "Ella Fitzgerald", title: "Ella Fitzgerald Sings the Cole Porter Song Book" },
    { artist: "Ella Fitzgerald", title: "Ella and Louis" },
    { artist: "Louis Armstrong", title: "Hot Fives & Sevens" },
    { artist: "Thelonious Monk", title: "Brilliant Corners" },
    { artist: "Thelonious Monk", title: "Monk's Dream" },
    { artist: "Thelonious Monk", title: "Thelonious Monk with John Coltrane" },
    // Bebop / Hard Bop
    { artist: "Charlie Parker", title: "Charlie Parker with Strings" },
    { artist: "Charlie Parker", title: "Bird and Diz" },
    { artist: "Dizzy Gillespie", title: "Dizzy Atmosphere" },
    { artist: "Bud Powell", title: "The Amazing Bud Powell, Vol. 1" },
    { artist: "Art Blakey & The Jazz Messengers", title: "Moanin'" },
    { artist: "Art Blakey & The Jazz Messengers", title: "A Night at Birdland" },
    { artist: "Horace Silver", title: "Song for My Father" },
    { artist: "Clifford Brown & Max Roach", title: "Clifford Brown & Max Roach" },
    { artist: "Sonny Rollins", title: "Saxophone Colossus" },
    { artist: "Sonny Rollins", title: "A Night at the Village Vanguard" },
    { artist: "Sonny Rollins", title: "The Bridge" },
    { artist: "Lee Morgan", title: "The Sidewinder" },
    { artist: "Freddie Hubbard", title: "Red Clay" },
    { artist: "Hank Mobley", title: "Soul Station" },
    { artist: "Kenny Dorham", title: "Quiet Kenny" },
    { artist: "Dexter Gordon", title: "Go" },
    { artist: "Jackie McLean", title: "Let Freedom Ring" },
    // Cool Jazz / West Coast
    { artist: "Miles Davis", title: "Kind of Blue" },
    { artist: "Miles Davis", title: "Birth of the Cool" },
    { artist: "Miles Davis", title: "Sketches of Spain" },
    { artist: "Miles Davis", title: "In a Silent Way" },
    { artist: "Miles Davis", title: "Bitches Brew" },
    { artist: "Miles Davis", title: "'Round About Midnight" },
    { artist: "Miles Davis", title: "A Tribute to Jack Johnson" },
    { artist: "Miles Davis", title: "On the Corner" },
    { artist: "Dave Brubeck", title: "Time Out" },
    { artist: "Stan Getz & João Gilberto", title: "Getz/Gilberto" },
    { artist: "Chet Baker", title: "Chet Baker Sings" },
    { artist: "Bill Evans Trio", title: "Sunday at the Village Vanguard" },
    { artist: "Bill Evans Trio", title: "Waltz for Debby" },
    { artist: "Bill Evans", title: "Everybody Digs Bill Evans" },
    // Free Jazz / Avant-Garde
    { artist: "John Coltrane", title: "A Love Supreme" },
    { artist: "John Coltrane", title: "Giant Steps" },
    { artist: "John Coltrane", title: "My Favorite Things" },
    { artist: "John Coltrane", title: "Blue Train" },
    { artist: "John Coltrane", title: "Ascension" },
    { artist: "Ornette Coleman", title: "The Shape of Jazz to Come" },
    { artist: "Ornette Coleman", title: "Free Jazz: A Collective Improvisation" },
    { artist: "Albert Ayler", title: "Spiritual Unity" },
    { artist: "Eric Dolphy", title: "Out to Lunch!" },
    { artist: "Eric Dolphy", title: "Out There" },
    { artist: "Cecil Taylor", title: "Unit Structures" },
    { artist: "Sun Ra", title: "Space Is the Place" },
    { artist: "Sun Ra", title: "Lanquidity" },
    { artist: "Pharoah Sanders", title: "Karma" },
    { artist: "Pharoah Sanders", title: "Thembi" },
    { artist: "Alice Coltrane", title: "Journey in Satchidananda" },
    { artist: "Alice Coltrane", title: "Ptah, the El Daoud" },
    { artist: "Don Cherry", title: "Complete Communion" },
    { artist: "Art Ensemble of Chicago", title: "Les Stances à Sophie" },
    { artist: "Anthony Braxton", title: "For Alto" },
    // Vocal Jazz
    { artist: "Sarah Vaughan", title: "Sarah Vaughan with Clifford Brown" },
    { artist: "Nina Simone", title: "I Put a Spell on You" },
    { artist: "Nina Simone", title: "Wild Is the Wind" },
    { artist: "Nina Simone", title: "Pastel Blues" },
    { artist: "Abbey Lincoln", title: "We Insist!" },
    { artist: "Betty Carter", title: "The Audience with Betty Carter" },
    { artist: "Carmen McRae", title: "Carmen Sings Monk" },
    // Fusion
    { artist: "Herbie Hancock", title: "Head Hunters" },
    { artist: "Herbie Hancock", title: "Maiden Voyage" },
    { artist: "Herbie Hancock", title: "Empyrean Isles" },
    { artist: "Wayne Shorter", title: "Speak No Evil" },
    { artist: "Wayne Shorter", title: "Juju" },
    { artist: "Weather Report", title: "Heavy Weather" },
    { artist: "Weather Report", title: "Black Market" },
    { artist: "Return to Forever", title: "Romantic Warrior" },
    { artist: "Mahavishnu Orchestra", title: "The Inner Mounting Flame" },
    { artist: "Pat Metheny Group", title: "Pat Metheny Group" },
    { artist: "Pat Metheny", title: "Bright Size Life" },
    { artist: "Jaco Pastorius", title: "Jaco Pastorius" },
    { artist: "Joe Henderson", title: "Inner Urge" },
    { artist: "Joe Henderson", title: "Page One" },
    { artist: "Grant Green", title: "Green Street" },
    { artist: "Wes Montgomery", title: "The Incredible Jazz Guitar of Wes Montgomery" },
    { artist: "McCoy Tyner", title: "The Real McCoy" },
    // Post-Bop / Modern
    { artist: "Charles Mingus", title: "The Black Saint and the Sinner Lady" },
    { artist: "Charles Mingus", title: "Mingus Ah Um" },
    { artist: "Charles Mingus", title: "Pithecanthropus Erectus" },
    { artist: "Andrew Hill", title: "Point of Departure" },
    { artist: "Bobby Hutcherson", title: "Dialogue" },
    { artist: "Woody Shaw", title: "Rosewood" },
    // Contemporary / 80s-Present
    { artist: "Wynton Marsalis", title: "Black Codes (From the Underground)" },
    { artist: "Branford Marsalis", title: "The Dark Keys" },
    { artist: "Keith Jarrett", title: "The Köln Concert" },
    { artist: "Keith Jarrett", title: "Standards, Vol. 1" },
    { artist: "Brad Mehldau", title: "The Art of the Trio, Vol. 3: Songs" },
    { artist: "Pat Metheny", title: "The Way Up" },
    { artist: "Vijay Iyer", title: "Historicity" },
    { artist: "Robert Glasper Experiment", title: "Black Radio" },
    { artist: "Kamasi Washington", title: "The Epic" },
    { artist: "Kamasi Washington", title: "Heaven and Earth" },
    { artist: "Shabaka Hutchings", title: "Wisdom of Elders" },
    { artist: "Sons of Kemet", title: "Black to the Future" },
    { artist: "Nubya Garcia", title: "Source" },
    { artist: "Makaya McCraven", title: "Universal Beings" },
    { artist: "Makaya McCraven", title: "In These Times" },
    { artist: "Christian Scott aTunde Adjuah", title: "Stretch Music" },
    { artist: "Ambrose Akinmusire", title: "on the tender spot of every calloused moment" },
    { artist: "Esperanza Spalding", title: "Emily's D+Evolution" },
    { artist: "GoGo Penguin", title: "v2.0" },
    { artist: "Snarky Puppy", title: "We Like It Here" },
    { artist: "Tigran Hamasyan", title: "Mockroot" },
    { artist: "Hiromi", title: "Spiral" },
    // Japanese Jazz
    { artist: "Ryo Fukui", title: "Scenery" },
    { artist: "Toshiko Akiyoshi", title: "Insights" },
    // South African Jazz
    { artist: "Abdullah Ibrahim", title: "Mannenberg" },
    { artist: "Hugh Masekela", title: "Hope" },
    // Latin Jazz
    { artist: "Tito Puente", title: "Dance Mania" },
    { artist: "Cal Tjader", title: "Soul Sauce" },
    // Spiritual Jazz
    { artist: "John Coltrane", title: "Interstellar Space" },
    { artist: "Yusef Lateef", title: "Eastern Sounds" },
    { artist: "Mulatu Astatke", title: "Mulatu of Ethiopia" },
    { artist: "Mary Lou Williams", title: "Zodiac Suite" },
    { artist: "Max Roach", title: "We Insist! Freedom Now Suite" },
    { artist: "Ornette Coleman", title: "Science Fiction" },
    { artist: "Charles Lloyd", title: "Forest Flower" },
    { artist: "Ahmad Jamal", title: "At the Pershing: But Not for Me" },
    { artist: "Cannonball Adderley", title: "Somethin' Else" },
    { artist: "Art Pepper", title: "Art Pepper Meets the Rhythm Section" },
    { artist: "Thelonious Monk", title: "Solo Monk" },
    { artist: "Oscar Peterson", title: "Night Train" },
    { artist: "Dave Holland", title: "Conference of the Birds" },
    { artist: "Jack DeJohnette", title: "Special Edition" },
    { artist: "Tomasz Stańko", title: "From the Green Hill" },
    { artist: "Shabaka and the Ancestors", title: "Wisdom of Elders" },
    { artist: "BADBADNOTGOOD", title: "IV" },
    { artist: "Chet Baker", title: "Chet" },
    { artist: "Stan Getz", title: "Focus" },
    { artist: "Sonny Clark", title: "Cool Struttin'" },
    { artist: "Jimmy Smith", title: "The Sermon!" },
    { artist: "Grant Green", title: "Idle Moments" },
    { artist: "Cassandra Wilson", title: "Blue Light 'Til Dawn" },
    { artist: "Diana Krall", title: "The Look of Love" },
    { artist: "Gregory Porter", title: "Liquid Spirit" },
    { artist: "Kurt Rosenwinkel", title: "The Remedy" },
    { artist: "Chris Potter", title: "The Sirens" },
    { artist: "Wayne Shorter", title: "Emanon" },
  ],

  "r-b-soul": [
    // Classic Soul / Motown
    { artist: "Marvin Gaye", title: "What's Going On" },
    { artist: "Marvin Gaye", title: "Let's Get It On" },
    { artist: "Marvin Gaye", title: "I Want You" },
    { artist: "Marvin Gaye", title: "Here, My Dear" },
    { artist: "Stevie Wonder", title: "Songs in the Key of Life" },
    { artist: "Stevie Wonder", title: "Innervisions" },
    { artist: "Stevie Wonder", title: "Talking Book" },
    { artist: "Stevie Wonder", title: "Music of My Mind" },
    { artist: "Aretha Franklin", title: "I Never Loved a Man the Way I Love You" },
    { artist: "Aretha Franklin", title: "Lady Soul" },
    { artist: "Aretha Franklin", title: "Young, Gifted and Black" },
    { artist: "Otis Redding", title: "Otis Blue: Otis Redding Sings Soul" },
    { artist: "Otis Redding", title: "The Dock of the Bay" },
    { artist: "Sam Cooke", title: "Live at the Harlem Square Club, 1963" },
    { artist: "Sam Cooke", title: "Night Beat" },
    { artist: "Ray Charles", title: "Modern Sounds in Country and Western Music" },
    { artist: "Ray Charles", title: "The Genius of Ray Charles" },
    { artist: "The Temptations", title: "Cloud Nine" },
    { artist: "The Supremes", title: "Where Did Our Love Go" },
    { artist: "Smokey Robinson & The Miracles", title: "Going to a Go-Go" },
    { artist: "The Four Tops", title: "Reach Out" },
    { artist: "The Isley Brothers", title: "3 + 3" },
    { artist: "Curtis Mayfield", title: "Superfly" },
    { artist: "Curtis Mayfield", title: "Curtis" },
    { artist: "Al Green", title: "Let's Stay Together" },
    { artist: "Al Green", title: "Call Me" },
    { artist: "Al Green", title: "I'm Still in Love with You" },
    { artist: "Bill Withers", title: "Still Bill" },
    { artist: "Bill Withers", title: "Just as I Am" },
    { artist: "Donny Hathaway", title: "Live" },
    { artist: "Donny Hathaway", title: "Everything Is Everything" },
    { artist: "Bobby Womack", title: "Understanding" },
    { artist: "Isaac Hayes", title: "Hot Buttered Soul" },
    { artist: "Isaac Hayes", title: "Shaft" },
    { artist: "Gil Scott-Heron", title: "Pieces of a Man" },
    { artist: "Nina Simone", title: "I Put a Spell on You" },
    // Funk
    { artist: "James Brown", title: "Live at the Apollo" },
    { artist: "James Brown", title: "Star Time" },
    { artist: "Sly & The Family Stone", title: "There's a Riot Goin' On" },
    { artist: "Sly & The Family Stone", title: "Stand!" },
    { artist: "Parliament", title: "Mothership Connection" },
    { artist: "Funkadelic", title: "Maggot Brain" },
    { artist: "Funkadelic", title: "One Nation Under a Groove" },
    { artist: "Earth, Wind & Fire", title: "That's the Way of the World" },
    { artist: "Earth, Wind & Fire", title: "All 'N All" },
    { artist: "The Meters", title: "Rejuvenation" },
    { artist: "War", title: "The World Is a Ghetto" },
    { artist: "Tower of Power", title: "Tower of Power" },
    { artist: "Chaka Khan", title: "Chaka" },
    { artist: "Rick James", title: "Street Songs" },
    { artist: "Bootsy Collins", title: "Ahh...The Name Is Bootsy, Baby!" },
    // Disco
    { artist: "Donna Summer", title: "Bad Girls" },
    { artist: "Donna Summer", title: "I Remember Yesterday" },
    { artist: "Chic", title: "Risqué" },
    { artist: "Chic", title: "C'est Chic" },
    { artist: "Sister Sledge", title: "We Are Family" },
    { artist: "Gloria Gaynor", title: "Love Tracks" },
    // 80s R&B
    { artist: "Prince", title: "Purple Rain" },
    { artist: "Prince", title: "Sign o' the Times" },
    { artist: "Prince", title: "1999" },
    { artist: "Prince", title: "Dirty Mind" },
    { artist: "Michael Jackson", title: "Thriller" },
    { artist: "Michael Jackson", title: "Off the Wall" },
    { artist: "Michael Jackson", title: "Bad" },
    { artist: "Whitney Houston", title: "Whitney Houston" },
    { artist: "Whitney Houston", title: "Whitney" },
    { artist: "Luther Vandross", title: "Never Too Much" },
    { artist: "Anita Baker", title: "Rapture" },
    { artist: "Sade", title: "Diamond Life" },
    { artist: "Sade", title: "Love Deluxe" },
    { artist: "Janet Jackson", title: "Rhythm Nation 1814" },
    { artist: "Janet Jackson", title: "Control" },
    { artist: "Janet Jackson", title: "The Velvet Rope" },
    { artist: "Teena Marie", title: "Wild and Peaceful" },
    { artist: "Alexander O'Neal", title: "Hearsay" },
    // 90s R&B
    { artist: "TLC", title: "CrazySexyCool" },
    { artist: "Mary J. Blige", title: "My Life" },
    { artist: "Mary J. Blige", title: "What's the 411?" },
    { artist: "R. Kelly", title: "12 Play" },
    { artist: "Toni Braxton", title: "Toni Braxton" },
    { artist: "Aaliyah", title: "One in a Million" },
    { artist: "Aaliyah", title: "Aaliyah" },
    { artist: "Brandy", title: "Never Say Never" },
    { artist: "Destiny's Child", title: "The Writing's on the Wall" },
    { artist: "Boyz II Men", title: "II" },
    { artist: "Jodeci", title: "Diary of a Mad Band" },
    { artist: "Maxwell", title: "Maxwell's Urban Hang Suite" },
    // Neo-Soul
    { artist: "D'Angelo", title: "Voodoo" },
    { artist: "D'Angelo", title: "Brown Sugar" },
    { artist: "D'Angelo and The Vanguard", title: "Black Messiah" },
    { artist: "Erykah Badu", title: "Baduizm" },
    { artist: "Erykah Badu", title: "Mama's Gun" },
    { artist: "Erykah Badu", title: "New Amerykah Part One (4th World War)" },
    { artist: "Lauryn Hill", title: "The Miseducation of Lauryn Hill" },
    { artist: "Jill Scott", title: "Who Is Jill Scott? Words and Sounds Vol. 1" },
    { artist: "India.Arie", title: "Acoustic Soul" },
    { artist: "Musiq Soulchild", title: "Aijuswanaseing" },
    { artist: "Anthony Hamilton", title: "Comin' from Where I'm From" },
    // 2000s R&B
    { artist: "Beyoncé", title: "Lemonade" },
    { artist: "Beyoncé", title: "Beyoncé" },
    { artist: "Beyoncé", title: "Renaissance" },
    { artist: "Beyoncé", title: "B'Day" },
    { artist: "Usher", title: "Confessions" },
    { artist: "Alicia Keys", title: "Songs in A Minor" },
    { artist: "Amy Winehouse", title: "Back to Black" },
    { artist: "Janelle Monáe", title: "The ArchAndroid" },
    { artist: "Janelle Monáe", title: "Dirty Computer" },
    // 2010s-2020s R&B
    { artist: "Frank Ocean", title: "Blonde" },
    { artist: "Frank Ocean", title: "Channel Orange" },
    { artist: "The Weeknd", title: "House of Balloons" },
    { artist: "The Weeknd", title: "After Hours" },
    { artist: "SZA", title: "Ctrl" },
    { artist: "SZA", title: "SOS" },
    { artist: "Solange", title: "A Seat at the Table" },
    { artist: "Blood Orange", title: "Negro Swan" },
    { artist: "Blood Orange", title: "Freetown Sound" },
    { artist: "Anderson .Paak", title: "Malibu" },
    { artist: "Anderson .Paak", title: "Ventura" },
    { artist: "H.E.R.", title: "H.E.R." },
    { artist: "Summer Walker", title: "Over It" },
    { artist: "Jazmine Sullivan", title: "Heaux Tales" },
    { artist: "Ravyn Lenae", title: "Hypnos" },
    { artist: "Steve Lacy", title: "Gemini Rights" },
    { artist: "Daniel Caesar", title: "Freudian" },
    { artist: "Giveon", title: "Give or Take" },
    { artist: "Lucky Daye", title: "Painted" },
    { artist: "Snoh Aalegra", title: "Ugh, those feels again" },
    { artist: "Silk Sonic", title: "An Evening with Silk Sonic" },
    { artist: "Victoria Monét", title: "Jaguar" },
    // Gospel
    { artist: "Mahalia Jackson", title: "The World's Greatest Gospel Singer" },
    { artist: "The Staple Singers", title: "Be Altitude: Respect Yourself" },
    { artist: "Kirk Franklin", title: "The Nu Nation Project" },
    // International R&B/Soul
    { artist: "Fela Kuti", title: "Zombie" },
    { artist: "Fela Kuti", title: "Expensive Shit" },
    { artist: "Mulatu Astatke", title: "Mulatu of Ethiopia" },
    { artist: "Cesária Évora", title: "Miss Perfumado" },
    { artist: "Angélique Kidjo", title: "Logozo" },
    { artist: "Roberta Flack", title: "First Take" },
    { artist: "Teddy Pendergrass", title: "Teddy Pendergrass" },
    { artist: "The O'Jays", title: "Back Stabbers" },
    { artist: "Harold Melvin & the Blue Notes", title: "I Miss You" },
    { artist: "Minnie Riperton", title: "Perfect Angel" },
    { artist: "Phyllis Hyman", title: "Goddess of Love" },
    { artist: "Teena Marie", title: "Starchild" },
    { artist: "Keith Sweat", title: "Make It Last Forever" },
    { artist: "New Edition", title: "Heart Break" },
    { artist: "En Vogue", title: "Funky Divas" },
    { artist: "Xscape", title: "Off the Hook" },
    { artist: "112", title: "Room 112" },
    { artist: "Ciara", title: "Goodies" },
  ],

  "pop": [
    // 60s Pop
    { artist: "The Beach Boys", title: "Pet Sounds" },
    { artist: "The Beatles", title: "A Hard Day's Night" },
    { artist: "Simon & Garfunkel", title: "Bridge over Troubled Water" },
    { artist: "Simon & Garfunkel", title: "Bookends" },
    { artist: "Dusty Springfield", title: "Dusty in Memphis" },
    { artist: "Dionne Warwick", title: "Make Way for Dionne Warwick" },
    { artist: "Petula Clark", title: "Downtown" },
    { artist: "The Mamas & the Papas", title: "If You Can Believe Your Eyes and Ears" },
    { artist: "The Zombies", title: "Odessey and Oracle" },
    // 70s Pop
    { artist: "Carole King", title: "Tapestry" },
    { artist: "Joni Mitchell", title: "Blue" },
    { artist: "Joni Mitchell", title: "Court and Spark" },
    { artist: "Joni Mitchell", title: "Hejira" },
    { artist: "Elton John", title: "Goodbye Yellow Brick Road" },
    { artist: "Elton John", title: "Honky Château" },
    { artist: "Billy Joel", title: "The Stranger" },
    { artist: "ABBA", title: "Arrival" },
    { artist: "ABBA", title: "The Album" },
    { artist: "Bee Gees", title: "Saturday Night Fever" },
    { artist: "Stevie Wonder", title: "Songs in the Key of Life" },
    { artist: "Harry Nilsson", title: "Nilsson Schmilsson" },
    { artist: "Todd Rundgren", title: "Something/Anything?" },
    { artist: "10cc", title: "The Original Soundtrack" },
    { artist: "Sparks", title: "Kimono My House" },
    // 80s Pop / Synth-Pop
    { artist: "Michael Jackson", title: "Thriller" },
    { artist: "Prince", title: "Purple Rain" },
    { artist: "Madonna", title: "Like a Prayer" },
    { artist: "Madonna", title: "Ray of Light" },
    { artist: "Madonna", title: "True Blue" },
    { artist: "George Michael", title: "Faith" },
    { artist: "Whitney Houston", title: "Whitney Houston" },
    { artist: "Cyndi Lauper", title: "She's So Unusual" },
    { artist: "Pet Shop Boys", title: "Actually" },
    { artist: "Pet Shop Boys", title: "Behaviour" },
    { artist: "Tears for Fears", title: "Songs from the Big Chair" },
    { artist: "a-ha", title: "Hunting High and Low" },
    { artist: "Phil Collins", title: "Face Value" },
    { artist: "Peter Gabriel", title: "So" },
    { artist: "Kate Bush", title: "Hounds of Love" },
    { artist: "Kate Bush", title: "The Kick Inside" },
    { artist: "Kate Bush", title: "The Dreaming" },
    { artist: "Annie Lennox", title: "Diva" },
    { artist: "Eurythmics", title: "Touch" },
    { artist: "The Human League", title: "Dare" },
    { artist: "Yazoo", title: "Upstairs at Eric's" },
    // 90s Pop
    { artist: "Mariah Carey", title: "Daydream" },
    { artist: "Mariah Carey", title: "The Emancipation of Mimi" },
    { artist: "Britney Spears", title: "...Baby One More Time" },
    { artist: "TLC", title: "CrazySexyCool" },
    { artist: "Spice Girls", title: "Spice" },
    { artist: "No Doubt", title: "Tragic Kingdom" },
    { artist: "Sheryl Crow", title: "Sheryl Crow" },
    { artist: "Alanis Morissette", title: "Jagged Little Pill" },
    { artist: "Tori Amos", title: "Little Earthquakes" },
    { artist: "Björk", title: "Debut" },
    { artist: "Björk", title: "Post" },
    { artist: "Everything but the Girl", title: "Amplified Heart" },
    { artist: "The Cranberries", title: "No Need to Argue" },
    { artist: "Fiona Apple", title: "Tidal" },
    { artist: "Fiona Apple", title: "When the Pawn..." },
    // 2000s Pop
    { artist: "Beyoncé", title: "Dangerously in Love" },
    { artist: "OutKast", title: "Speakerboxxx/The Love Below" },
    { artist: "Justin Timberlake", title: "FutureSex/LoveSounds" },
    { artist: "Gwen Stefani", title: "Love. Angel. Music. Baby." },
    { artist: "Amy Winehouse", title: "Back to Black" },
    { artist: "Robyn", title: "Body Talk" },
    { artist: "Rihanna", title: "Good Girl Gone Bad" },
    { artist: "Rihanna", title: "Anti" },
    { artist: "Nelly Furtado", title: "Loose" },
    { artist: "Lily Allen", title: "Alright, Still" },
    { artist: "M.I.A.", title: "Kala" },
    { artist: "M.I.A.", title: "Arular" },
    // Art Pop / Indie Pop
    { artist: "Sufjan Stevens", title: "Carrie & Lowell" },
    { artist: "Sufjan Stevens", title: "Illinois" },
    { artist: "Vampire Weekend", title: "Modern Vampires of the City" },
    { artist: "Vampire Weekend", title: "Vampire Weekend" },
    { artist: "Grizzly Bear", title: "Veckatimest" },
    { artist: "Beach House", title: "Teen Dream" },
    { artist: "Beach House", title: "Depression Cherry" },
    { artist: "Fleet Foxes", title: "Fleet Foxes" },
    { artist: "Bon Iver", title: "For Emma, Forever Ago" },
    { artist: "Bon Iver", title: "22, A Million" },
    { artist: "St. Vincent", title: "St. Vincent" },
    { artist: "St. Vincent", title: "Actor" },
    { artist: "FKA twigs", title: "LP1" },
    { artist: "FKA twigs", title: "Magdalene" },
    { artist: "Perfume Genius", title: "No Shape" },
    // 2010s-2020s Pop
    { artist: "Lady Gaga", title: "The Fame Monster" },
    { artist: "Lady Gaga", title: "Born This Way" },
    { artist: "Lorde", title: "Pure Heroine" },
    { artist: "Lorde", title: "Melodrama" },
    { artist: "Carly Rae Jepsen", title: "Emotion" },
    { artist: "Taylor Swift", title: "1989" },
    { artist: "Taylor Swift", title: "Folklore" },
    { artist: "Taylor Swift", title: "Red" },
    { artist: "Adele", title: "21" },
    { artist: "Adele", title: "25" },
    { artist: "Ariana Grande", title: "Thank U, Next" },
    { artist: "Ariana Grande", title: "Sweetener" },
    { artist: "Dua Lipa", title: "Future Nostalgia" },
    { artist: "Billie Eilish", title: "When We All Fall Asleep, Where Do We Go?" },
    { artist: "Billie Eilish", title: "Happier Than Ever" },
    { artist: "Charli XCX", title: "Pop 2" },
    { artist: "Charli XCX", title: "How I'm Feeling Now" },
    { artist: "Charli XCX", title: "Brat" },
    { artist: "Olivia Rodrigo", title: "SOUR" },
    { artist: "Weyes Blood", title: "Titanic Rising" },
    { artist: "Caroline Polachek", title: "Pang" },
    { artist: "Magdalena Bay", title: "Mercurial World" },
    { artist: "Rina Sawayama", title: "Sawayama" },
    { artist: "Rosalía", title: "El Mal Querer" },
    { artist: "Rosalía", title: "Motomami" },
    { artist: "Bad Bunny", title: "Un Verano Sin Ti" },
    { artist: "Harry Styles", title: "Harry's House" },
    { artist: "Troye Sivan", title: "Something to Give Each Other" },
    { artist: "Mitski", title: "Puberty 2" },
    { artist: "Mitski", title: "Be the Cowboy" },
    // K-Pop / J-Pop
    { artist: "BTS", title: "Map of the Soul: 7" },
    { artist: "NewJeans", title: "NewJeans" },
    { artist: "Utada Hikaru", title: "First Love" },
    // Chamber Pop / Orchestral Pop
    { artist: "Scott Walker", title: "Scott 4" },
    { artist: "Rufus Wainwright", title: "Want One" },
    { artist: "The Divine Comedy", title: "Casanova" },
    { artist: "Haim", title: "Women in Music Pt. III" },
    { artist: "Phoebe Bridgers", title: "Punisher" },
    { artist: "boygenius", title: "the record" },
    { artist: "Chappell Roan", title: "The Rise and Fall of a Midwest Princess" },
    { artist: "Janelle Monáe", title: "The ArchAndroid" },
    { artist: "Lizzo", title: "Cuz I Love You" },
    { artist: "Kim Petras", title: "Feed the Beast" },
    { artist: "Christine and the Queens", title: "Chaleur Humaine" },
    { artist: "Robyn", title: "Robyn" },
    { artist: "The Weeknd", title: "Starboy" },
    { artist: "SZA", title: "Ctrl" },
    { artist: "Bruno Mars", title: "24K Magic" },
    { artist: "Lana Del Rey", title: "Norman Fucking Rockwell!" },
    { artist: "Lana Del Rey", title: "Born to Die" },
    { artist: "Sky Ferreira", title: "Night Time, My Time" },
    { artist: "Grimes", title: "Art Angels" },
    { artist: "Grimes", title: "Visions" },
    { artist: "The 1975", title: "A Brief Inquiry into Online Relationships" },
    { artist: "BROCKHAMPTON", title: "Saturation II" },
    { artist: "Glass Animals", title: "Dreamland" },
    { artist: "Tame Impala", title: "Currents" },
    { artist: "Jessie Ware", title: "What's Your Pleasure?" },
    { artist: "Raye", title: "My 21st Century Blues" },
    { artist: "Sabrina Carpenter", title: "Short n' Sweet" },
    { artist: "Clairo", title: "Sling" },
    { artist: "Japanese Breakfast", title: "Jubilee" },
  ],

  "metal": [
    // Proto-Metal / Classic Heavy Metal
    { artist: "Black Sabbath", title: "Black Sabbath" },
    { artist: "Black Sabbath", title: "Paranoid" },
    { artist: "Black Sabbath", title: "Master of Reality" },
    { artist: "Black Sabbath", title: "Vol. 4" },
    { artist: "Black Sabbath", title: "Sabbath Bloody Sabbath" },
    { artist: "Judas Priest", title: "British Steel" },
    { artist: "Judas Priest", title: "Screaming for Vengeance" },
    { artist: "Judas Priest", title: "Sad Wings of Destiny" },
    { artist: "Judas Priest", title: "Painkiller" },
    { artist: "Motörhead", title: "Ace of Spades" },
    { artist: "Motörhead", title: "Overkill" },
    { artist: "Rainbow", title: "Rising" },
    { artist: "Dio", title: "Holy Diver" },
    { artist: "Ozzy Osbourne", title: "Blizzard of Ozz" },
    // NWOBHM
    { artist: "Iron Maiden", title: "The Number of the Beast" },
    { artist: "Iron Maiden", title: "Powerslave" },
    { artist: "Iron Maiden", title: "Seventh Son of a Seventh Son" },
    { artist: "Iron Maiden", title: "Iron Maiden" },
    { artist: "Iron Maiden", title: "Brave New World" },
    { artist: "Diamond Head", title: "Lightning to the Nations" },
    { artist: "Angel Witch", title: "Angel Witch" },
    { artist: "Saxon", title: "Wheels of Steel" },
    { artist: "Venom", title: "Black Metal" },
    { artist: "Venom", title: "Welcome to Hell" },
    // Thrash Metal
    { artist: "Metallica", title: "Master of Puppets" },
    { artist: "Metallica", title: "Ride the Lightning" },
    { artist: "Metallica", title: "...And Justice for All" },
    { artist: "Metallica", title: "Kill 'Em All" },
    { artist: "Metallica", title: "Metallica" },
    { artist: "Slayer", title: "Reign in Blood" },
    { artist: "Slayer", title: "Seasons in the Abyss" },
    { artist: "Slayer", title: "South of Heaven" },
    { artist: "Megadeth", title: "Rust in Peace" },
    { artist: "Megadeth", title: "Peace Sells... but Who's Buying?" },
    { artist: "Megadeth", title: "Countdown to Extinction" },
    { artist: "Anthrax", title: "Among the Living" },
    { artist: "Exodus", title: "Bonded by Blood" },
    { artist: "Testament", title: "The Legacy" },
    { artist: "Kreator", title: "Pleasure to Kill" },
    { artist: "Sodom", title: "Agent Orange" },
    { artist: "Destruction", title: "Eternal Devastation" },
    { artist: "Sepultura", title: "Arise" },
    { artist: "Sepultura", title: "Beneath the Remains" },
    { artist: "Pantera", title: "Vulgar Display of Power" },
    { artist: "Pantera", title: "Cowboys from Hell" },
    // Death Metal
    { artist: "Death", title: "Symbolic" },
    { artist: "Death", title: "Human" },
    { artist: "Death", title: "Leprosy" },
    { artist: "Death", title: "Individual Thought Patterns" },
    { artist: "Morbid Angel", title: "Altars of Madness" },
    { artist: "Morbid Angel", title: "Blessed Are the Sick" },
    { artist: "Cannibal Corpse", title: "Tomb of the Mutilated" },
    { artist: "Obituary", title: "Cause of Death" },
    { artist: "Entombed", title: "Left Hand Path" },
    { artist: "Dismember", title: "Like an Everflowing Stream" },
    { artist: "Bolt Thrower", title: "The IVth Crusade" },
    { artist: "At the Gates", title: "Slaughter of the Soul" },
    { artist: "Carcass", title: "Heartwork" },
    { artist: "Carcass", title: "Necroticism – Descanting the Insalubrious" },
    { artist: "Suffocation", title: "Pierced from Within" },
    { artist: "Gorguts", title: "Obscura" },
    { artist: "Atheist", title: "Unquestionable Presence" },
    { artist: "Cynic", title: "Focus" },
    { artist: "Nile", title: "Annihilation of the Wicked" },
    { artist: "Bloodbath", title: "Nightmares Made Flesh" },
    // Black Metal
    { artist: "Bathory", title: "Under the Sign of the Black Mark" },
    { artist: "Bathory", title: "Blood Fire Death" },
    { artist: "Mayhem", title: "De Mysteriis Dom Sathanas" },
    { artist: "Burzum", title: "Hvis lyset tar oss" },
    { artist: "Burzum", title: "Filosofem" },
    { artist: "Darkthrone", title: "A Blaze in the Northern Sky" },
    { artist: "Darkthrone", title: "Transilvanian Hunger" },
    { artist: "Emperor", title: "In the Nightside Eclipse" },
    { artist: "Emperor", title: "Anthems to the Welkin at Dusk" },
    { artist: "Immortal", title: "At the Heart of Winter" },
    { artist: "Dissection", title: "Storm of the Light's Bane" },
    { artist: "Enslaved", title: "Below the Lights" },
    { artist: "Blut Aus Nord", title: "The Work Which Transforms God" },
    { artist: "Deathspell Omega", title: "Si Monvmentvm Reqvires, Circvmspice" },
    { artist: "Wolves in the Throne Room", title: "Two Hunters" },
    { artist: "Agalloch", title: "The Mantle" },
    { artist: "Alcest", title: "Écailles de Lune" },
    { artist: "Mgła", title: "Exercises in Futility" },
    // Doom Metal
    { artist: "Candlemass", title: "Epicus Doomicus Metallicus" },
    { artist: "Saint Vitus", title: "Born Too Late" },
    { artist: "Electric Wizard", title: "Dopethrone" },
    { artist: "Sleep", title: "Dopesmoker" },
    { artist: "Sleep", title: "Sleep's Holy Mountain" },
    { artist: "Sunn O)))", title: "Monoliths & Dimensions" },
    { artist: "Bell Witch", title: "Mirror Reaper" },
    { artist: "Yob", title: "Clearing the Path to Ascend" },
    // Progressive Metal
    { artist: "Dream Theater", title: "Images and Words" },
    { artist: "Dream Theater", title: "Metropolis Pt. 2: Scenes from a Memory" },
    { artist: "Tool", title: "Lateralus" },
    { artist: "Tool", title: "Ænima" },
    { artist: "Tool", title: "Fear Inoculum" },
    { artist: "Opeth", title: "Blackwater Park" },
    { artist: "Opeth", title: "Still Life" },
    { artist: "Opeth", title: "Ghost Reveries" },
    { artist: "Mastodon", title: "Leviathan" },
    { artist: "Mastodon", title: "Crack the Skye" },
    { artist: "Between the Buried and Me", title: "Colors" },
    { artist: "Meshuggah", title: "Destroy Erase Improve" },
    { artist: "Meshuggah", title: "ObZen" },
    { artist: "Gojira", title: "From Mars to Sirius" },
    { artist: "Gojira", title: "The Way of All Flesh" },
    // Power Metal
    { artist: "Helloween", title: "Keeper of the Seven Keys: Part II" },
    { artist: "Helloween", title: "Keeper of the Seven Keys: Part I" },
    { artist: "Blind Guardian", title: "Nightfall in Middle-Earth" },
    { artist: "Blind Guardian", title: "Imaginations from the Other Side" },
    { artist: "Stratovarius", title: "Visions" },
    { artist: "Rhapsody of Fire", title: "Symphony of Enchanted Lands" },
    { artist: "Gamma Ray", title: "Land of the Free" },
    // Sludge / Post-Metal
    { artist: "Neurosis", title: "Through Silver in Blood" },
    { artist: "Neurosis", title: "Times of Grace" },
    { artist: "Isis", title: "Oceanic" },
    { artist: "Isis", title: "Panopticon" },
    { artist: "Converge", title: "Jane Doe" },
    { artist: "The Dillinger Escape Plan", title: "Calculating Infinity" },
    { artist: "Baroness", title: "Purple" },
    { artist: "Deafheaven", title: "Sunbather" },
    { artist: "Pallbearer", title: "Sorrow and Extinction" },
    // Modern / 2010s-2020s Metal
    { artist: "Power Trip", title: "Nightmare Logic" },
    { artist: "Tomb Mold", title: "Manor of Infinite Forms" },
    { artist: "Blood Incantation", title: "Hidden History of the Human Race" },
    { artist: "Undeath", title: "It's Time... to Rise from the Grave" },
    { artist: "Liturgy", title: "Aesthethica" },
    { artist: "Lorna Shore", title: "Pain Remains" },
    { artist: "Knocked Loose", title: "A Tear in the Fabric of Life" },
    { artist: "Spiritbox", title: "Eternal Blue" },
    { artist: "Rammstein", title: "Mutter" },
    { artist: "System of a Down", title: "Toxicity" },
    { artist: "Deftones", title: "White Pony" },
    { artist: "Deftones", title: "Around the Fur" },
    { artist: "Lamb of God", title: "Ashes of the Wake" },
    { artist: "High on Fire", title: "De Vermis Mysteriis" },
    { artist: "Mastodon", title: "Blood Mountain" },
    { artist: "The Sword", title: "Age of Winters" },
    { artist: "Kvelertak", title: "Kvelertak" },
    { artist: "Vektor", title: "Terminal Redux" },
    { artist: "Horrendous", title: "Idol" },
    { artist: "Cattle Decapitation", title: "Death Atlas" },
    { artist: "Ulcerate", title: "Stare into Death and Be Still" },
    { artist: "Oranssi Pazuzu", title: "Mestarin kynsi" },
    { artist: "Imperial Triumphant", title: "Alphaville" },
    { artist: "Full of Hell", title: "Garden of Burning Apparitions" },
    { artist: "Zeal & Ardor", title: "Zeal & Ardor" },
    { artist: "Wormrot", title: "Voices" },
    { artist: "Archspire", title: "Bleed the Future" },
  ],

  "folk-country": [
    // Traditional Folk / 60s Folk Revival
    { artist: "Bob Dylan", title: "Highway 61 Revisited" },
    { artist: "Bob Dylan", title: "Blonde on Blonde" },
    { artist: "Bob Dylan", title: "The Freewheelin' Bob Dylan" },
    { artist: "Bob Dylan", title: "Bringing It All Back Home" },
    { artist: "Bob Dylan", title: "Blood on the Tracks" },
    { artist: "Bob Dylan", title: "The Basement Tapes" },
    { artist: "Bob Dylan", title: "John Wesley Harding" },
    { artist: "Woody Guthrie", title: "Dust Bowl Ballads" },
    { artist: "Pete Seeger", title: "We Shall Overcome" },
    { artist: "Joan Baez", title: "Joan Baez" },
    { artist: "Joan Baez", title: "Diamonds & Rust" },
    { artist: "Joni Mitchell", title: "Blue" },
    { artist: "Joni Mitchell", title: "Hejira" },
    { artist: "Joni Mitchell", title: "For the Roses" },
    { artist: "Leonard Cohen", title: "Songs of Leonard Cohen" },
    { artist: "Leonard Cohen", title: "Songs of Love and Hate" },
    { artist: "Leonard Cohen", title: "I'm Your Man" },
    { artist: "Leonard Cohen", title: "You Want It Darker" },
    { artist: "Nick Drake", title: "Pink Moon" },
    { artist: "Nick Drake", title: "Five Leaves Left" },
    { artist: "Nick Drake", title: "Bryter Layter" },
    { artist: "Tim Buckley", title: "Happy Sad" },
    { artist: "Tim Buckley", title: "Starsailor" },
    { artist: "Fairport Convention", title: "Liege & Lief" },
    { artist: "Pentangle", title: "Basket of Light" },
    { artist: "Sandy Denny", title: "The North Star Grassman and the Ravens" },
    { artist: "Bert Jansch", title: "Bert Jansch" },
    { artist: "John Martyn", title: "Solid Air" },
    { artist: "Richard Thompson", title: "Shoot Out the Lights" },
    { artist: "Vashti Bunyan", title: "Just Another Diamond Day" },
    { artist: "Donovan", title: "Sunshine Superman" },
    { artist: "Simon & Garfunkel", title: "Parsley, Sage, Rosemary and Thyme" },
    { artist: "Phil Ochs", title: "I Ain't Marching Anymore" },
    { artist: "Cat Stevens", title: "Tea for the Tillerman" },
    { artist: "James Taylor", title: "Sweet Baby James" },
    // Classic Country
    { artist: "Hank Williams", title: "40 Greatest Hits" },
    { artist: "Johnny Cash", title: "At Folsom Prison" },
    { artist: "Johnny Cash", title: "American IV: The Man Comes Around" },
    { artist: "Johnny Cash", title: "At San Quentin" },
    { artist: "Patsy Cline", title: "Patsy Cline's Greatest Hits" },
    { artist: "Willie Nelson", title: "Red Headed Stranger" },
    { artist: "Willie Nelson", title: "Stardust" },
    { artist: "Waylon Jennings", title: "Honky Tonk Heroes" },
    { artist: "Merle Haggard", title: "Mama Tried" },
    { artist: "Merle Haggard", title: "Sing Me Back Home" },
    { artist: "George Jones", title: "I Am What I Am" },
    { artist: "Tammy Wynette", title: "Stand by Your Man" },
    { artist: "Loretta Lynn", title: "Coal Miner's Daughter" },
    { artist: "Dolly Parton", title: "Coat of Many Colors" },
    { artist: "Dolly Parton", title: "Jolene" },
    { artist: "Gram Parsons", title: "Grievous Angel" },
    { artist: "Gram Parsons", title: "GP" },
    { artist: "Townes Van Zandt", title: "Townes Van Zandt" },
    { artist: "Townes Van Zandt", title: "Live at the Old Quarter, Houston, Texas" },
    { artist: "Guy Clark", title: "Old No. 1" },
    { artist: "Emmylou Harris", title: "Wrecking Ball" },
    { artist: "Emmylou Harris", title: "Pieces of the Sky" },
    // Bluegrass
    { artist: "Bill Monroe", title: "The Essential Bill Monroe and His Blue Grass Boys" },
    { artist: "Flatt & Scruggs", title: "Foggy Mountain Banjo" },
    { artist: "The Stanley Brothers", title: "The Complete Columbia Stanley Brothers" },
    { artist: "Alison Krauss", title: "Now That I've Found You: A Collection" },
    { artist: "Nickel Creek", title: "Nickel Creek" },
    { artist: "Chris Thile", title: "Bach: Sonatas and Partitas, Vol. 1" },
    // Blues
    { artist: "Robert Johnson", title: "King of the Delta Blues Singers" },
    { artist: "Muddy Waters", title: "The Anthology: 1947-1972" },
    { artist: "Howlin' Wolf", title: "Moanin' in the Moonlight" },
    { artist: "B.B. King", title: "Live at the Regal" },
    { artist: "John Lee Hooker", title: "The Healer" },
    { artist: "Son House", title: "Father of Folk Blues" },
    { artist: "Skip James", title: "Today!" },
    { artist: "Mississippi John Hurt", title: "Today!" },
    { artist: "Lightnin' Hopkins", title: "Mojo Hand" },
    { artist: "Elmore James", title: "The Sky Is Crying" },
    { artist: "T-Bone Walker", title: "T-Bone Blues" },
    { artist: "Albert King", title: "Born Under a Bad Sign" },
    { artist: "Freddie King", title: "Let's Hide Away and Dance Away" },
    { artist: "Etta James", title: "At Last!" },
    // Alt-Country / Americana
    { artist: "Uncle Tupelo", title: "No Depression" },
    { artist: "Wilco", title: "Yankee Hotel Foxtrot" },
    { artist: "Wilco", title: "A Ghost Is Born" },
    { artist: "Ryan Adams", title: "Heartbreaker" },
    { artist: "Lucinda Williams", title: "Car Wheels on a Gravel Road" },
    { artist: "Steve Earle", title: "Guitar Town" },
    { artist: "Drive-By Truckers", title: "Southern Rock Opera" },
    { artist: "Gillian Welch", title: "Revival" },
    { artist: "Gillian Welch", title: "Time (The Revelator)" },
    { artist: "Old Crow Medicine Show", title: "O.C.M.S." },
    { artist: "Jason Isbell", title: "Southeastern" },
    { artist: "Jason Isbell and the 400 Unit", title: "The Nashville Sound" },
    { artist: "Sturgill Simpson", title: "Metamodern Sounds in Country Music" },
    { artist: "Sturgill Simpson", title: "A Sailor's Guide to Earth" },
    { artist: "Tyler Childers", title: "Purgatory" },
    { artist: "Colter Wall", title: "Songs of the Plains" },
    { artist: "Chris Stapleton", title: "Traveller" },
    { artist: "Margo Price", title: "Midwest Farmer's Daughter" },
    { artist: "Sierra Ferrell", title: "Long Time Coming" },
    { artist: "Waxahatchee", title: "Saint Cloud" },
    { artist: "Kacey Musgraves", title: "Golden Hour" },
    { artist: "Brandi Carlile", title: "By the Way, I Forgive You" },
    { artist: "The Avett Brothers", title: "I and Love and You" },
    // Contemporary Folk
    { artist: "Iron & Wine", title: "Our Endless Numbered Days" },
    { artist: "Iron & Wine", title: "The Creek Drank the Cradle" },
    { artist: "Fleet Foxes", title: "Fleet Foxes" },
    { artist: "Fleet Foxes", title: "Helplessness Blues" },
    { artist: "Bon Iver", title: "For Emma, Forever Ago" },
    { artist: "Sufjan Stevens", title: "Carrie & Lowell" },
    { artist: "The Tallest Man on Earth", title: "The Wild Hunt" },
    { artist: "Laura Marling", title: "Once I Was an Eagle" },
    { artist: "Big Thief", title: "U.F.O.F." },
    { artist: "Adrianne Lenker", title: "songs" },
    { artist: "Phoebe Bridgers", title: "Punisher" },
    { artist: "Andy Shauf", title: "The Neon Skyline" },
    // World / International Folk
    { artist: "Buena Vista Social Club", title: "Buena Vista Social Club" },
    { artist: "Ali Farka Touré", title: "Talking Timbuktu" },
    { artist: "Tinariwen", title: "Amassakoul" },
    { artist: "Ravi Shankar", title: "Three Ragas" },
    { artist: "Caetano Veloso", title: "Transa" },
    { artist: "Gilberto Gil", title: "Refazenda" },
    { artist: "Os Mutantes", title: "Os Mutantes" },
    { artist: "Tropicália", title: "Tropicália: ou Panis et Circensis" },
    { artist: "Mercedes Sosa", title: "30 Años" },
    { artist: "Víctor Jara", title: "Te Recuerdo Amanda" },
    { artist: "Nusrat Fateh Ali Khan", title: "Mustt Mustt" },
    { artist: "Tinariwen", title: "Emmaar" },
    { artist: "Bombino", title: "Nomad" },
    { artist: "Mdou Moctar", title: "Afrique Victime" },
    { artist: "Khruangbin", title: "Con Todo El Mundo" },
    { artist: "John Prine", title: "John Prine" },
    { artist: "John Prine", title: "The Tree of Forgiveness" },
    { artist: "Iris DeMent", title: "Infamous Angel" },
    { artist: "Neko Case", title: "Fox Confessor Brings the Flood" },
    { artist: "The Handsome Family", title: "Singing Bones" },
    { artist: "Bonnie 'Prince' Billy", title: "I See a Darkness" },
    { artist: "Bill Callahan", title: "Sometimes I Wish We Were an Eagle" },
    { artist: "Sun Kil Moon", title: "Ghosts of the Great Highway" },
    { artist: "Richard Dawson", title: "Peasant" },
    { artist: "Jessica Pratt", title: "Quiet Signs" },
    { artist: "Joanna Newsom", title: "Ys" },
    { artist: "Joanna Newsom", title: "Have One on Me" },
    { artist: "Angel Olsen", title: "My Woman" },
    { artist: "Aldous Harding", title: "Designer" },
    { artist: "Weyes Blood", title: "Titanic Rising" },
    { artist: "Faye Webster", title: "I Know I'm Funny haha" },
    { artist: "Charley Crockett", title: "The Man from Waco" },
    { artist: "Zach Bryan", title: "American Heartbreak" },
    { artist: "Billy Strings", title: "Renewal" },
    { artist: "Amália Rodrigues", title: "The Art of Amália" },
    { artist: "Oumou Sangaré", title: "Worotan" },
    { artist: "Youssou N'Dour", title: "The Guide (Wommat)" },
    { artist: "Rokia Traoré", title: "Bowmboï" },
  ],
};
