// Maps Last.fm / MusicBrainz freeform tags to our genre taxonomy slugs
const TAG_TO_SLUG: Record<string, string> = {
  // Rock
  rock: "rock",
  "classic rock": "rock",
  "hard rock": "rock",
  "alternative rock": "alternative-rock",
  "alt-rock": "alternative-rock",
  alternative: "alternative-rock",
  indie: "indie-rock",
  "indie rock": "indie-rock",
  punk: "punk",
  "punk rock": "punk",
  "pop punk": "punk",
  "hardcore punk": "punk",
  "post-punk": "post-punk",
  "post punk": "post-punk",
  "new wave": "post-punk",
  "progressive rock": "progressive-rock",
  "prog rock": "progressive-rock",
  "art rock": "progressive-rock",
  "psychedelic rock": "psychedelic-rock",
  psychedelic: "psychedelic-rock",
  "psychedelia": "psychedelic-rock",
  grunge: "grunge",
  shoegaze: "shoegaze",
  "dream pop": "shoegaze",
  "glam rock": "rock",
  "garage rock": "rock",
  "blues rock": "rock",
  "folk rock": "rock",
  "soft rock": "rock",
  "southern rock": "rock",
  "roots rock": "rock",
  "stoner rock": "rock",
  "math rock": "rock",
  "noise rock": "rock",
  "post-rock": "rock",
  emo: "rock",
  "britpop": "alternative-rock",

  // Hip-Hop
  "hip-hop": "hip-hop",
  "hip hop": "hip-hop",
  rap: "hip-hop",
  "east coast hip hop": "east-coast-hip-hop",
  "east coast": "east-coast-hip-hop",
  "west coast hip hop": "west-coast-hip-hop",
  "west coast": "west-coast-hip-hop",
  "southern hip hop": "southern-hip-hop",
  "trap": "trap",
  "conscious hip hop": "conscious-hip-hop",
  "conscious rap": "conscious-hip-hop",
  "underground hip hop": "hip-hop",
  "gangsta rap": "hip-hop",
  "boom bap": "hip-hop",
  "alternative hip hop": "hip-hop",

  // Electronic
  electronic: "electronic",
  electronica: "electronic",
  "ambient": "ambient",
  "house": "house",
  "deep house": "house",
  "acid house": "house",
  "techno": "techno",
  "detroit techno": "techno",
  "drum and bass": "drum-and-bass",
  "drum n bass": "drum-and-bass",
  dnb: "drum-and-bass",
  "jungle": "drum-and-bass",
  "idm": "idm",
  "intelligent dance music": "idm",
  "trip hop": "trip-hop",
  "trip-hop": "trip-hop",
  "downtempo": "electronic",
  "synth-pop": "electronic",
  "synthpop": "electronic",
  edm: "electronic",
  "industrial": "electronic",
  "ebm": "electronic",
  "experimental electronic": "electronic",
  "glitch": "electronic",
  "dubstep": "electronic",
  "trance": "electronic",

  // Jazz
  jazz: "jazz",
  "bebop": "bebop",
  "hard bop": "hard-bop",
  "cool jazz": "cool-jazz",
  "modal jazz": "jazz",
  "free jazz": "free-jazz",
  "avant-garde jazz": "free-jazz",
  "fusion": "jazz-fusion",
  "jazz fusion": "jazz-fusion",
  "jazz-funk": "jazz-fusion",
  "smooth jazz": "jazz",
  "latin jazz": "jazz",
  "swing": "jazz",
  "big band": "jazz",
  "vocal jazz": "jazz",
  "post-bop": "jazz",

  // R&B / Soul
  "rhythm and blues": "r-b-soul",
  "r&b": "r-b-soul",
  rnb: "r-b-soul",
  soul: "soul",
  "neo soul": "neo-soul",
  "neo-soul": "neo-soul",
  funk: "funk",
  "p-funk": "funk",
  motown: "motown",
  gospel: "r-b-soul",
  "contemporary r&b": "r-b-soul",
  "new jack swing": "r-b-soul",
  disco: "r-b-soul",

  // Pop
  pop: "pop",
  "synth pop": "synth-pop",
  "art pop": "art-pop",
  "chamber pop": "art-pop",
  "baroque pop": "art-pop",
  "indie pop": "indie-pop",
  "power pop": "pop",
  "dance pop": "pop",
  "electropop": "pop",
  "k-pop": "pop",
  "j-pop": "pop",
  "latin pop": "pop",
  "teen pop": "pop",
  singer: "pop",
  "singer-songwriter": "pop",

  // Metal
  metal: "metal",
  "heavy metal": "metal",
  "thrash metal": "thrash-metal",
  "thrash": "thrash-metal",
  "death metal": "death-metal",
  "black metal": "black-metal",
  "doom metal": "doom-metal",
  "stoner metal": "doom-metal",
  "sludge metal": "doom-metal",
  "progressive metal": "progressive-metal",
  "prog metal": "progressive-metal",
  "power metal": "metal",
  "speed metal": "metal",
  "nu metal": "metal",
  "metalcore": "metal",
  "post-metal": "metal",
  "gothic metal": "metal",
  "symphonic metal": "metal",
  "folk metal": "metal",
  nwobhm: "metal",

  // Folk / Country
  folk: "folk-country",
  country: "country",
  "alt-country": "alt-country",
  "alternative country": "alt-country",
  "americana": "americana",
  bluegrass: "folk-country",
  "contemporary folk": "folk-country",
  "traditional folk": "folk-country",
  "outlaw country": "country",
  "country rock": "country",
  blues: "folk-country",
  "delta blues": "folk-country",
  "electric blues": "folk-country",
  "country blues": "folk-country",
  "world music": "folk-country",
  "celtic": "folk-country",
  "roots": "folk-country",
};

export function mapTags(tags: string[], fallbackGenres: string[]): string[] {
  const mapped = new Set<string>();

  for (const tag of tags) {
    const slug = TAG_TO_SLUG[tag.toLowerCase()];
    if (slug) mapped.add(slug);
  }

  // If no tags mapped, use fallback genres from candidate list
  if (mapped.size === 0) {
    for (const g of fallbackGenres) {
      mapped.add(g);
    }
  }

  return Array.from(mapped);
}
