export const electronic: Array<{ artist: string; title: string }> = [
  // Ambient / Early Electronic
  { artist: "Brian Eno", title: "Ambient 1: Music for Airports" },
  { artist: "Brian Eno", title: "Another Green World" },
  { artist: "Brian Eno", title: "Music for Films" },
  { artist: "Tangerine Dream", title: "Phaedra" },
  { artist: "Tangerine Dream", title: "Rubycon" },
  { artist: "Klaus Schulze", title: "Timewind" },
  { artist: "Vangelis", title: "Blade Runner" },
  { artist: "Jean-Michel Jarre", title: "Oxygène" },
  { artist: "Kraftwerk", title: "Trans-Europe Express" },
  { artist: "Kraftwerk", title: "The Man-Machine" },
  { artist: "Kraftwerk", title: "Computer World" },
  { artist: "Kraftwerk", title: "Autobahn" },
  { artist: "Yellow Magic Orchestra", title: "Solid State Survivor" },
  { artist: "Yellow Magic Orchestra", title: "BGM" },
  // Synth-Pop / New Wave Electronic
  { artist: "Depeche Mode", title: "Violator" },
  { artist: "Depeche Mode", title: "Music for the Masses" },
  { artist: "Depeche Mode", title: "Black Celebration" },
  { artist: "New Order", title: "Technique" },
  { artist: "Orchestral Manoeuvres in the Dark", title: "Architecture & Morality" },
  { artist: "Gary Numan", title: "The Pleasure Principle" },
  { artist: "Cabaret Voltaire", title: "Red Mecca" },
  { artist: "Throbbing Gristle", title: "20 Jazz Funk Greats" },
  { artist: "Einstürzende Neubauten", title: "Halber Mensch" },
  { artist: "SPK", title: "Leichenschrei" },
  { artist: "Front 242", title: "Front by Front" },
  // House / Techno
  { artist: "Frankie Knuckles", title: "Beyond the Mix" },
  { artist: "Larry Heard", title: "Amnesia" },
  { artist: "Derrick May", title: "Innovator" },
  { artist: "Jeff Mills", title: "Waveform Transmission Vol. 3" },
  { artist: "Underground Resistance", title: "Revolution for Change" },
  { artist: "Juan Atkins", title: "20 Years: 1985-2005" },
  { artist: "Model 500", title: "Classics" },
  { artist: "The Orb", title: "The Orb's Adventures Beyond the Ultraworld" },
  { artist: "Orbital", title: "Orbital 2" },
  { artist: "Underworld", title: "dubnobasswithmyheadman" },
  { artist: "Underworld", title: "Second Toughest in the Infants" },
  { artist: "The Chemical Brothers", title: "Dig Your Own Hole" },
  { artist: "The Chemical Brothers", title: "Surrender" },
  { artist: "Fatboy Slim", title: "You've Come a Long Way, Baby" },
  { artist: "The Prodigy", title: "The Fat of the Land" },
  { artist: "The Prodigy", title: "Music for the Jilted Generation" },
  { artist: "Daft Punk", title: "Homework" },
  { artist: "Daft Punk", title: "Discovery" },
  { artist: "Daft Punk", title: "Random Access Memories" },
  { artist: "Basement Jaxx", title: "Remedy" },
  { artist: "Laurent Garnier", title: "30" },
  // Trip-Hop
  { artist: "Massive Attack", title: "Blue Lines" },
  { artist: "Massive Attack", title: "Mezzanine" },
  { artist: "Massive Attack", title: "Protection" },
  { artist: "Portishead", title: "Dummy" },
  { artist: "Portishead", title: "Third" },
  { artist: "Tricky", title: "Maxinquaye" },
  { artist: "DJ Shadow", title: "Endtroducing....." },
  { artist: "UNKLE", title: "Psyence Fiction" },
  // IDM / Experimental
  { artist: "Aphex Twin", title: "Selected Ambient Works 85-92" },
  { artist: "Aphex Twin", title: "Selected Ambient Works Volume II" },
  { artist: "Aphex Twin", title: "Richard D. James Album" },
  { artist: "Aphex Twin", title: "Drukqs" },
  { artist: "Autechre", title: "Tri Repetae" },
  { artist: "Autechre", title: "LP5" },
  { artist: "Autechre", title: "Amber" },
  { artist: "Boards of Canada", title: "Music Has the Right to Children" },
  { artist: "Boards of Canada", title: "Geogaddi" },
  { artist: "Squarepusher", title: "Feed Me Weird Things" },
  { artist: "Squarepusher", title: "Hard Normal Daddy" },
  { artist: "μ-Ziq", title: "Lunatic Harness" },
  { artist: "Four Tet", title: "Rounds" },
  { artist: "Four Tet", title: "There Is Love in You" },
  { artist: "Four Tet", title: "New Energy" },
  // Drum & Bass / Jungle
  { artist: "Goldie", title: "Timeless" },
  { artist: "Roni Size / Reprazent", title: "New Forms" },
  { artist: "LTJ Bukem", title: "Logical Progression" },
  { artist: "Photek", title: "Modus Operandi" },
  // Ambient / Drone / Post-2000
  { artist: "Tim Hecker", title: "Harmony in Ultraviolet" },
  { artist: "Tim Hecker", title: "Ravedeath, 1972" },
  { artist: "Tim Hecker", title: "Virgins" },
  { artist: "Fennesz", title: "Endless Summer" },
  { artist: "Stars of the Lid", title: "The Tired Sounds of Stars of the Lid" },
  { artist: "Gas", title: "Pop" },
  { artist: "William Basinski", title: "The Disintegration Loops" },
  { artist: "Oneohtrix Point Never", title: "R Plus Seven" },
  { artist: "Oneohtrix Point Never", title: "Age Of" },
  { artist: "Oneohtrix Point Never", title: "Garden of Delete" },
  // Contemporary Electronic / 2000s-2020s
  { artist: "Burial", title: "Untrue" },
  { artist: "Burial", title: "Burial" },
  { artist: "James Blake", title: "James Blake" },
  { artist: "Flying Lotus", title: "Cosmogramma" },
  { artist: "Flying Lotus", title: "Los Angeles" },
  { artist: "Flying Lotus", title: "You're Dead!" },
  { artist: "Nicolas Jaar", title: "Space Is Only Noise" },
  { artist: "Arca", title: "KiCk i" },
  { artist: "Arca", title: "Arca" },
  { artist: "SOPHIE", title: "Oil of Every Pearl's Un-Insides" },
  { artist: "Kelela", title: "Take Me Apart" },
  { artist: "Kelela", title: "Raven" },
  { artist: "Caribou", title: "Swim" },
  { artist: "Caribou", title: "Our Love" },
  { artist: "Jamie xx", title: "In Colour" },
  { artist: "Disclosure", title: "Settle" },
  { artist: "Flume", title: "Flume" },
  { artist: "Kaytranada", title: "99.9%" },
  { artist: "Jon Hopkins", title: "Immunity" },
  { artist: "Jon Hopkins", title: "Singularity" },
  { artist: "Floating Points", title: "Crush" },
  { artist: "Floating Points, Pharoah Sanders & The London Symphony Orchestra", title: "Promises" },
  { artist: "Andy Stott", title: "Luxury Problems" },
  { artist: "The Avalanches", title: "Since I Left You" },
  { artist: "The Avalanches", title: "Wildflower" },
  { artist: "Björk", title: "Homogenic" },
  { artist: "Björk", title: "Vespertine" },
  { artist: "Björk", title: "Post" },
  { artist: "M83", title: "Hurry Up, We're Dreaming" },
  { artist: "Justice", title: "†" },
  { artist: "Gesaffelstein", title: "Aleph" },
  { artist: "Skrillex", title: "Scary Monsters and Nice Sprites" },
  { artist: "Ryuichi Sakamoto", title: "async" },
  { artist: "Yaeji", title: "What We Drew" },
  { artist: "Helena Hauff", title: "Qualm" },
  { artist: "Peggy Gou", title: "I Hear You" },
  { artist: "Objekt", title: "Cocoon Crush" },
  { artist: "Holly Herndon", title: "PROTO" },
  { artist: "Tirzah", title: "Devotion" },
  // Japanese Electronic
  { artist: "Susumu Yokota", title: "Sakura" },
  { artist: "Cornelius", title: "Fantasma" },
  { artist: "Midori Takada", title: "Through the Looking Glass" },
  // Minimal / Microhouse
  { artist: "Ricardo Villalobos", title: "Alcachofa" },
  { artist: "Actress", title: "R.I.P." },
  { artist: "Actress", title: "Ghettoville" },
  { artist: "Modeselektor", title: "Happy Birthday!" },
  { artist: "Moderat", title: "Moderat" },
  { artist: "Aphex Twin", title: "Syro" },
  { artist: "Plastikman", title: "Sheet One" },
  { artist: "Burial", title: "Kindred" },
  { artist: "Clark", title: "Clark" },
  { artist: "Machinedrum", title: "Vapor City" },
  { artist: "Daniel Avery", title: "Drone Logic" },
  { artist: "Lone", title: "Reality Testing" },
  { artist: "DJ Koze", title: "Knock Knock" },
  { artist: "Bicep", title: "Isles" },
  { artist: "Skee Mask", title: "Compro" },
  { artist: "Overmono", title: "Good Lies" },
  { artist: "Yves Tumor", title: "Heaven to a Tortured Mind" },
  { artist: "The Knife", title: "Silent Shout" },
  { artist: "Fever Ray", title: "Fever Ray" },
  { artist: "Röyksopp", title: "Melody A.M." },
  { artist: "Bonobo", title: "Black Sands" },
  { artist: "Mount Kimbie", title: "Crooks & Lovers" },
  { artist: "Darkside", title: "Psychic" },
  { artist: "Nils Frahm", title: "All Melody" },

  // --- Discovered via Last.fm ---
  { artist: "Imogen Heap", title: "Speak for Yourself" },
  { artist: "Crystal Castles", title: "(II)" },
  { artist: "Empire of the Sun", title: "Walking on a Dream" },
  { artist: "I Monster", title: "Neveroddoreven" },
  { artist: "Justice", title: "Cross" },
  { artist: "Calvin Harris", title: "I Created Disco" },
  { artist: "Daft Punk", title: "TRON: Legacy" },
  { artist: "The Knife", title: "Deep Cuts" },
  { artist: "Moby", title: "Everything Is Wrong" },
  { artist: "Pogo", title: "Wonderland" },
  { artist: "KMFDM", title: "Symbols" },
  { artist: "Passion Pit", title: "Manners" },
  { artist: "Infected Mushroom", title: "Vicious Delicious" },
  { artist: "Röyksopp", title: "Junior" },
  { artist: "Zedd", title: "True Colors" },
  { artist: "The Chemical Brothers", title: "Come With Us" },
  { artist: "The Chemical Brothers", title: "We Are the Night" },
  { artist: "IAMX", title: "Volatile Times" },
  { artist: "The Crystal Method", title: "Legion of Boom" },
  { artist: "The Weeknd", title: "House of Balloons (Original)" },
  { artist: "Tycho", title: "Dive" },
  { artist: "Little Dragon", title: "Machine Dreams" },
  { artist: "Air", title: "Pocket Symphony" },
  { artist: "Troye Sivan", title: "Blue Neighbourhood (Deluxe)" },
  { artist: "Underworld", title: "A Hundred Days Off" },
  { artist: "Coil", title: "The Ape of Naples" },
  { artist: "The Chemical Brothers", title: "Further" },
  { artist: "Goldfrapp", title: "Felt Mountain" },
  { artist: "Goldfrapp", title: "Black Cherry" },
  { artist: "múm", title: "Finally We Are No One" },
  { artist: "The Chemical Brothers", title: "Exit Planet Dust" },
  { artist: "Apollo 440", title: "Gettin' High on Your Own Supply" },
  { artist: "Sneaker Pimps", title: "Splinter" },
  { artist: "Yello", title: "Essential" },
  { artist: "Fluke", title: "Risotto" },
  { artist: "IAMX", title: "Kiss + Swallow" },
  { artist: "The Prodigy", title: "Experience" },
  { artist: "The Crystal Method", title: "Vegas" },
  { artist: "Underworld", title: "Oblivion With Bells" },
  { artist: "Benny Benassi", title: "Electroman" },
  { artist: "Autechre", title: "Quaristice" },
  { artist: "Infected Mushroom", title: "Army of Mushrooms" },
  { artist: "The Crystal Method", title: "Tweekend" },
  { artist: "Depeche Mode", title: "Sounds of the Universe" },
  { artist: "Atoms for Peace", title: "AMOK" },
  { artist: "Neon Indian", title: "Psychic Chasms" },
  { artist: "Infected Mushroom", title: "Converting Vegetarians" },
  { artist: "The Future Sound of London", title: "Dead Cities" },
  { artist: "Just Jack", title: "Overtones" },
  { artist: "Kylie Minogue", title: "Aphrodite" },
  { artist: "Fatboy Slim", title: "Palookaville" },
  { artist: "Does It Offend You, Yeah?", title: "You Have No Idea What You're Getting Yourself Into" },
  { artist: "Junior Senior", title: "D-D-Don't Don't Stop the Beat" },
  { artist: "Björk", title: "Vulnicura" },
  { artist: "Wax Tailor", title: "Tales of the Forgotten Melodies" },
  { artist: "Hot Chip", title: "The Warning" },
  { artist: "Toro y Moi", title: "Anything in Return" },
  { artist: "Carbon Based Lifeforms", title: "Interloper" },
  { artist: "Moloko", title: "Statues" },
  { artist: "Apollo 440", title: "Electro Glide in Blue" },
  { artist: "Nero", title: "Welcome Reality" },
  { artist: "Depeche Mode", title: "Ultra" },
  { artist: "HEALTH", title: "Death Magic" },
  { artist: "Ratatat", title: "Ratatat" },
  { artist: "Trentemøller", title: "The Last Resort" },
  { artist: "Orbital", title: "Orbital" },
  { artist: "Hooverphonic", title: "The Magnificent Tree" },
  { artist: "Boards of Canada", title: "Tomorrow's Harvest" },
  { artist: "Björk", title: "Medulla" },
  { artist: "Underworld", title: "Barking" },
  { artist: "Faithless", title: "Reverence" },
  { artist: "Brian Eno", title: "Before and After Science" },
  { artist: "James Blake", title: "The Colour in Anything" },
  { artist: "Ulver", title: "Perdition City" },
  { artist: "Capsule", title: "PLAYER" },
  { artist: "Mr.Kitty", title: "TIME" },
  { artist: "C418", title: "Minecraft - Volume Beta" },
  { artist: "Thom Yorke", title: "Tomorrow's Modern Boxes" },
  { artist: "Damon Albarn", title: "Everyday Robots" },
  { artist: "TWICE", title: "The Feels" },
  { artist: "Moloko", title: "Things to Make and Do" },
  { artist: "My Life with the Thrill Kill Kult", title: "Confessions Of A Knife" },
  { artist: "Underworld", title: "Barbara Barbara, We Face a Shining Future" },
  { artist: "Skinny Puppy", title: "Too Dark Park" },
  { artist: "Four Tet", title: "Pause" },
  { artist: "Moby", title: "Last Night" },
  { artist: "Hot Chip", title: "Made in the Dark" },
  { artist: "Fluke", title: "Puppy" },
  { artist: "Basement Jaxx", title: "Kish Kash" },
  { artist: "The Chemical Brothers", title: "Born in the Echoes" },
  { artist: "Suicide", title: "Suicide (2019 - Remaster)" },
  { artist: "Todd Terje", title: "It's Album Time" },
  { artist: "Madonna", title: "MDNA" },
  { artist: "Celldweller", title: "Celldweller" },
  { artist: "Mort Garson", title: "Mother Earth's Plantasia" },
  { artist: "Rob Dougan", title: "Furious Angels" },
  { artist: "Snail's house", title: "Ordinary Songs 2" },
  { artist: "Plaid", title: "Double Figure" },
  { artist: "Aphex Twin", title: "Digeridoo" },
  { artist: "Simian Mobile Disco", title: "Temporary Pleasure" },
  { artist: "COLTEMONIKHA", title: "COLTEMONIKHA 2" },
  { artist: "Coil", title: "Musick to Play in the Dark" },
  { artist: "Kelis", title: "Flesh Tone" },
  { artist: "t.A.T.u.", title: "Waste Management" },
  { artist: "Air", title: "10 000 Hz Legend" },
  { artist: "Empire of the Sun", title: "Ice on the Dune" },
  { artist: "The Presets", title: "Apocalypso" },
  { artist: "Archive", title: "Lights" },
  { artist: "Nightmares on Wax", title: "Carboot Soul" },
  { artist: "Deichkind", title: "Aufstand im Schlaraffenland" },
  { artist: "Archive", title: "Noise" },
  { artist: "Datarock", title: "Datarock Datarock" },
  { artist: "Orbital", title: "Blue Album" },
  { artist: "Vangelis", title: "Albedo 0.39" },
  { artist: "Portishead", title: "Roseland NYC Live" },
  { artist: "I-F", title: "Fucking Consumer" },
  { artist: "Scooter", title: "No Time to Chill" },
  { artist: "Fatboy Slim", title: "Better Living Through Chemistry" },
  { artist: "Cluster", title: "Zuckerzeit" },
  { artist: "Death Grips", title: "Fashion Week" },
  { artist: "Boards of Canada", title: "Hi Scores" },
  { artist: "Ascendant Vierge", title: "Vierge" },
  { artist: "Cascada", title: "Everytime We Touch" },
  { artist: "Groove Armada", title: "Black Light" },
  { artist: "Röyksopp", title: "Senior" },
  { artist: "Underworld", title: "Beaucoup Fish" },
  { artist: "pilotredsun", title: "Achievement" },
  { artist: "Slayyyter", title: "STARFUCKER" },
  { artist: "Groove Armada", title: "Lovebox" },
  { artist: "Machine Girl", title: "The Ugly Art" },
  { artist: "Lamb", title: "What Sound" },
  { artist: "Groove Armada", title: "Soundboy Rock" },
  { artist: "Lazerhawk", title: "Redline" },
  { artist: "Capsule", title: "MORE! MORE! MORE!" },
  { artist: "Carpenter Brut", title: "Trilogy" },
  { artist: "808 State", title: "Ninety" },
  { artist: "Midnight Juggernauts", title: "Dystopia" },
  { artist: "Emancipator", title: "Soon it Will be Cold Enough" },
  { artist: "Polygon Window", title: "Surfing on Sine Waves" },
  { artist: "deadmau5", title: "4x4=12" },
  { artist: "Ashra", title: "New Age of Earth" },
  { artist: "Infected Mushroom", title: "IM the Supervisor" },
  { artist: "Hadouken!", title: "For the Masses" },
  { artist: "Holy Fuck", title: "LP" },
  { artist: "Moby", title: "Destroyed" },
  { artist: "Ayria", title: "Hearts for Bullets" },
  { artist: "Infected Mushroom", title: "Classical Mushroom" },
  { artist: "Knife Party", title: "Rage Valley" },
  { artist: "Stereo Total", title: "Musique Automatique" },
  { artist: "The xx", title: "I See You" },
  { artist: "Tycho", title: "Awake" },
  { artist: "Autechre", title: "Garbage" },
  { artist: "James Blake", title: "Overgrown" },
  { artist: "Bondage Fairies", title: "What You Didn't Know When You Hired Me" },
  { artist: "Squarepusher", title: "Hello Everything" },
  { artist: "Sophie Ellis-Bextor", title: "Trip the Light Fantastic" },
  { artist: "Squarepusher", title: "Ultravisitor" },
  { artist: "Air", title: "Le Voyage dans la Lune" },
  { artist: "Pet Shop Boys", title: "Very" },
  { artist: "Christina Aguilera", title: "Bionic" },
  { artist: "Lali Puna", title: "Scary World Theory" },
  { artist: "Fuck Buttons", title: "Tarot Sport" },
  { artist: "Coil", title: "Black Antlers" },
  { artist: "LCD Soundsystem", title: "45:33" },
  { artist: "Crystal Castles", title: "Celestica" },
  { artist: "Four Tet", title: "Pink" },
  { artist: "Knife Party", title: "Abandon Ship" },
  { artist: "MSTRKRFT", title: "The Looks" },
  { artist: "Baths", title: "Obsidian" },
  { artist: "Apparat", title: "The Devil's Walk" },
  { artist: "Björk", title: "Biophilia" },
  { artist: "Air", title: "Love 2" },
  { artist: "Primal Scream", title: "XTRMNTR" },
  { artist: "Xploding Plastix", title: "Amateur Girlfriends Go Proskirt Agents" },
  { artist: "Autechre", title: "Oversteps" },
  { artist: "Com Truise", title: "Galactic Melt" },
  { artist: "Venetian Snares", title: "Rossz csillag alatt született" },
  { artist: "Radiohead", title: "TKOL RMX 1234567" },
  { artist: "PNAU", title: "PNAU" },
  { artist: "The Chemical Brothers", title: "Brotherhood" },
  { artist: "Mr. Oizo", title: "Analog Worms Attack" },
  { artist: "The Future Sound of London", title: "Lifeforms" },
  { artist: "Sophie Ellis-Bextor", title: "Shoot from the Hip" },
  { artist: "Eartheater", title: "Trinity" },
  { artist: "t.A.T.u.", title: "Happy Smiles" },
  { artist: "David Bowie", title: "Earthling" },
  { artist: "Kraftwerk", title: "Die Mensch-Maschine" },
  { artist: "Hadouken!", title: "Music for an Accelerated Culture" },
  { artist: "Soulwax", title: "Any Minute Now" },
  { artist: "The Cinematic Orchestra", title: "Motion" },
  { artist: "The Orb", title: "Adventures Beyond the Ultraworld" },
  { artist: "Amon Tobin", title: "Bricolage" },
  { artist: "Mylo", title: "Destroy Rock & Roll" },
  { artist: "Kraftwerk", title: "Trans Europa Express" },
  { artist: "Ellie Goulding", title: "Halcyon Days" },
  { artist: "I See Stars", title: "New Demons" },
  { artist: "Polarkreis 18", title: "The Colour Of Snow" },
  { artist: "Moloko", title: "I Am Not a Doctor" },
  { artist: "Koop", title: "Waltz for Koop" },
  { artist: "Infected Mushroom", title: "The Gathering" },
  { artist: "Toro y Moi", title: "What For?" },
  { artist: "iamamiwhoami", title: "kin" },
  { artist: "Skrillex", title: "More Monsters and Sprites" },
  { artist: "KMFDM", title: "Money" },
  { artist: "Kim Petras", title: "TURN OFF THE LIGHT" },
  { artist: "Blue Stahli", title: "Blue Stahli" },
  { artist: "The KLF", title: "The White Room" },
  { artist: "The Knife", title: "The Knife" },
  { artist: "Zero 7", title: "The Garden" },
  { artist: "Crown the Empire", title: "The Resistance: Rise of the Runaways" },
  { artist: "Holy Fuck", title: "Congrats" },
  { artist: "Nine Inch Nails", title: "Hesitation Marks" },
  { artist: "Tobacco", title: "Fucked Up Friends" },
  { artist: "Perfume", title: "⊿" },
  { artist: "Blockhead", title: "Music By Cavelight" },
  { artist: "múm", title: "Summer Make Good" },
  { artist: "Perfume", title: "GAME" },
  { artist: "Sam Sparro", title: "Black & Gold" },
  { artist: "Unheilig", title: "Grosse Freiheit" },
  { artist: "Sevdaliza", title: "The Suspended Kid" },
  { artist: "The Ting Tings", title: "Sounds From Nowheresville" },
  { artist: "King Gizzard & The Lizard Wizard", title: "The Silver Cord" },
  { artist: "Bonobo", title: "Dial 'M' for Monkey" },
  { artist: "Arca", title: "Mutant" },
  { artist: "The Buggles", title: "The Age of Plastic" },
  { artist: "Faithless", title: "No Roots" },
  { artist: "Audio Bullys", title: "Ego War" },
  { artist: "Bonobo", title: "Animal Magic" },
  { artist: "Frank Zappa", title: "Jazz From Hell" },
  { artist: "Peace Orchestra", title: "Peace Orchestra" },
  { artist: "Extrawelt", title: "In Aufruhr" },
  { artist: "Los Prisioneros", title: "Corazones" },
  { artist: "Gotye", title: "Like Drawing Blood" },
  { artist: "Justice", title: "Woman" },
  { artist: "She", title: "coloris" },
  { artist: "Vatican Shadow", title: "Remember Your Black Day" },
  { artist: "Schiller", title: "Weltreise" },
  { artist: "Depeche Mode", title: "Construction Time Again" },
  { artist: "ESPRIT 空想", title: "virtua.zip" },
  { artist: "Yelle", title: "Pop-up" },
  { artist: "EMF", title: "Schubert Dip" },
  { artist: "Depeche Mode", title: "Some Great Reward" },
  { artist: "Orbital", title: "The Altogether" },
  { artist: "Paul Kalkbrenner", title: "7" },
  { artist: "Blue States", title: "Man Mountain" },
  { artist: "Thievery Corporation", title: "The Mirror Conspiracy" },
  { artist: "White Noise", title: "An Electric Storm" },
  { artist: "Tinashe", title: "BB/ANG3L" },
  { artist: "To Rococo Rot", title: "The Amateur View" },
  { artist: "Kraftwerk", title: "The Man Machine" },
];
