export const folkCountry: Array<{ artist: string; title: string }> = [
  // Traditional Folk / 60s Folk Revival
  { artist: "Bob Dylan", title: "Highway 61 Revisited" },
  { artist: "Bob Dylan", title: "Blonde on Blonde" },
  { artist: "Bob Dylan", title: "The Freewheelin' Bob Dylan" },
  { artist: "Bob Dylan", title: "Bringing It All Back Home" },
  { artist: "Bob Dylan", title: "Blood on the Tracks" },
  { artist: "Bob Dylan", title: "The Basement Tapes" },
  { artist: "Bob Dylan", title: "John Wesley Harding" },
  { artist: "Woody Guthrie", title: "Dust Bowl Ballads" },
  { artist: "Pete Seeger", title: "We Shall Overcome" },
  { artist: "Joan Baez", title: "Joan Baez" },
  { artist: "Joan Baez", title: "Diamonds & Rust" },
  { artist: "Joni Mitchell", title: "Blue" },
  { artist: "Joni Mitchell", title: "Hejira" },
  { artist: "Joni Mitchell", title: "For the Roses" },
  { artist: "Leonard Cohen", title: "Songs of Leonard Cohen" },
  { artist: "Leonard Cohen", title: "Songs of Love and Hate" },
  { artist: "Leonard Cohen", title: "I'm Your Man" },
  { artist: "Leonard Cohen", title: "You Want It Darker" },
  { artist: "Nick Drake", title: "Pink Moon" },
  { artist: "Nick Drake", title: "Five Leaves Left" },
  { artist: "Nick Drake", title: "Bryter Layter" },
  { artist: "Tim Buckley", title: "Happy Sad" },
  { artist: "Tim Buckley", title: "Starsailor" },
  { artist: "Fairport Convention", title: "Liege & Lief" },
  { artist: "Pentangle", title: "Basket of Light" },
  { artist: "Sandy Denny", title: "The North Star Grassman and the Ravens" },
  { artist: "Bert Jansch", title: "Bert Jansch" },
  { artist: "John Martyn", title: "Solid Air" },
  { artist: "Richard Thompson", title: "Shoot Out the Lights" },
  { artist: "Vashti Bunyan", title: "Just Another Diamond Day" },
  { artist: "Donovan", title: "Sunshine Superman" },
  { artist: "Simon & Garfunkel", title: "Parsley, Sage, Rosemary and Thyme" },
  { artist: "Phil Ochs", title: "I Ain't Marching Anymore" },
  { artist: "Cat Stevens", title: "Tea for the Tillerman" },
  { artist: "James Taylor", title: "Sweet Baby James" },
  // Classic Country
  { artist: "Hank Williams", title: "40 Greatest Hits" },
  { artist: "Johnny Cash", title: "At Folsom Prison" },
  { artist: "Johnny Cash", title: "American IV: The Man Comes Around" },
  { artist: "Johnny Cash", title: "At San Quentin" },
  { artist: "Patsy Cline", title: "Patsy Cline's Greatest Hits" },
  { artist: "Willie Nelson", title: "Red Headed Stranger" },
  { artist: "Willie Nelson", title: "Stardust" },
  { artist: "Waylon Jennings", title: "Honky Tonk Heroes" },
  { artist: "Merle Haggard", title: "Mama Tried" },
  { artist: "Merle Haggard", title: "Sing Me Back Home" },
  { artist: "George Jones", title: "I Am What I Am" },
  { artist: "Tammy Wynette", title: "Stand by Your Man" },
  { artist: "Loretta Lynn", title: "Coal Miner's Daughter" },
  { artist: "Dolly Parton", title: "Coat of Many Colors" },
  { artist: "Dolly Parton", title: "Jolene" },
  { artist: "Gram Parsons", title: "Grievous Angel" },
  { artist: "Gram Parsons", title: "GP" },
  { artist: "Townes Van Zandt", title: "Townes Van Zandt" },
  { artist: "Townes Van Zandt", title: "Live at the Old Quarter, Houston, Texas" },
  { artist: "Guy Clark", title: "Old No. 1" },
  { artist: "Emmylou Harris", title: "Wrecking Ball" },
  { artist: "Emmylou Harris", title: "Pieces of the Sky" },
  // Bluegrass
  { artist: "Bill Monroe", title: "The Essential Bill Monroe and His Blue Grass Boys" },
  { artist: "Flatt & Scruggs", title: "Foggy Mountain Banjo" },
  { artist: "The Stanley Brothers", title: "The Complete Columbia Stanley Brothers" },
  { artist: "Alison Krauss", title: "Now That I've Found You: A Collection" },
  { artist: "Nickel Creek", title: "Nickel Creek" },
  { artist: "Chris Thile", title: "Bach: Sonatas and Partitas, Vol. 1" },
  // Blues
  { artist: "Robert Johnson", title: "King of the Delta Blues Singers" },
  { artist: "Muddy Waters", title: "The Anthology: 1947-1972" },
  { artist: "Howlin' Wolf", title: "Moanin' in the Moonlight" },
  { artist: "B.B. King", title: "Live at the Regal" },
  { artist: "John Lee Hooker", title: "The Healer" },
  { artist: "Son House", title: "Father of Folk Blues" },
  { artist: "Skip James", title: "Today!" },
  { artist: "Mississippi John Hurt", title: "Today!" },
  { artist: "Lightnin' Hopkins", title: "Mojo Hand" },
  { artist: "Elmore James", title: "The Sky Is Crying" },
  { artist: "T-Bone Walker", title: "T-Bone Blues" },
  { artist: "Albert King", title: "Born Under a Bad Sign" },
  { artist: "Freddie King", title: "Let's Hide Away and Dance Away" },
  { artist: "Etta James", title: "At Last!" },
  // Alt-Country / Americana
  { artist: "Uncle Tupelo", title: "No Depression" },
  { artist: "Wilco", title: "Yankee Hotel Foxtrot" },
  { artist: "Wilco", title: "A Ghost Is Born" },
  { artist: "Ryan Adams", title: "Heartbreaker" },
  { artist: "Lucinda Williams", title: "Car Wheels on a Gravel Road" },
  { artist: "Steve Earle", title: "Guitar Town" },
  { artist: "Drive-By Truckers", title: "Southern Rock Opera" },
  { artist: "Gillian Welch", title: "Revival" },
  { artist: "Gillian Welch", title: "Time (The Revelator)" },
  { artist: "Old Crow Medicine Show", title: "O.C.M.S." },
  { artist: "Jason Isbell", title: "Southeastern" },
  { artist: "Jason Isbell and the 400 Unit", title: "The Nashville Sound" },
  { artist: "Sturgill Simpson", title: "Metamodern Sounds in Country Music" },
  { artist: "Sturgill Simpson", title: "A Sailor's Guide to Earth" },
  { artist: "Tyler Childers", title: "Purgatory" },
  { artist: "Colter Wall", title: "Songs of the Plains" },
  { artist: "Chris Stapleton", title: "Traveller" },
  { artist: "Margo Price", title: "Midwest Farmer's Daughter" },
  { artist: "Sierra Ferrell", title: "Long Time Coming" },
  { artist: "Waxahatchee", title: "Saint Cloud" },
  { artist: "Kacey Musgraves", title: "Golden Hour" },
  { artist: "Brandi Carlile", title: "By the Way, I Forgive You" },
  { artist: "The Avett Brothers", title: "I and Love and You" },
  // Contemporary Folk
  { artist: "Iron & Wine", title: "Our Endless Numbered Days" },
  { artist: "Iron & Wine", title: "The Creek Drank the Cradle" },
  { artist: "Fleet Foxes", title: "Fleet Foxes" },
  { artist: "Fleet Foxes", title: "Helplessness Blues" },
  { artist: "Bon Iver", title: "For Emma, Forever Ago" },
  { artist: "Sufjan Stevens", title: "Carrie & Lowell" },
  { artist: "The Tallest Man on Earth", title: "The Wild Hunt" },
  { artist: "Laura Marling", title: "Once I Was an Eagle" },
  { artist: "Big Thief", title: "U.F.O.F." },
  { artist: "Adrianne Lenker", title: "songs" },
  { artist: "Phoebe Bridgers", title: "Punisher" },
  { artist: "Andy Shauf", title: "The Neon Skyline" },
  // World / International Folk
  { artist: "Buena Vista Social Club", title: "Buena Vista Social Club" },
  { artist: "Ali Farka Touré", title: "Talking Timbuktu" },
  { artist: "Tinariwen", title: "Amassakoul" },
  { artist: "Ravi Shankar", title: "Three Ragas" },
  { artist: "Caetano Veloso", title: "Transa" },
  { artist: "Gilberto Gil", title: "Refazenda" },
  { artist: "Os Mutantes", title: "Os Mutantes" },
  { artist: "Tropicália", title: "Tropicália: ou Panis et Circensis" },
  { artist: "Mercedes Sosa", title: "30 Años" },
  { artist: "Víctor Jara", title: "Te Recuerdo Amanda" },
  { artist: "Nusrat Fateh Ali Khan", title: "Mustt Mustt" },
  { artist: "Tinariwen", title: "Emmaar" },
  { artist: "Bombino", title: "Nomad" },
  { artist: "Mdou Moctar", title: "Afrique Victime" },
  { artist: "Khruangbin", title: "Con Todo El Mundo" },
  { artist: "John Prine", title: "John Prine" },
  { artist: "John Prine", title: "The Tree of Forgiveness" },
  { artist: "Iris DeMent", title: "Infamous Angel" },
  { artist: "Neko Case", title: "Fox Confessor Brings the Flood" },
  { artist: "The Handsome Family", title: "Singing Bones" },
  { artist: "Bonnie 'Prince' Billy", title: "I See a Darkness" },
  { artist: "Bill Callahan", title: "Sometimes I Wish We Were an Eagle" },
  { artist: "Sun Kil Moon", title: "Ghosts of the Great Highway" },
  { artist: "Richard Dawson", title: "Peasant" },
  { artist: "Jessica Pratt", title: "Quiet Signs" },
  { artist: "Joanna Newsom", title: "Ys" },
  { artist: "Joanna Newsom", title: "Have One on Me" },
  { artist: "Angel Olsen", title: "My Woman" },
  { artist: "Aldous Harding", title: "Designer" },
  { artist: "Weyes Blood", title: "Titanic Rising" },
  { artist: "Faye Webster", title: "I Know I'm Funny haha" },
  { artist: "Charley Crockett", title: "The Man from Waco" },
  { artist: "Zach Bryan", title: "American Heartbreak" },
  { artist: "Billy Strings", title: "Renewal" },
  { artist: "Amália Rodrigues", title: "The Art of Amália" },
  { artist: "Oumou Sangaré", title: "Worotan" },
  { artist: "Youssou N'Dour", title: "The Guide (Wommat)" },
  { artist: "Rokia Traoré", title: "Bowmboï" },

  // --- Discovered via Last.fm ---
  { artist: "Tracy Chapman", title: "Tracy Chapman" },
  { artist: "Edward Sharpe & The Magnetic Zeros", title: "Up From Below" },
  { artist: "Bon Iver", title: "Blood Bank" },
  { artist: "Angus & Julia Stone", title: "Down the Way" },
  { artist: "Ben Howard", title: "Every Kingdom" },
  { artist: "Iron & Wine", title: "The Shepherd's Dog" },
  { artist: "Bob Dylan", title: "Another Side of Bob Dylan" },
  { artist: "Joni Mitchell", title: "Ladies of the Canyon" },
  { artist: "Paul Simon", title: "Paul Simon" },
  { artist: "Damien Rice", title: "O" },
  { artist: "Joni Mitchell", title: "Clouds" },
  { artist: "Great Lake Swimmers", title: "Ongiara" },
  { artist: "Simon & Garfunkel", title: "Wednesday Morning, 3 A.M." },
  { artist: "Beirut", title: "The Flying Club Cup" },
  { artist: "Lana Del Rey", title: "Chemtrails Over the Country Club" },
  { artist: "Woody Guthrie", title: "This Land Is Your Land: The Asch Recordings, Vol. 1" },
  { artist: "Laura Marling", title: "I Speak Because I Can" },
  { artist: "Damien Rice", title: "9" },
  { artist: "Vashti Bunyan", title: "Lookaftering" },
  { artist: "Karen Dalton", title: "In My Own Time" },
  { artist: "Laura Marling", title: "Alas I Cannot Swim" },
  { artist: "Alexi Murdoch", title: "Time Without Consequence" },
  { artist: "The Weepies", title: "Say I Am You" },
  { artist: "Leonard Cohen", title: "Death Of A Ladies' Man" },
  { artist: "Keaton Henson", title: "Dear" },
  { artist: "Devendra Banhart", title: "Cripple Crow" },
  { artist: "Adrianne Lenker", title: "Hours Were The Birds" },
  { artist: "Gordon Lightfoot", title: "Gord's Gold" },
  { artist: "Ray LaMontagne", title: "Till the Sun Turns Black" },
  { artist: "Joanna Newsom", title: "The Milk-Eyed Mender" },
  { artist: "Lucy Rose", title: "Like I Used To" },
  { artist: "Buffy Sainte-Marie", title: "Illuminations" },
  { artist: "Eluveitie", title: "Evocation I - The Arcane Dominion" },
  { artist: "Gordon Lightfoot", title: "If You Could Read My Mind" },
  { artist: "Richard & Linda Thompson", title: "I Want To See The Bright Lights Tonight" },
  { artist: "The Civil Wars", title: "Barton Hollow" },
  { artist: "Norma Tanega", title: "Walkin' My Cat Named Dog" },
  { artist: "Fionn Regan", title: "The End Of History" },
  { artist: "Van Morrison", title: "Astral Weeks" },
  { artist: "Mumford & Sons", title: "Babel" },
  { artist: "Mariee Sioux", title: "Faces In The Rocks" },
  { artist: "Townes Van Zandt", title: "Rear View Mirror" },
  { artist: "Vetiver", title: "Tight Knit" },
  { artist: "Shawn Colvin", title: "A Few Small Repairs" },
  { artist: "Moriarty", title: "Gee whiz but this is a lonesome town" },
  { artist: "Johnny Cash", title: "American III: Solitary Man" },
  { artist: "Johnny Flynn", title: "A Larum" },
  { artist: "Animal Collective", title: "Sung Tongs" },
  { artist: "Nick Drake", title: "Made To Love Magic" },
  { artist: "Ben Harper", title: "Welcome To The Cruel World" },
  { artist: "Daniel Johnston", title: "Hi How Are You" },
  { artist: "Blackmore's Night", title: "Under a Violet Moon" },
  { artist: "Odetta", title: "Odetta Sings Dylan" },
  { artist: "Amos Lee", title: "Supply and Demand" },
  { artist: "First Aid Kit", title: "Stay Gold" },
  { artist: "Loreena McKennitt", title: "The Visit" },
  { artist: "Deer Tick", title: "War Elephant" },
  { artist: "Monsters of Folk", title: "Monsters of Folk" },
  { artist: "Steam Powered Giraffe", title: "The 2¢ Show" },
  { artist: "Мельница", title: "Дорога сна" },
  { artist: "Sandy", title: "Manuscrito" },
  { artist: "Elizabeth Cotten", title: "Freight Train And Other North Carolina Folk Songs And Tunes" },
  { artist: "Townes Van Zandt", title: "Our Mother the Mountain" },
  { artist: "Connie Converse", title: "How Sad, How Lovely" },
  { artist: "Laura Veirs", title: "July Flame" },
  { artist: "Мельница", title: "Перевал" },
  { artist: "The Microphones", title: "The Glow Pt. 2" },
  { artist: "Myrkur", title: "Folkesange" },
  { artist: "Laura Marling", title: "A Creature I Don't Know" },
  { artist: "Alela Diane", title: "The Pirate's Gospel" },
  { artist: "Bright Eyes", title: "I'm Wide Awake, It's Morning" },
  { artist: "Loreena McKennitt", title: "The Book of Secrets" },
  { artist: "The Incredible String Band", title: "The 5000 Spirits or the Layers of the Onion" },
  { artist: "Sun Kil Moon", title: "Benji" },
  { artist: "Sharon Van Etten", title: "Epic" },
  { artist: "Tim Buckley", title: "Lorca" },
  { artist: "Мельница", title: "Зов Крови" },
  { artist: "Joshua Radin", title: "We Were Here" },
  { artist: "Alela Diane", title: "To Be Still" },
  { artist: "Angus & Julia Stone", title: "A Book Like This" },
  { artist: "Faun", title: "Licht" },
  { artist: "Tracy Chapman", title: "Our Bright Future" },
  { artist: "The Tallest Man on Earth", title: "Shallow Grave" },
  { artist: "Agnes Obel", title: "Aventine" },
  { artist: "Mallu Magalhães", title: "Pitanga" },
  { artist: "Devendra Banhart", title: "What Will We Be" },
  { artist: "Eddie Vedder", title: "Ukulele Songs" },
  { artist: "Joan Baez", title: "5" },
  { artist: "Kate & Anna McGarrigle", title: "Kate & Anna McGarrigle" },
  { artist: "Wardruna", title: "Runaljod - Ragnarok" },
  { artist: "Jewel", title: "This Way" },
  { artist: "Fink", title: "Perfect Darkness" },
  { artist: "Priscilla Ahn", title: "A Good Day" },
  { artist: "Vetiver", title: "To Find Me Gone" },
  { artist: "Tracy Chapman", title: "Matters of the Heart" },
  { artist: "James Vincent McMorrow", title: "Early in the Morning" },
  { artist: "The Brian Jonestown Massacre", title: "Thank God for Mental Illness" },
  { artist: "Wardruna", title: "Runaljod - gap var Ginnunga" },
  { artist: "Joe Purdy", title: "Julie Blue" },
  { artist: "Benjamin Francis Leftwich", title: "Last Smoke Before The Snowstorm" },
  { artist: "Manu Chao", title: "Próxima Estación: Esperanza" },
  { artist: "Karel Kryl", title: "Bratříčku, zavírej vrátka" },
  { artist: "Trees", title: "On the Shore" },
  { artist: "The Staves", title: "Dead & Born & Grown" },
  { artist: "Tracy Chapman", title: "Crossroads" },
  { artist: "Alexi Murdoch", title: "Four Songs" },
  { artist: "Jackson C. Frank", title: "Jackson C. Frank" },
  { artist: "The Incredible String Band", title: "The Hangman's Beautiful Daughter" },
  { artist: "Laura Marling", title: "Short Movie" },
  { artist: "The Weepies", title: "Hideaway" },
  { artist: "Jack Rose", title: "Kensington Blues" },
  { artist: "Lord Huron", title: "Lonesome Dreams" },
  { artist: "Planxty", title: "Planxty" },
  { artist: "Julien Baker", title: "Sprained Ankle" },
  { artist: "Ani DiFranco", title: "Little Plastic Castle" },
  { artist: "Frank Turner", title: "Love Ire & Song" },
  { artist: "Ani DiFranco", title: "Not a Pretty Girl" },
  { artist: "Mount Eerie", title: "Night Palace" },
  { artist: "Joni Mitchell", title: "Song to a Seagull" },
  { artist: "Midlake", title: "The Trials Of Van Occupanther" },
  { artist: "Horse Feathers", title: "Words Are Dead" },
  { artist: "Heilung", title: "Ofnir" },
  { artist: "The Strumbellas", title: "Hope" },
  { artist: "Мельница", title: "Дикие травы" },
  { artist: "Bill Fay", title: "Time Of The Last Persecution" },
  { artist: "Joe Pug", title: "Nation of Heat EP" },
  { artist: "Brett Dennen", title: "So Much More" },
  { artist: "M. Ward", title: "Transfiguration of Vincent" },
  { artist: "Daughter", title: "His Young Heart" },
  { artist: "Phil Ochs", title: "Pleasures Of The Harbor" },
  { artist: "Andrew Belle", title: "The Ladder" },
  { artist: "Andrew Bird", title: "My Finest Work Yet" },
  { artist: "Laura Marling", title: "Song For Our Daughter" },
  { artist: "Bill Callahan", title: "Dream River" },
  { artist: "The Be Good Tanyas", title: "Chinatown" },
  { artist: "Mount Eerie", title: "A Crow Looked At Me" },
  { artist: "The Felice Brothers", title: "The Felice Brothers" },
  { artist: "Fairport Convention", title: "Liege And Lief" },
  { artist: "Gregory Alan Isakov", title: "That Sea, The Gambler" },
  { artist: "Mount Eerie", title: "Clear Moon" },
  { artist: "Nick Drake", title: "Time of No Reply" },
  { artist: "Mark Fry", title: "Dreaming With Alice" },
  { artist: "Evan Dando", title: "Baby I'm Bored" },
  { artist: "Marissa Nadler", title: "Ballads of Living and Dying" },
  { artist: "Josh Ritter", title: "The Historical Conquests of Josh Ritter" },
  { artist: "Akron/Family", title: "Akron/Family" },
  { artist: "The Tallest Man on Earth", title: "Sometimes the Blues Is Just a Passing Bird" },
  { artist: "Espers", title: "The Weed Tree" },
  { artist: "The Lumineers", title: "BRIGHTSIDE" },
  { artist: "Devendra Banhart", title: "Smokey Rolls Down Thunder Canyon" },
  { artist: "Chelsea Wolfe", title: "Birth of Violence" },
  { artist: "Judee Sill", title: "Heart Food" },
  { artist: "Loreena McKennitt", title: "The Mask and Mirror" },
  { artist: "Drudkh", title: "Songs of Grief and Solitude" },
  { artist: "Devendra Banhart", title: "Rejoicing in the Hands" },
  { artist: "Hozier", title: "Unreal Unearth: Unaired" },
  { artist: "Noah and the Whale", title: "The First Days Of Spring" },
  { artist: "Vetiver", title: "Vetiver" },
  { artist: "The Mountain Goats", title: "All Hail West Texas" },
  { artist: "Loreena McKennitt", title: "Elemental" },
  { artist: "Vashti Bunyan", title: "Heartleap" },
  { artist: "Steam Powered Giraffe", title: "MK III" },
  { artist: "Tim Buckley", title: "Tim Buckley" },
  { artist: "Eluveitie", title: "Evocation I: The Arcane Dominion" },
  { artist: "Giles Corey", title: "Giles Corey" },
  { artist: "Iron & Wine", title: "Kiss Each Other Clean" },
  { artist: "Paul Simon", title: "The Paul Simon Songbook" },
  { artist: "Fleet Foxes", title: "Crack-Up" },
  { artist: "Donovan", title: "What's Bin Did And What's Bin Hid" },
  { artist: "Dar Williams", title: "End of the Summer" },
  { artist: "John Prine", title: "Sweet Revenge" },
  { artist: "Laura Marling", title: "Semper Femina" },
  { artist: "Bob Dylan", title: "World Gone Wrong" },
  { artist: "Ingrid Michaelson", title: "Be OK" },
  { artist: "The Pogues", title: "Rum Sodomy & the Lash" },
  { artist: "Ichiko Aoba", title: "Luminescent Creatures" },
  { artist: "Loreena McKennitt", title: "The Wind That Shakes The Barley" },
  { artist: "Wardruna", title: "Skald" },
  { artist: "Leighton Meester", title: "Heartstrings" },
  { artist: "Frank Turner", title: "England Keep My Bones" },
  { artist: "John Renbourn", title: "The Lady And The Unicorn" },
  { artist: "Johnny Cash", title: "American Recordings" },
  { artist: "Crooked Still", title: "Shaken by a Low Sound" },
  { artist: "Dan Mangan", title: "Nice, Nice, Very Nice" },
  { artist: "mewithoutYou", title: "It's All Crazy! It's All False! It's All A Dream! It's Alright" },
  { artist: "Phil Ochs", title: "There But For Fortune" },
  { artist: "Vàli", title: "Forlatt" },
  { artist: "Timber Timbre", title: "Timber Timbre" },
  { artist: "Rodriguez", title: "Coming From Reality" },
  { artist: "Great Lake Swimmers", title: "Bodies And Minds" },
  { artist: "Marissa Nadler", title: "The Saga of Mayflower May" },
  { artist: "Woods", title: "City Sun Eater In The River Of Light" },
  { artist: "Birdy", title: "Birdy (Deluxe Version)" },
  { artist: "Aldous Harding", title: "Aldous Harding" },
  { artist: "John Fahey", title: "The Transfiguration Of Blind Joe Death" },
  { artist: "Nick Drake", title: "The Making Of Five Leaves Left" },
  { artist: "You+Me", title: "rose ave." },
  { artist: "Aldous Harding", title: "Party" },
  { artist: "Mallu Magalhães", title: "Mallu Magalhães" },
  { artist: "Bob Dylan", title: "New Morning" },
  { artist: "Matt Costa", title: "Songs We Sing" },
  { artist: "Lissie", title: "Catching A Tiger" },
  { artist: "Clannad", title: "Fuaim" },
  { artist: "In Gowan Ring", title: "Hazel Steps through a Weathered Home" },
  { artist: "City and Colour", title: "The Hurry And The Harm" },
  { artist: "Arlo Guthrie", title: "Alice's Restaurant" },
  { artist: "Brandi Carlile", title: "The Story" },
  { artist: "Joshua Radin", title: "Simple Times" },
  { artist: "Bowerbirds", title: "Upper Air" },
  { artist: "Nicolette Larson", title: "Nicolette" },
  { artist: "Julia Jacklin", title: "Don't Let The Kids Win" },
  { artist: "Newton Faulkner", title: "Rebuilt By Humans" },
  { artist: "Bowerbirds", title: "Hymns for a Dark Horse" },
  { artist: "Cat Stevens", title: "Mona Bone Jakon" },
  { artist: "Vic Chesnutt", title: "North Star Deserter" },
  { artist: "William Fitzsimmons", title: "Gold in the Shadow" },
  { artist: "Espers", title: "Espers" },
  { artist: "Jason Webley", title: "Against the Night" },
  { artist: "My Morning Jacket", title: "The Tennessee Fire" },
  { artist: "Neil Young", title: "Silver & Gold" },
  { artist: "A.A. Bondy", title: "American Hearts" },
  { artist: "Sun Kil Moon", title: "April" },
  { artist: "Richard Thompson", title: "Sweet Warrior" },
  { artist: "Xavier Rudd", title: "Spirit Bird" },
  { artist: "Richard & Linda Thompson", title: "Shoot Out the Lights" },
  { artist: "Lisa Hannigan", title: "Passenger" },
  { artist: "George Ezra", title: "Staying at Tamara's" },
  { artist: "Yellow House", title: "A Carnival of Fears" },
  { artist: "Natalia Lafourcade", title: "Musas (Un Homenaje al Folclore Latinoamericano en Manos de Los Macorinos), Vol. 2" },
  { artist: "Vàli", title: "Skogslandskap" },
  { artist: "Cowboy Junkies", title: "Lay It Down" },
  { artist: "Anavitória", title: "claraboia" },
  { artist: "The Corrs", title: "Home" },
  { artist: "Mountain Man", title: "Made The Harbor" },
  { artist: "Nanci Griffith", title: "Other Voices, Other Rooms" },
  { artist: "James Taylor", title: "James Taylor" },
  { artist: "Micah P. Hinson", title: "Micah P. Hinson and the Gospel of Progress" },
  { artist: "Angel Olsen", title: "Big Time" },
  { artist: "Novo Amor", title: "Birthplace" },
  { artist: "Bob Dylan", title: "Good as I Been to You" },
  { artist: "Six Organs of Admittance", title: "Dark Noontide" },
  { artist: "dodie", title: "You - EP" },
  { artist: "The Avett Brothers", title: "Mignonette" },
  { artist: "Volcano Choir", title: "Unmap" },
  { artist: "Old Crow Medicine Show", title: "Big Iron World" },
  { artist: "Sabrina Carpenter", title: "Eyes Wide Open" },
  { artist: "Frank Turner", title: "Sleep Is For the Week" },
  { artist: "Neil Young", title: "Prairie Wind" },
  { artist: "Lambchop", title: "OH (Ohio)" },
  { artist: "Rebecca Pidgeon", title: "The Raven" },
];
