export const hipHop: Array<{ artist: string; title: string }> = [
  // Old School / Golden Age
  { artist: "Grandmaster Flash & The Furious Five", title: "The Message" },
  { artist: "Run-D.M.C.", title: "Raising Hell" },
  { artist: "Beastie Boys", title: "Paul's Boutique" },
  { artist: "Beastie Boys", title: "Licensed to Ill" },
  { artist: "Public Enemy", title: "It Takes a Nation of Millions to Hold Us Back" },
  { artist: "Public Enemy", title: "Fear of a Black Planet" },
  { artist: "Eric B. & Rakim", title: "Paid in Full" },
  { artist: "N.W.A", title: "Straight Outta Compton" },
  { artist: "De La Soul", title: "3 Feet High and Rising" },
  { artist: "A Tribe Called Quest", title: "The Low End Theory" },
  { artist: "A Tribe Called Quest", title: "Midnight Marauders" },
  { artist: "Gang Starr", title: "Moment of Truth" },
  { artist: "KRS-One", title: "Return of the Boom Bap" },
  { artist: "Big Daddy Kane", title: "Long Live the Kane" },
  { artist: "Boogie Down Productions", title: "Criminal Minded" },
  // East Coast
  { artist: "Nas", title: "Illmatic" },
  { artist: "Nas", title: "It Was Written" },
  { artist: "The Notorious B.I.G.", title: "Ready to Die" },
  { artist: "The Notorious B.I.G.", title: "Life After Death" },
  { artist: "Wu-Tang Clan", title: "Enter the Wu-Tang (36 Chambers)" },
  { artist: "Raekwon", title: "Only Built 4 Cuban Linx..." },
  { artist: "GZA", title: "Liquid Swords" },
  { artist: "Ghostface Killah", title: "Supreme Clientele" },
  { artist: "Mobb Deep", title: "The Infamous" },
  { artist: "Jay-Z", title: "Reasonable Doubt" },
  { artist: "Jay-Z", title: "The Blueprint" },
  { artist: "Jay-Z", title: "The Black Album" },
  { artist: "Jay-Z", title: "4:44" },
  { artist: "DMX", title: "It's Dark and Hell Is Hot" },
  { artist: "Busta Rhymes", title: "When Disaster Strikes..." },
  // West Coast
  { artist: "Dr. Dre", title: "The Chronic" },
  { artist: "Dr. Dre", title: "2001" },
  { artist: "Snoop Dogg", title: "Doggystyle" },
  { artist: "2Pac", title: "All Eyez on Me" },
  { artist: "2Pac", title: "Me Against the World" },
  { artist: "Ice Cube", title: "AmeriKKKa's Most Wanted" },
  { artist: "Ice Cube", title: "Death Certificate" },
  { artist: "DJ Quik", title: "Quik Is the Name" },
  { artist: "The Pharcyde", title: "Bizarre Ride II the Pharcyde" },
  // Southern
  { artist: "OutKast", title: "Aquemini" },
  { artist: "OutKast", title: "ATLiens" },
  { artist: "OutKast", title: "Stankonia" },
  { artist: "OutKast", title: "Speakerboxxx/The Love Below" },
  { artist: "UGK", title: "Ridin' Dirty" },
  { artist: "Scarface", title: "The Diary" },
  { artist: "Goodie Mob", title: "Soul Food" },
  { artist: "Three 6 Mafia", title: "Mystic Stylez" },
  { artist: "Lil Wayne", title: "Tha Carter III" },
  { artist: "Lil Wayne", title: "Tha Carter II" },
  { artist: "T.I.", title: "King" },
  // Conscious / Underground
  { artist: "Mos Def", title: "Black on Both Sides" },
  { artist: "Black Star", title: "Mos Def & Talib Kweli Are Black Star" },
  { artist: "Common", title: "Be" },
  { artist: "Common", title: "Like Water for Chocolate" },
  { artist: "The Roots", title: "Things Fall Apart" },
  { artist: "The Roots", title: "Illadelph Halflife" },
  { artist: "Lauryn Hill", title: "The Miseducation of Lauryn Hill" },
  { artist: "Fugees", title: "The Score" },
  { artist: "Madvillain", title: "Madvillainy" },
  { artist: "MF DOOM", title: "Mm..Food" },
  { artist: "MF DOOM", title: "Operation: Doomsday" },
  { artist: "Aesop Rock", title: "Labor Days" },
  { artist: "Company Flow", title: "Funcrusher Plus" },
  { artist: "El-P", title: "Fantastic Damage" },
  { artist: "Cannibal Ox", title: "The Cold Vein" },
  { artist: "Deltron 3030", title: "Deltron 3030" },
  { artist: "Hieroglyphics", title: "3rd Eye Vision" },
  // 2000s
  { artist: "Kanye West", title: "The College Dropout" },
  { artist: "Kanye West", title: "Late Registration" },
  { artist: "Kanye West", title: "My Beautiful Dark Twisted Fantasy" },
  { artist: "Kanye West", title: "Graduation" },
  { artist: "Kanye West", title: "808s & Heartbreak" },
  { artist: "Kanye West", title: "Yeezus" },
  { artist: "Eminem", title: "The Marshall Mathers LP" },
  { artist: "Eminem", title: "The Slim Shady LP" },
  { artist: "50 Cent", title: "Get Rich or Die Tryin'" },
  { artist: "Clipse", title: "Hell Hath No Fury" },
  { artist: "Lupe Fiasco", title: "Food & Liquor" },
  { artist: "Kid Cudi", title: "Man on the Moon: The End of Day" },
  // 2010s-2020s
  { artist: "Kendrick Lamar", title: "good kid, m.A.A.d city" },
  { artist: "Kendrick Lamar", title: "To Pimp a Butterfly" },
  { artist: "Kendrick Lamar", title: "DAMN." },
  { artist: "Kendrick Lamar", title: "Mr. Morale & The Big Steppers" },
  { artist: "J. Cole", title: "2014 Forest Hills Drive" },
  { artist: "Drake", title: "Take Care" },
  { artist: "Drake", title: "Nothing Was the Same" },
  { artist: "Travis Scott", title: "Rodeo" },
  { artist: "Travis Scott", title: "Astroworld" },
  { artist: "Tyler, The Creator", title: "Flower Boy" },
  { artist: "Tyler, The Creator", title: "IGOR" },
  { artist: "Tyler, The Creator", title: "Call Me If You Get Lost" },
  { artist: "Frank Ocean", title: "Channel Orange" },
  { artist: "Danny Brown", title: "Atrocity Exhibition" },
  { artist: "Run The Jewels", title: "Run The Jewels 2" },
  { artist: "Vince Staples", title: "Summertime '06" },
  { artist: "Denzel Curry", title: "TA13OO" },
  { artist: "Freddie Gibbs & Madlib", title: "Piñata" },
  { artist: "Freddie Gibbs & The Alchemist", title: "Alfredo" },
  { artist: "Pusha T", title: "Daytona" },
  { artist: "Earl Sweatshirt", title: "Some Rap Songs" },
  { artist: "Joey Bada$$", title: "1999" },
  { artist: "Isaiah Rashad", title: "The Sun's Tirade" },
  { artist: "JID", title: "The Forever Story" },
  { artist: "Little Simz", title: "Sometimes I Might Be Introvert" },
  { artist: "Skepta", title: "Konnichiwa" },
  { artist: "Stormzy", title: "Gang Signs & Prayer" },
  { artist: "Dave", title: "Psychodrama" },
  { artist: "Slowthai", title: "Nothing Great About Britain" },
  { artist: "Playboi Carti", title: "Die Lit" },
  { artist: "Future", title: "DS2" },
  { artist: "Young Thug", title: "Barter 6" },
  { artist: "Rico Nasty", title: "Nightmare Vacation" },
  { artist: "Noname", title: "Room 25" },
  { artist: "Rapsody", title: "Eve" },
  { artist: "Megan Thee Stallion", title: "Good News" },
  { artist: "Baby Keem", title: "The Melodic Blue" },
  { artist: "Nas", title: "King's Disease II" },
  // Bonus International
  { artist: "Dizzee Rascal", title: "Boy in da Corner" },
  { artist: "Roots Manuva", title: "Run Come Save Me" },
  { artist: "Missy Elliott", title: "Supa Dupa Fly" },
  { artist: "Missy Elliott", title: "Miss E... So Addictive" },
  { artist: "Scarface", title: "The Fix" },
  { artist: "Souls of Mischief", title: "93 'til Infinity" },
  { artist: "Pete Rock & CL Smooth", title: "Mecca and the Soul Brother" },
  { artist: "Czarface & MF DOOM", title: "Super What?" },
  { artist: "Boldy James & The Alchemist", title: "The Price of Tea in China" },
  { artist: "Lil' Kim", title: "Hard Core" },
  { artist: "Foxy Brown", title: "Ill Na Na" },
  { artist: "Cam'ron", title: "Purple Haze" },
  { artist: "The Diplomats", title: "Diplomatic Immunity" },
  { artist: "Jadakiss", title: "Kiss tha Game Goodbye" },
  { artist: "Redman", title: "Dare Iz a Darkside" },
  { artist: "Method Man", title: "Tical" },
  { artist: "Ol' Dirty Bastard", title: "Return to the 36 Chambers: The Dirty Version" },
  { artist: "Westside Gunn", title: "Pray for Paris" },
  { artist: "Conway the Machine", title: "From King to a GOD" },
  { artist: "Logic", title: "Under Pressure" },
  { artist: "Cordae", title: "The Lost Boy" },
  { artist: "Killer Mike", title: "R.A.P. Music" },
  { artist: "Big K.R.I.T.", title: "4eva Is a Mighty Long Time" },
  { artist: "Curren$y", title: "Pilot Talk" },
  { artist: "Mac Miller", title: "Swimming" },
  { artist: "Chance the Rapper", title: "Acid Rap" },
  { artist: "Tierra Whack", title: "Whack World" },
  { artist: "Quelle Chris", title: "Being You Is Great, I Wish I Could Be You More Often" },
  { artist: "billy woods & Kenny Segal", title: "Maps" },
  { artist: "Armand Hammer", title: "Haram" },
  { artist: "Ka", title: "Descendants of Cain" },
  { artist: "Saba", title: "Care for Me" },
  { artist: "Smino", title: "blkswn" },

  // --- Discovered via Last.fm ---
  { artist: "Doja Cat", title: "Scarlet" },
  { artist: "Juice WRLD", title: "Goodbye & Good Riddance" },
  { artist: "XXXTENTACION", title: "17" },
  { artist: "Flobots", title: "Fight With Tools" },
  { artist: "Migos", title: "Culture II" },
  { artist: "The Roots", title: "Phrenology" },
  { artist: "The Roots", title: "Do You Want More?!!!??!" },
  { artist: "Lil Tecca", title: "DOPAMINE" },
  { artist: "Azealia Banks", title: "Slay-Z" },
  { artist: "Beastie Boys", title: "To the 5 Boroughs" },
  { artist: "Fergie", title: "The Dutchess" },
  { artist: "MF DOOM", title: "Born Like This" },
  { artist: "21 Savage", title: "Issa Album" },
  { artist: "The Carters", title: "EVERYTHING IS LOVE" },
  { artist: "Beastie Boys", title: "Hello Nasty" },
  { artist: "Lil Baby", title: "Drip Harder" },
  { artist: "J. Cole", title: "Cole World: The Sideline Story" },
  { artist: "De Jeugd van Tegenwoordig", title: "De Lachende Derde" },
  { artist: "Talib Kweli", title: "Quality" },
  { artist: "The Streets", title: "Original Pirate Material" },
  { artist: "J. Cole", title: "MIDDLE CHILD" },
  { artist: "The Pharcyde", title: "Labcabincalifornia" },
  { artist: "Aesop Rock", title: "None Shall Pass" },
  { artist: "Kendrick Lamar", title: "euphoria" },
  { artist: "Beastie Boys", title: "Check Your Head" },
  { artist: "Vanilla Ice", title: "To The Extreme" },
  { artist: "Post Malone", title: "Stoney (Deluxe)" },
  { artist: "$uicideboy$", title: "I Want To Die In New Orleans" },
  { artist: "Desiigner", title: "New English" },
  { artist: "O.S.T.R.", title: "Tabasko" },
  { artist: "Rick Ross", title: "Port Of Miami" },
  { artist: "Young Dolph", title: "Rich Slave" },
  { artist: "Organized Konfusion", title: "Stress: The Extinction Agenda" },
  { artist: "Insane Clown Posse", title: "Riddle Box" },
  { artist: "Black Eyed Peas", title: "Behind The Front" },
  { artist: "will.i.am", title: "Songs About Girls" },
  { artist: "Public Enemy", title: "Yo! Bum Rush the Show" },
  { artist: "Cover Drive", title: "Bajan Style" },
  { artist: "Kaliber 44", title: "W 63 minuty dookoła świata" },
  { artist: "DJ Shadow", title: "Preemptive Strike" },
  { artist: "dälek", title: "Absence" },
  { artist: "Blackalicious", title: "Nia" },
  { artist: "Kenny Beats", title: "LOUIE" },
  { artist: "DJ Shadow", title: "The Private Press" },
  { artist: "IZA", title: "Dona de Mim" },
  { artist: "Ghostemane", title: "BLACKMAGE" },
  { artist: "Coolio", title: "Gangsta's Paradise" },
  { artist: "CunninLynguists", title: "A Piece of Strange" },
  { artist: "Atmosphere", title: "When Life Gives You Lemons, You Paint That Shit Gold" },
  { artist: "Jinsang", title: "Life" },
  { artist: "MC Hammer", title: "Please Hammer Don't Hurt 'Em" },
  { artist: "PRO8L3M", title: "PRO8L3M" },
  { artist: "Jon Bellion", title: "The Human Condition" },
  { artist: "Beastie Boys", title: "Hot Sauce Committee Part Two" },
  { artist: "Manafest", title: "Glory" },
  { artist: "Flying Lotus", title: "Yasuke" },
  { artist: "Eminem", title: "Rap God" },
  { artist: "The Cool Kids", title: "The Bake Sale" },
  { artist: "De La Soul", title: "Art Official Intelligence: Mosaic Thump" },
  { artist: "BROCKHAMPTON", title: "SATURATION" },
  { artist: "donGURALesko", title: "El Polako" },
  { artist: "Fisz", title: "Polepione dźwięki" },
  { artist: "Organized Konfusion", title: "Organized Konfusion" },
  { artist: "Public Enemy", title: "Muse Sick-N-Hour Mess Age" },
  { artist: "Trevor Daniel", title: "Falling" },
  { artist: "Rizzle Kicks", title: "Stereo Typical" },
  { artist: "BROCKHAMPTON", title: "THE FAMILY" },
  { artist: "Drake", title: "Views" },
  { artist: "Chiddy Bang", title: "The Preview" },
  { artist: "Ugly God", title: "The Booty Tape" },
  { artist: "House of Pain", title: "Same As It Ever Was" },
  { artist: "Pezet", title: "Muzyka Emocjonalna" },
  { artist: "Lil' Kim", title: "The Naked Truth" },
  { artist: "Illa J", title: "Yancey Boys" },
  { artist: "Hollywood Undead", title: "American Tragedy" },
  { artist: "Masta Ace", title: "Disposable Arts" },
  { artist: "BROCKHAMPTON", title: "TM" },
  { artist: "Post Malone", title: "rockstar" },
  { artist: "E-40", title: "My Ghetto Report Card" },
  { artist: "N*E*R*D", title: "Fly Or Die" },
  { artist: "Lil Pump", title: "Lil Pump" },
  { artist: "$uicideboy$", title: "Sing Me A Lullaby, My Sweet Temptation" },
  { artist: "Hush", title: "Bulletproof" },
  { artist: "N*E*R*D", title: "Seeing Sounds" },
  { artist: "T-Pain", title: "Epiphany" },
  { artist: "Cypress Hill", title: "IV" },
  { artist: "Xamã", title: "Zodíaco" },
  { artist: "Jeru the Damaja", title: "Wrath Of The Math" },
  { artist: "Sage Francis", title: "A Healthy Distrust" },
  { artist: "Sage Francis", title: "Personal Journals" },
  { artist: "Brand Nubian", title: "One for All" },
  { artist: "Atmosphere", title: "Seven's Travels" },
  { artist: "mgk", title: "Binge" },
  { artist: "Nicki Minaj", title: "Massive Attack" },
  { artist: "Conway the Machine", title: "God Don't Make Mistakes" },
  { artist: "Clams Casino", title: "Instrumentals" },
  { artist: "Mýa", title: "Moodring" },
  { artist: "A Boogie wit da Hoodie", title: "The Bigger Artist" },
  { artist: "Raekwon", title: "Only Built 4 Cuban Linx 2" },
  { artist: "GrubSon", title: "O.R.S." },
  { artist: "Diddy", title: "Press Play" },
  { artist: "Fettes Brot", title: "Fettes Brot lässt grüssen" },
  { artist: "N-Dubz", title: "Uncle B" },
  { artist: "Stray Kids", title: "ODDINARY" },
  { artist: "O.S.T.R.", title: "HollyŁódź" },
  { artist: "Björk", title: "Selmasongs: Music From the Motion Picture \"Dancer in the Dark\"" },
  { artist: "Mac Miller", title: "I Love Life, Thank You" },
  { artist: "Webbie", title: "Savage Life" },
  { artist: "G-Eazy", title: "When It's Dark Out" },
  { artist: "Freundeskreis", title: "Quadratur des Kreises" },
  { artist: "Kreayshawn", title: "Somethin' 'Bout Kreay" },
  { artist: "Trouble", title: "EdgeWood" },
  { artist: "BigXthaPlug", title: "THE BIGGEST" },
  { artist: "Gang Starr", title: "Step in the Arena" },
  { artist: "B.o.B", title: "Strange Clouds" },
  { artist: "The Herbaliser", title: "Blow Your Headphones" },
  { artist: "Hieroglyphics", title: "Full Circle" },
  { artist: "RZA", title: "Birth of a Prince" },
  { artist: "TWICE", title: "Alcohol-Free" },
  { artist: "Lil Baby", title: "It's Only Me" },
  { artist: "Black Alien", title: "Abaixo de Zero: Hello Hell" },
  { artist: "Oxxxymiron", title: "ГОРГОРОД" },
  { artist: "MellowHype", title: "BlackenedWhite" },
  { artist: "j-hope", title: "on the street (with J. Cole)" },
  { artist: "Future", title: "HNDRXX" },
  { artist: "Orishas", title: "A Lo Cubano" },
  { artist: "LNGSHOT", title: "Saucin'" },
  { artist: "Mobb Deep", title: "Infamy" },
  { artist: "Eric B. & Rakim", title: "Let The Rhythm Hit 'Em" },
  { artist: "IDK", title: "Is He Real?" },
  { artist: "The Disposable Heroes Of Hiphoprisy", title: "Hypocrisy Is The Greatest Luxury" },
  { artist: "Dan Le Sac vs Scroobius Pip", title: "Angles" },
  { artist: "Juice WRLD", title: "The Party Never Ends" },
  { artist: "Bausa", title: "Powerbausa" },
  { artist: "JID", title: "DiCaprio 2" },
  { artist: "Eric B. & Rakim", title: "Don't Sweat The Technique" },
  { artist: "Outerspace", title: "My Brother's Keeper" },
  { artist: "Pete Philly & Perquisite", title: "Mindstate" },
  { artist: "Kid Cudi", title: "The Boy Who Flew To The Moon (Vol. 1)" },
  { artist: "The Neighbourhood", title: "#000000 & #FFFFFF" },
  { artist: "Rakim", title: "The 18th Letter" },
  { artist: "Azealia Banks", title: "1991 EP" },
  { artist: "Frank Ocean", title: "Biking" },
  { artist: "Bryson Gray", title: "Maga Ain't Got No Color" },
  { artist: "dälek", title: "Abandoned Language" },
  { artist: "Cypress Hill", title: "III: Temples of Boom" },
  { artist: "Marteria", title: "Zum Glück in die Zukunft II" },
  { artist: "Handsome Boy Modeling School", title: "So... How's Your Girl?" },
  { artist: "Jvcki Wai", title: "Enchanted Propaganda" },
  { artist: "DAOKO", title: "Daoko" },
  { artist: "Death Grips", title: "No Love Deep Web" },
  { artist: "The Herbaliser", title: "Take London" },
  { artist: "MONSTA X", title: "THE CLAN pt.2 <GUILTY>" },
  { artist: "SCARLXRD", title: "DXXM" },
  { artist: "Benny the Butcher", title: "Tana Talk 4" },
  { artist: "Insane Clown Posse", title: "Ringmaster" },
  { artist: "DJ Jazzy Jeff & The Fresh Prince", title: "Code Red" },
  { artist: "The Pharcyde", title: "Humboldt Beginnings" },
  { artist: "Childish Gambino", title: "Because the Internet" },
  { artist: "Kodak Black", title: "Project Baby 2: All Grown Up (Deluxe)" },
  { artist: "The Foreign Exchange", title: "Leave It All Behind" },
  { artist: "dead prez", title: "Lets Get Free" },
  { artist: "Miles Davis", title: "Doo-Bop" },
  { artist: "Evil Nine", title: "You Can Be Special Too" },
  { artist: "Wu-Tang Clan", title: "Legendary Weapons" },
  { artist: "Kid Koala", title: "Some Of My Best Friends Are DJs" },
  { artist: "JAY-Z", title: "American Gangster" },
  { artist: "Alfa Mist", title: "Antiphon" },
  { artist: "Takeoff", title: "The Last Rocket" },
  { artist: "Lil Wayne", title: "Tha Carter IV (Complete Edition)" },
  { artist: "Public Enemy", title: "Apocalypse 91...The Enemy Strikes Black" },
  { artist: "Danger Dan", title: "Reflexionen aus dem beschönigten Leben" },
  { artist: "People Under the Stairs", title: "Fun DMC" },
  { artist: "Chance the Rapper", title: "Coloring Book" },
  { artist: "Bad Bunny", title: "nadie sabe lo que va a pasar mañana" },
  { artist: "mgk", title: "Pressure" },
  { artist: "Hemp Gru", title: "Droga" },
  { artist: "Sadistik", title: "The Balancing Act" },
  { artist: "Prezident", title: "Kunst ist eine besitzergreifende Geliebte" },
  { artist: "Del Tha Funkee Homosapien", title: "Both Sides of the Brain" },
  { artist: "Nico & Vinz", title: "Black Star Elephant" },
  { artist: "Dilated Peoples", title: "The Platform" },
  { artist: "Lil Uzi Vert", title: "New Patek" },
  { artist: "Hemp Gru", title: "Klucz" },
  { artist: "Bones", title: "Scumbag" },
  { artist: "St1m", title: "Я - Рэп" },
  { artist: "Oh No", title: "Dr. No's Oxperiment" },
  { artist: "Xamã", title: "Pecado Capital" },
  { artist: "Seventeen", title: "SEVENTEEN 1st Mini Album ’17 CARAT’" },
  { artist: "Drake", title: "Her Loss" },
  { artist: "AZ", title: "Doe or Die" },
  { artist: "Heize", title: "She's fine" },
  { artist: "Rye Rye", title: "Go! Pop! Bang!" },
  { artist: "Lay Bankz", title: "After 7" },
  { artist: "2 Live Crew", title: "As Nasty As They Wanna Be" },
  { artist: "Lil Peep", title: "Come Over When You're Sober, Pt. 2" },
  { artist: "Germ", title: "Germ Has A Deathwish" },
  { artist: "50 Cent", title: "Before I Self-Destruct" },
  { artist: "Cochise", title: "THE INSPECTION" },
  { artist: "Djonga", title: "Quanto Mais Eu Como, Mais Fome Eu Sinto !" },
  { artist: "Z-Ro", title: "The Life Of Joseph W. McVey" },
  { artist: "BlocBoy JB", title: "Look Alive (feat. Drake)" },
  { artist: "Sonic Boom Six", title: "The Ruff Guide to Genre-Terrorism" },
  { artist: "Juice WRLD", title: "Fighting Demons" },
  { artist: "Xavier Wulf", title: "Whiplash'd" },
  { artist: "Wiley", title: "Playtime Is Over" },
  { artist: "K.I.Z.", title: "Urlaub fürs Gehirn" },
  { artist: "Desiigner", title: "Tiimmy Turner" },
  { artist: "Mac Miller", title: "Blue Slide Park" },
  { artist: "Filipe Ret", title: "Revel" },
  { artist: "Drake", title: "Hotline Bling" },
  { artist: "Desiigner", title: "Panda" },
  { artist: "Bow Wow", title: "Wanted" },
  { artist: "Gorillaz", title: "G Sides" },
  { artist: "Lizzo", title: "Lizzobangers" },
  { artist: "Bell Biv DeVoe", title: "Poison" },
  { artist: "Bobby Shmurda", title: "Hot N*gga" },
  { artist: "Pretty Ricky", title: "Bluestars" },
  { artist: "Trouble", title: "Snake Eyes" },
  { artist: "Roots Manuva", title: "Dub Come Save Me" },
  { artist: "Bones", title: "FromBeyondTheGrave" },
  { artist: "Bb trickz", title: "80'z" },
  { artist: "DMX", title: "The Definition Of X: Pick Of The Litter" },
  { artist: "LL Cool J", title: "THE DEFinition" },
  { artist: "Lilas ir Innomine", title: "Išgama" },
  { artist: "A Boogie wit da Hoodie", title: "B4 AVA" },
  { artist: "Eric B. & Rakim", title: "Follow the Leader" },
  { artist: "Insane Clown Posse", title: "Bang! Pow! Boom! nuclear" },
  { artist: "Cypress Hill", title: "Skull & Bones" },
  { artist: "Bones", title: "DeadBoy" },
  { artist: "Macklemore", title: "The Unplanned Mixtape" },
  { artist: "Nicki Minaj", title: "Regret in Your Tears" },
  { artist: "Anacondaz", title: "Без паники" },
  { artist: "NF", title: "Mansion" },
  { artist: "Miguel", title: "Kaleidoscope Dream (Deluxe Version)" },
  { artist: "Death Grips", title: "Jenny Death" },
  { artist: "BROCKHAMPTON", title: "iridescence" },
  { artist: "Pi’erre Bourne", title: "The Life Of Pi'erre 4 (Deluxe)" },
  { artist: "LAY", title: "LAY 02 SHEEP" },
  { artist: "Insane Clown Posse", title: "Carnival of Carnage" },
  { artist: "Bones", title: "SoThereWeStood" },
  { artist: "D12", title: "D12 World" },
  { artist: "Diplo", title: "California" },
  { artist: "Deichkind", title: "Bitte ziehen Sie durch" },
  { artist: "Saul Williams", title: "Saul Williams" },
  { artist: "Shabazz Palaces", title: "Black Up" },
  { artist: "TLC", title: "Ooooooohhh... On the TLC Tip" },
  { artist: "Eyedea & Abilities", title: "E&A" },
  { artist: "Das EFX", title: "Straight Up Sewaside" },
  { artist: "Denzel Curry", title: "Ultimate" },
];
