export const jazz: Array<{ artist: string; title: string }> = [
  // Swing / Pre-Bop
  { artist: "Duke Ellington", title: "Ellington at Newport" },
  { artist: "Duke Ellington", title: "Money Jungle" },
  { artist: "Duke Ellington", title: "Far East Suite" },
  { artist: "Count Basie", title: "The Atomic Mr. Basie" },
  { artist: "Billie Holiday", title: "Lady in Satin" },
  { artist: "Billie Holiday", title: "Lady Sings the Blues" },
  { artist: "Ella Fitzgerald", title: "Ella Fitzgerald Sings the Cole Porter Song Book" },
  { artist: "Ella Fitzgerald", title: "Ella and Louis" },
  { artist: "Louis Armstrong", title: "Hot Fives & Sevens" },
  { artist: "Thelonious Monk", title: "Brilliant Corners" },
  { artist: "Thelonious Monk", title: "Monk's Dream" },
  { artist: "Thelonious Monk", title: "Thelonious Monk with John Coltrane" },
  // Bebop / Hard Bop
  { artist: "Charlie Parker", title: "Charlie Parker with Strings" },
  { artist: "Charlie Parker", title: "Bird and Diz" },
  { artist: "Dizzy Gillespie", title: "Dizzy Atmosphere" },
  { artist: "Bud Powell", title: "The Amazing Bud Powell, Vol. 1" },
  { artist: "Art Blakey & The Jazz Messengers", title: "Moanin'" },
  { artist: "Art Blakey & The Jazz Messengers", title: "A Night at Birdland" },
  { artist: "Horace Silver", title: "Song for My Father" },
  { artist: "Clifford Brown & Max Roach", title: "Clifford Brown & Max Roach" },
  { artist: "Sonny Rollins", title: "Saxophone Colossus" },
  { artist: "Sonny Rollins", title: "A Night at the Village Vanguard" },
  { artist: "Sonny Rollins", title: "The Bridge" },
  { artist: "Lee Morgan", title: "The Sidewinder" },
  { artist: "Freddie Hubbard", title: "Red Clay" },
  { artist: "Hank Mobley", title: "Soul Station" },
  { artist: "Kenny Dorham", title: "Quiet Kenny" },
  { artist: "Dexter Gordon", title: "Go" },
  { artist: "Jackie McLean", title: "Let Freedom Ring" },
  // Cool Jazz / West Coast
  { artist: "Miles Davis", title: "Kind of Blue" },
  { artist: "Miles Davis", title: "Birth of the Cool" },
  { artist: "Miles Davis", title: "Sketches of Spain" },
  { artist: "Miles Davis", title: "In a Silent Way" },
  { artist: "Miles Davis", title: "Bitches Brew" },
  { artist: "Miles Davis", title: "'Round About Midnight" },
  { artist: "Miles Davis", title: "A Tribute to Jack Johnson" },
  { artist: "Miles Davis", title: "On the Corner" },
  { artist: "Dave Brubeck", title: "Time Out" },
  { artist: "Stan Getz & João Gilberto", title: "Getz/Gilberto" },
  { artist: "Chet Baker", title: "Chet Baker Sings" },
  { artist: "Bill Evans Trio", title: "Sunday at the Village Vanguard" },
  { artist: "Bill Evans Trio", title: "Waltz for Debby" },
  { artist: "Bill Evans", title: "Everybody Digs Bill Evans" },
  // Free Jazz / Avant-Garde
  { artist: "John Coltrane", title: "A Love Supreme" },
  { artist: "John Coltrane", title: "Giant Steps" },
  { artist: "John Coltrane", title: "My Favorite Things" },
  { artist: "John Coltrane", title: "Blue Train" },
  { artist: "John Coltrane", title: "Ascension" },
  { artist: "Ornette Coleman", title: "The Shape of Jazz to Come" },
  { artist: "Ornette Coleman", title: "Free Jazz: A Collective Improvisation" },
  { artist: "Albert Ayler", title: "Spiritual Unity" },
  { artist: "Eric Dolphy", title: "Out to Lunch!" },
  { artist: "Eric Dolphy", title: "Out There" },
  { artist: "Cecil Taylor", title: "Unit Structures" },
  { artist: "Sun Ra", title: "Space Is the Place" },
  { artist: "Sun Ra", title: "Lanquidity" },
  { artist: "Pharoah Sanders", title: "Karma" },
  { artist: "Pharoah Sanders", title: "Thembi" },
  { artist: "Alice Coltrane", title: "Journey in Satchidananda" },
  { artist: "Alice Coltrane", title: "Ptah, the El Daoud" },
  { artist: "Don Cherry", title: "Complete Communion" },
  { artist: "Art Ensemble of Chicago", title: "Les Stances à Sophie" },
  { artist: "Anthony Braxton", title: "For Alto" },
  // Vocal Jazz
  { artist: "Sarah Vaughan", title: "Sarah Vaughan with Clifford Brown" },
  { artist: "Nina Simone", title: "I Put a Spell on You" },
  { artist: "Nina Simone", title: "Wild Is the Wind" },
  { artist: "Nina Simone", title: "Pastel Blues" },
  { artist: "Abbey Lincoln", title: "We Insist!" },
  { artist: "Betty Carter", title: "The Audience with Betty Carter" },
  { artist: "Carmen McRae", title: "Carmen Sings Monk" },
  // Fusion
  { artist: "Herbie Hancock", title: "Head Hunters" },
  { artist: "Herbie Hancock", title: "Maiden Voyage" },
  { artist: "Herbie Hancock", title: "Empyrean Isles" },
  { artist: "Wayne Shorter", title: "Speak No Evil" },
  { artist: "Wayne Shorter", title: "Juju" },
  { artist: "Weather Report", title: "Heavy Weather" },
  { artist: "Weather Report", title: "Black Market" },
  { artist: "Return to Forever", title: "Romantic Warrior" },
  { artist: "Mahavishnu Orchestra", title: "The Inner Mounting Flame" },
  { artist: "Pat Metheny Group", title: "Pat Metheny Group" },
  { artist: "Pat Metheny", title: "Bright Size Life" },
  { artist: "Jaco Pastorius", title: "Jaco Pastorius" },
  { artist: "Joe Henderson", title: "Inner Urge" },
  { artist: "Joe Henderson", title: "Page One" },
  { artist: "Grant Green", title: "Green Street" },
  { artist: "Wes Montgomery", title: "The Incredible Jazz Guitar of Wes Montgomery" },
  { artist: "McCoy Tyner", title: "The Real McCoy" },
  // Post-Bop / Modern
  { artist: "Charles Mingus", title: "The Black Saint and the Sinner Lady" },
  { artist: "Charles Mingus", title: "Mingus Ah Um" },
  { artist: "Charles Mingus", title: "Pithecanthropus Erectus" },
  { artist: "Andrew Hill", title: "Point of Departure" },
  { artist: "Bobby Hutcherson", title: "Dialogue" },
  { artist: "Woody Shaw", title: "Rosewood" },
  // Contemporary / 80s-Present
  { artist: "Wynton Marsalis", title: "Black Codes (From the Underground)" },
  { artist: "Branford Marsalis", title: "The Dark Keys" },
  { artist: "Keith Jarrett", title: "The Köln Concert" },
  { artist: "Keith Jarrett", title: "Standards, Vol. 1" },
  { artist: "Brad Mehldau", title: "The Art of the Trio, Vol. 3: Songs" },
  { artist: "Pat Metheny", title: "The Way Up" },
  { artist: "Vijay Iyer", title: "Historicity" },
  { artist: "Robert Glasper Experiment", title: "Black Radio" },
  { artist: "Kamasi Washington", title: "The Epic" },
  { artist: "Kamasi Washington", title: "Heaven and Earth" },
  { artist: "Shabaka Hutchings", title: "Wisdom of Elders" },
  { artist: "Sons of Kemet", title: "Black to the Future" },
  { artist: "Nubya Garcia", title: "Source" },
  { artist: "Makaya McCraven", title: "Universal Beings" },
  { artist: "Makaya McCraven", title: "In These Times" },
  { artist: "Christian Scott aTunde Adjuah", title: "Stretch Music" },
  { artist: "Ambrose Akinmusire", title: "on the tender spot of every calloused moment" },
  { artist: "Esperanza Spalding", title: "Emily's D+Evolution" },
  { artist: "GoGo Penguin", title: "v2.0" },
  { artist: "Snarky Puppy", title: "We Like It Here" },
  { artist: "Tigran Hamasyan", title: "Mockroot" },
  { artist: "Hiromi", title: "Spiral" },
  // Japanese Jazz
  { artist: "Ryo Fukui", title: "Scenery" },
  { artist: "Toshiko Akiyoshi", title: "Insights" },
  // South African Jazz
  { artist: "Abdullah Ibrahim", title: "Mannenberg" },
  { artist: "Hugh Masekela", title: "Hope" },
  // Latin Jazz
  { artist: "Tito Puente", title: "Dance Mania" },
  { artist: "Cal Tjader", title: "Soul Sauce" },
  // Spiritual Jazz
  { artist: "John Coltrane", title: "Interstellar Space" },
  { artist: "Yusef Lateef", title: "Eastern Sounds" },
  { artist: "Mulatu Astatke", title: "Mulatu of Ethiopia" },
  { artist: "Mary Lou Williams", title: "Zodiac Suite" },
  { artist: "Max Roach", title: "We Insist! Freedom Now Suite" },
  { artist: "Ornette Coleman", title: "Science Fiction" },
  { artist: "Charles Lloyd", title: "Forest Flower" },
  { artist: "Ahmad Jamal", title: "At the Pershing: But Not for Me" },
  { artist: "Cannonball Adderley", title: "Somethin' Else" },
  { artist: "Art Pepper", title: "Art Pepper Meets the Rhythm Section" },
  { artist: "Thelonious Monk", title: "Solo Monk" },
  { artist: "Oscar Peterson", title: "Night Train" },
  { artist: "Dave Holland", title: "Conference of the Birds" },
  { artist: "Jack DeJohnette", title: "Special Edition" },
  { artist: "Tomasz Stańko", title: "From the Green Hill" },
  { artist: "Shabaka and the Ancestors", title: "Wisdom of Elders" },
  { artist: "BADBADNOTGOOD", title: "IV" },
  { artist: "Chet Baker", title: "Chet" },
  { artist: "Stan Getz", title: "Focus" },
  { artist: "Sonny Clark", title: "Cool Struttin'" },
  { artist: "Jimmy Smith", title: "The Sermon!" },
  { artist: "Grant Green", title: "Idle Moments" },
  { artist: "Cassandra Wilson", title: "Blue Light 'Til Dawn" },
  { artist: "Diana Krall", title: "The Look of Love" },
  { artist: "Gregory Porter", title: "Liquid Spirit" },
  { artist: "Kurt Rosenwinkel", title: "The Remedy" },
  { artist: "Chris Potter", title: "The Sirens" },
  { artist: "Wayne Shorter", title: "Emanon" },

  // --- Discovered via Last.fm ---
  { artist: "Billie Holiday", title: "Solitude" },
  { artist: "Dorothy Ashby", title: "Afro-Harping" },
  { artist: "Michael Bublé", title: "Michael Bublé" },
  { artist: "Lady Gaga", title: "Harlequin" },
  { artist: "Michael Bublé", title: "Call Me Irresponsible" },
  { artist: "Casiopea", title: "Casiopea" },
  { artist: "Bill Evans Trio", title: "Explorations" },
  { artist: "Caro Emerald", title: "Deleted Scenes from the Cutting Room Floor" },
  { artist: "Roy Hargrove", title: "Earfood" },
  { artist: "Miles Davis", title: "Ascenseur Pour L'échafaud" },
  { artist: "Michael Bublé", title: "Crazy Love" },
  { artist: "Miles Davis Quintet", title: "Relaxin' With The Miles Davis Quintet" },
  { artist: "Oliver Nelson", title: "The Blues and the Abstract Truth" },
  { artist: "Charles Mingus", title: "Mingus Mingus Mingus Mingus Mingus" },
  { artist: "Sarah Vaughan", title: "Swingin' Easy" },
  { artist: "Jamie Cullum", title: "Twentysomething" },
  { artist: "Dexter Gordon", title: "A Swingin' Affair" },
  { artist: "Melody Gardot", title: "My One And Only Thrill" },
  { artist: "Charles Mingus", title: "Blues & Roots" },
  { artist: "Wayne Shorter", title: "Night Dreamer" },
  { artist: "Nat Adderley", title: "Work Song" },
  { artist: "Hank Crawford", title: "Wildflower" },
  { artist: "George Benson", title: "Give Me the Night" },
  { artist: "Herbie Hancock", title: "Fat Albert Rotunda" },
  { artist: "Frank Sinatra", title: "In the Wee Small Hours" },
  { artist: "Miles Davis", title: "Someday My Prince Will Come" },
  { artist: "Thelonious Monk", title: "Straight, No Chaser" },
  { artist: "Esbjörn Svensson Trio", title: "From Gagarin's Point of View" },
  { artist: "Paul Desmond", title: "Take Ten" },
  { artist: "Nat King Cole", title: "The Nat King Cole Story" },
  { artist: "Ernestine Anderson", title: "My Kinda Swing" },
  { artist: "Idris Muhammad", title: "Power of Soul" },
  { artist: "Joni Mitchell", title: "Both Sides Now" },
  { artist: "Pink Martini", title: "Hang On Little Tomato" },
  { artist: "Miles Davis", title: "Get Up With It" },
  { artist: "Norah Jones", title: "Not Too Late" },
  { artist: "Antônio Carlos Jobim", title: "Wave" },
  { artist: "McCoy Tyner", title: "Nights of Ballads & Blues" },
  { artist: "Vince Guaraldi Trio", title: "A Boy Named Charlie Brown" },
  { artist: "Keith Jarrett", title: "My Song" },
  { artist: "Lee Morgan", title: "Cornbread" },
  { artist: "Diana Krall", title: "When I Look In Your Eyes" },
  { artist: "Jamie Cullum", title: "Catching Tales" },
  { artist: "Sade", title: "Soldier of Love" },
  { artist: "Chick Corea", title: "Return to Forever" },
  { artist: "The Dave Brubeck Quartet", title: "Jazz Impressions Of Japan" },
  { artist: "Miles Davis", title: "Porgy and Bess" },
  { artist: "Yussef Kamaal", title: "Black Focus" },
  { artist: "Melody Gardot", title: "Worrisome Heart" },
  { artist: "Bill Evans Trio", title: "At The Village Vanguard" },
  { artist: "Hiromi", title: "Voice" },
  { artist: "Dizzy Gillespie", title: "Groovin' High" },
  { artist: "John Coltrane", title: "Soultrane" },
  { artist: "Lou Donaldson", title: "Blues Walk" },
  { artist: "Bill Evans Trio", title: "Portrait in Jazz" },
  { artist: "Ella Fitzgerald", title: "Lullabies Of Birdland" },
  { artist: "Katie Melua", title: "Piece by Piece" },
  { artist: "Thelonious Monk", title: "Underground" },
  { artist: "Norah Jones", title: "The Fall" },
  { artist: "Paul McCartney", title: "Kisses on the Bottom" },
  { artist: "BADBADNOTGOOD", title: "III" },
  { artist: "Charles Mingus", title: "Let My Children Hear Music" },
  { artist: "Jan Johansson", title: "Jazz på svenska" },
  { artist: "John Scofield", title: "A Go Go" },
  { artist: "Esbjörn Svensson Trio", title: "Seven Days of Falling" },
  { artist: "George Benson", title: "Breezin'" },
  { artist: "Marcin Wasilewski Trio", title: "January" },
  { artist: "Miles Davis Quintet", title: "Cookin' With The Miles Davis Quintet" },
  { artist: "Madeleine Peyroux", title: "Bare Bones" },
  { artist: "Thelonious Monk", title: "Monk's Music" },
  { artist: "Duke Ellington & John Coltrane", title: "Duke Ellington & John Coltrane" },
  { artist: "Miles Davis", title: "Tutu" },
  { artist: "Miles Davis", title: "Sorcerer" },
  { artist: "Jamie Cullum", title: "The Pursuit" },
  { artist: "Sonny Rollins", title: "Sonny Rollins With The Modern Jazz Quartet" },
  { artist: "Art Tatum", title: "Piano Starts Here" },
  { artist: "Eliane Elias", title: "Dreamer" },
  { artist: "Steely Dan", title: "Two Against Nature" },
  { artist: "Blossom Dearie", title: "Blossom Dearie" },
  { artist: "Cannonball Adderley", title: "Somethin' Else (Rudy Van Gelder Edition)" },
  { artist: "Art Farmer", title: "Modern Art" },
  { artist: "Chick Corea", title: "My Spanish Heart" },
  { artist: "Wes Montgomery", title: "A Day In The Life" },
  { artist: "Betty Carter", title: "Inside Betty Carter" },
  { artist: "The Bad Plus", title: "These Are The Vistas" },
  { artist: "Michael Franks", title: "The Art of Tea" },
  { artist: "Julie London", title: "Julie Is Her Name" },
  { artist: "Pat Metheny Group", title: "Letter From Home" },
  { artist: "Miles Davis", title: "Filles de Kilimanjaro" },
  { artist: "Tom Waits", title: "Closing Time" },
  { artist: "The Kilimanjaro Darkjazz Ensemble", title: "The Kilimanjaro Darkjazz Ensemble" },
  { artist: "Boney James", title: "Send One Your Love" },
  { artist: "George Duke", title: "The Aura Will Prevail" },
  { artist: "Casiopea", title: "Photographs" },
  { artist: "Charles Mingus", title: "The Clown" },
  { artist: "Miles Davis", title: "Ascenseur Pour L'Echafaud" },
  { artist: "Katie Melua", title: "Call Off the Search" },
  { artist: "mouse on the keys", title: "An Anxious Object" },
  { artist: "Eva Cassidy", title: "Songbird" },
  { artist: "Chick Corea", title: "Light as a Feather" },
  { artist: "Wayne Shorter", title: "Native Dancer" },
  { artist: "Jan Garbarek", title: "In Praise of Dreams" },
  { artist: "Chet Baker", title: "My Funny Valentine" },
  { artist: "Return to Forever", title: "Hymn Of The Seventh Galaxy" },
  { artist: "Bud Powell", title: "The Amazing Bud Powell" },
  { artist: "Hugh Laurie", title: "Let Them Talk" },
  { artist: "Sonny Clark", title: "Sonny's Crib" },
  { artist: "Herbie Hancock", title: "Sextant" },
  { artist: "Alice Coltrane", title: "Huntington Ashram Monastery" },
  { artist: "Grover Washington, Jr.", title: "Mister Magic" },
  { artist: "Al Di Meola", title: "Elegant Gypsy" },
  { artist: "Sonny Sharrock", title: "Black Woman" },
  { artist: "Esbjörn Svensson Trio", title: "E.S:T. Tuesday Wonderland" },
  { artist: "Bobby Hutcherson", title: "Montara" },
  { artist: "Joe Henderson", title: "Double Rainbow" },
  { artist: "Jan Garbarek", title: "Visible World" },
  { artist: "Stan Getz", title: "Sweet Rain" },
  { artist: "Pat Metheny", title: "Secret Story" },
  { artist: "Skalpel", title: "Skalpel" },
  { artist: "Julie London", title: "Lonely Girl" },
  { artist: "Till Brönner", title: "Oceana" },
  { artist: "Allen Toussaint", title: "The Bright Mississippi" },
  { artist: "John Coltrane", title: "Coltrane Jazz" },
  { artist: "Jimmy Smith", title: "Back at the Chicken Shack" },
  { artist: "Herbie Hancock", title: "MR. HANDS" },
  { artist: "The Comet Is Coming", title: "Trust In The Lifeforce Of The Deep Mystery" },
  { artist: "Anouar Brahem", title: "Le Voyage De Sahar" },
  { artist: "Kenny Dorham", title: "Una Mas" },
  { artist: "Wes Montgomery", title: "Full House" },
  { artist: "Bill Evans", title: "Conversations With Myself" },
  { artist: "Joni Mitchell", title: "Mingus" },
  { artist: "Kenny Burrell", title: "Midnight Blue" },
  { artist: "Piero Umiliani", title: "To-Day's Sound" },
  { artist: "Chick Corea", title: "The Leprechaun" },
  { artist: "Archie Shepp", title: "Attica Blues" },
  { artist: "Milt Jackson", title: "Wizard of the Vibes" },
  { artist: "Diana Krall", title: "Quiet Nights" },
  { artist: "Charles Mingus", title: "Mingus Plays Piano" },
  { artist: "Donald Byrd", title: "Byrd in Hand" },
  { artist: "Weather Report", title: "Weather Report" },
  { artist: "Björk", title: "Gling-Glo" },
  { artist: "Sam Rivers", title: "Fuchsia Swing Song" },
  { artist: "Wes Montgomery", title: "Boss Guitar" },
  { artist: "Paul Desmond", title: "Bossa Antigua" },
  { artist: "Manu Katché", title: "Neighbourhood" },
  { artist: "Bobby Darin", title: "That's All" },
  { artist: "Donald Byrd", title: "Places and Spaces" },
  { artist: "Ella Fitzgerald", title: "Ella" },
  { artist: "Stan Getz", title: "Getz/Gilberto" },
  { artist: "Johnny Hartman", title: "I Just Dropped By To Say Hello" },
  { artist: "Sonny Clark", title: "Leapin' And Lopin'" },
  { artist: "Eberhard Weber", title: "The Colours Of Chloë" },
  { artist: "Miles Davis", title: "Nefertiti" },
  { artist: "Bill Evans", title: "New Jazz Conceptions" },
  { artist: "Sam Rivers", title: "Contours" },
  { artist: "Chet Baker", title: "Embraceable You" },
  { artist: "Hiromi", title: "Another Mind" },
  { artist: "Celeste", title: "Lately - EP" },
  { artist: "Miles Davis", title: "Blue Haze" },
  { artist: "Miles Davis", title: "Miles Ahead" },
  { artist: "Paul Desmond", title: "Summertime" },
  { artist: "The Cinematic Orchestra", title: "Man With a Movie Camera" },
  { artist: "Nina Simone", title: "Little Girl Blue" },
  { artist: "Cassandra Wilson", title: "Traveling Miles" },
  { artist: "Joshua Redman", title: "Wish" },
  { artist: "Pat Metheny Group", title: "Offramp" },
  { artist: "Sun Ra", title: "Jazz In Silhouette" },
  { artist: "Tom Waits", title: "Nighthawks at the Diner" },
  { artist: "Duke Ellington", title: "Blues In Orbit" },
  { artist: "Wayne Shorter", title: "Schizophrenia" },
  { artist: "Oliver Nelson", title: "Sound Pieces" },
  { artist: "Dizzy Gillespie", title: "Afro" },
  { artist: "Art Blakey & The Jazz Messengers", title: "Mosaic" },
  { artist: "Herbie Hancock", title: "Inventions & Dimensions" },
  { artist: "Herbie Hancock", title: "Man-Child" },
  { artist: "Donald Byrd", title: "A New Perspective" },
  { artist: "Quincy Jones", title: "You've Got It Bad Girl" },
  { artist: "Duke Ellington", title: "Ellington At Newport 1956 (Complete)" },
  { artist: "Andra Day", title: "Cheers To The Fall" },
  { artist: "Esbjörn Svensson Trio", title: "Viaticum" },
  { artist: "Weather Report", title: "Mysterious Traveller" },
  { artist: "Ahmad Jamal", title: "Chamber Music Of The New Jazz" },
  { artist: "Wayne Shorter", title: "Adam's Apple" },
  { artist: "Frank Sinatra", title: "Songs for Young Lovers" },
  { artist: "Oscar Peterson", title: "Pastel Moods" },
  { artist: "Miles Davis", title: "Miles in the Sky" },
  { artist: "Cannonball Adderley", title: "Know What I Mean?" },
  { artist: "Nina Simone", title: "Ne me quitte pas" },
  { artist: "Paul Desmond", title: "Glad to Be Unhappy" },
  { artist: "Oscar Peterson Trio", title: "Night Train" },
  { artist: "Aziza Mustafa Zadeh", title: "Dance Of Fire" },
  { artist: "Keith Jarrett", title: "At The Blue Note" },
  { artist: "Avishai Cohen", title: "Aurora" },
  { artist: "Norah Jones", title: "Day Breaks" },
  { artist: "Art Blakey", title: "Moanin'" },
  { artist: "Pat Metheny", title: "One Quiet Night" },
  { artist: "Oscar Peterson", title: "Oscar Peterson Plays The Cole Porter Songbook" },
  { artist: "Keith Jarrett", title: "Facing You" },
  { artist: "Joshua Redman", title: "Freedom in the Groove" },
  { artist: "Blossom Dearie", title: "Give Him The Ooh-La-La" },
  { artist: "Arve Henriksen", title: "Cartography" },
  { artist: "Robert Glasper", title: "In My Element" },
  { artist: "Erroll Garner", title: "The Original Misty" },
  { artist: "Sarah Vaughan", title: "Sarah Vaughan" },
  { artist: "Jaga Jazzist", title: "One-Armed Bandit" },
  { artist: "Aisha Duo", title: "Quiet Songs" },
  { artist: "The Crusaders", title: "Street Life" },
  { artist: "Thelonious Monk", title: "It's Monk's Time" },
  { artist: "Wynton Marsalis", title: "Standard Time Vol. 3: The Resolution Of Romance" },
  { artist: "John Coltrane", title: "Coltrane Plays the Blues" },
  { artist: "Manu Katché", title: "Third Round" },
  { artist: "Cassandra Wilson", title: "New Moon Daughter" },
  { artist: "Avishai Cohen", title: "At Home" },
  { artist: "Nina Simone", title: "Baltimore" },
  { artist: "Ornette Coleman", title: "Tomorrow Is The Question!" },
  { artist: "Gábor Szabó", title: "Dreams" },
  { artist: "Brian Culbertson", title: "It's On Tonight" },
  { artist: "Donald Byrd", title: "Street Lady" },
  { artist: "Joe Pass", title: "Intercontinental" },
  { artist: "John Coltrane", title: "Meditations" },
  { artist: "Roy Hargrove", title: "Nothing Serious" },
  { artist: "Abbey Lincoln", title: "Abbey Is Blue" },
  { artist: "Trombone Shorty", title: "Backatown" },
  { artist: "Bob James", title: "One" },
  { artist: "Jim Hall", title: "Concierto" },
  { artist: "Wayne Shorter", title: "Adam's Apple (Rudy Van Gelder Edition)" },
  { artist: "Miles Davis", title: "The Musings Of Miles" },
  { artist: "Piero Umiliani", title: "La legge dei gangsters" },
  { artist: "Lee Morgan", title: "The Gigolo" },
  { artist: "John Coltrane", title: "Olé Coltrane" },
  { artist: "Herbie Hancock", title: "Crossings" },
  { artist: "Hank Mobley", title: "No Room for Squares" },
  { artist: "Ahmad Jamal", title: "Ahmad's Blues" },
  { artist: "Keith Jarrett", title: "Treasure Island" },
  { artist: "Sonny Rollins", title: "Way Out West" },
  { artist: "Dr. John", title: "Locked Down" },
  { artist: "Mose Allison", title: "I Don't Worry About A Thing" },
  { artist: "Charlie Haden", title: "Nocturne" },
  { artist: "Sun Ra", title: "The Futuristic Sounds Of Sun Ra" },
  { artist: "Djavan", title: "Djavan \"Ao Vivo\"" },
  { artist: "Esperanza Spalding", title: "Chamber Music Society" },
  { artist: "Diana Krall", title: "All for You: A Dedication to the Nat King Cole Trio" },
  { artist: "Ron Carter", title: "Blues Farm" },
  { artist: "Esperanza Spalding", title: "Radio Music Society" },
  { artist: "Ray Brown Trio", title: "Soular Energy" },
  { artist: "De-Phazz", title: "Death By Chocolate" },
  { artist: "Jimmy Smith", title: "House Party" },
  { artist: "Stacey Kent", title: "Breakfast On The Morning Tram" },
  { artist: "Sun Ra", title: "Sleeping Beauty" },
  { artist: "Weather Report", title: "Sweetnighter" },
];
