export const metal: Array<{ artist: string; title: string }> = [
  // Proto-Metal / Classic Heavy Metal
  { artist: "Black Sabbath", title: "Black Sabbath" },
  { artist: "Black Sabbath", title: "Paranoid" },
  { artist: "Black Sabbath", title: "Master of Reality" },
  { artist: "Black Sabbath", title: "Vol. 4" },
  { artist: "Black Sabbath", title: "Sabbath Bloody Sabbath" },
  { artist: "Judas Priest", title: "British Steel" },
  { artist: "Judas Priest", title: "Screaming for Vengeance" },
  { artist: "Judas Priest", title: "Sad Wings of Destiny" },
  { artist: "Judas Priest", title: "Painkiller" },
  { artist: "Motörhead", title: "Ace of Spades" },
  { artist: "Motörhead", title: "Overkill" },
  { artist: "Rainbow", title: "Rising" },
  { artist: "Dio", title: "Holy Diver" },
  { artist: "Ozzy Osbourne", title: "Blizzard of Ozz" },
  // NWOBHM
  { artist: "Iron Maiden", title: "The Number of the Beast" },
  { artist: "Iron Maiden", title: "Powerslave" },
  { artist: "Iron Maiden", title: "Seventh Son of a Seventh Son" },
  { artist: "Iron Maiden", title: "Iron Maiden" },
  { artist: "Iron Maiden", title: "Brave New World" },
  { artist: "Diamond Head", title: "Lightning to the Nations" },
  { artist: "Angel Witch", title: "Angel Witch" },
  { artist: "Saxon", title: "Wheels of Steel" },
  { artist: "Venom", title: "Black Metal" },
  { artist: "Venom", title: "Welcome to Hell" },
  // Thrash Metal
  { artist: "Metallica", title: "Master of Puppets" },
  { artist: "Metallica", title: "Ride the Lightning" },
  { artist: "Metallica", title: "...And Justice for All" },
  { artist: "Metallica", title: "Kill 'Em All" },
  { artist: "Metallica", title: "Metallica" },
  { artist: "Slayer", title: "Reign in Blood" },
  { artist: "Slayer", title: "Seasons in the Abyss" },
  { artist: "Slayer", title: "South of Heaven" },
  { artist: "Megadeth", title: "Rust in Peace" },
  { artist: "Megadeth", title: "Peace Sells... but Who's Buying?" },
  { artist: "Megadeth", title: "Countdown to Extinction" },
  { artist: "Anthrax", title: "Among the Living" },
  { artist: "Exodus", title: "Bonded by Blood" },
  { artist: "Testament", title: "The Legacy" },
  { artist: "Kreator", title: "Pleasure to Kill" },
  { artist: "Sodom", title: "Agent Orange" },
  { artist: "Destruction", title: "Eternal Devastation" },
  { artist: "Sepultura", title: "Arise" },
  { artist: "Sepultura", title: "Beneath the Remains" },
  { artist: "Pantera", title: "Vulgar Display of Power" },
  { artist: "Pantera", title: "Cowboys from Hell" },
  // Death Metal
  { artist: "Death", title: "Symbolic" },
  { artist: "Death", title: "Human" },
  { artist: "Death", title: "Leprosy" },
  { artist: "Death", title: "Individual Thought Patterns" },
  { artist: "Morbid Angel", title: "Altars of Madness" },
  { artist: "Morbid Angel", title: "Blessed Are the Sick" },
  { artist: "Cannibal Corpse", title: "Tomb of the Mutilated" },
  { artist: "Obituary", title: "Cause of Death" },
  { artist: "Entombed", title: "Left Hand Path" },
  { artist: "Dismember", title: "Like an Everflowing Stream" },
  { artist: "Bolt Thrower", title: "The IVth Crusade" },
  { artist: "At the Gates", title: "Slaughter of the Soul" },
  { artist: "Carcass", title: "Heartwork" },
  { artist: "Carcass", title: "Necroticism – Descanting the Insalubrious" },
  { artist: "Suffocation", title: "Pierced from Within" },
  { artist: "Gorguts", title: "Obscura" },
  { artist: "Atheist", title: "Unquestionable Presence" },
  { artist: "Cynic", title: "Focus" },
  { artist: "Nile", title: "Annihilation of the Wicked" },
  { artist: "Bloodbath", title: "Nightmares Made Flesh" },
  // Black Metal
  { artist: "Bathory", title: "Under the Sign of the Black Mark" },
  { artist: "Bathory", title: "Blood Fire Death" },
  { artist: "Mayhem", title: "De Mysteriis Dom Sathanas" },
  { artist: "Burzum", title: "Hvis lyset tar oss" },
  { artist: "Burzum", title: "Filosofem" },
  { artist: "Darkthrone", title: "A Blaze in the Northern Sky" },
  { artist: "Darkthrone", title: "Transilvanian Hunger" },
  { artist: "Emperor", title: "In the Nightside Eclipse" },
  { artist: "Emperor", title: "Anthems to the Welkin at Dusk" },
  { artist: "Immortal", title: "At the Heart of Winter" },
  { artist: "Dissection", title: "Storm of the Light's Bane" },
  { artist: "Enslaved", title: "Below the Lights" },
  { artist: "Blut Aus Nord", title: "The Work Which Transforms God" },
  { artist: "Deathspell Omega", title: "Si Monvmentvm Reqvires, Circvmspice" },
  { artist: "Wolves in the Throne Room", title: "Two Hunters" },
  { artist: "Agalloch", title: "The Mantle" },
  { artist: "Alcest", title: "Écailles de Lune" },
  { artist: "Mgła", title: "Exercises in Futility" },
  // Doom Metal
  { artist: "Candlemass", title: "Epicus Doomicus Metallicus" },
  { artist: "Saint Vitus", title: "Born Too Late" },
  { artist: "Electric Wizard", title: "Dopethrone" },
  { artist: "Sleep", title: "Dopesmoker" },
  { artist: "Sleep", title: "Sleep's Holy Mountain" },
  { artist: "Sunn O)))", title: "Monoliths & Dimensions" },
  { artist: "Bell Witch", title: "Mirror Reaper" },
  { artist: "Yob", title: "Clearing the Path to Ascend" },
  // Progressive Metal
  { artist: "Dream Theater", title: "Images and Words" },
  { artist: "Dream Theater", title: "Metropolis Pt. 2: Scenes from a Memory" },
  { artist: "Tool", title: "Lateralus" },
  { artist: "Tool", title: "Ænima" },
  { artist: "Tool", title: "Fear Inoculum" },
  { artist: "Opeth", title: "Blackwater Park" },
  { artist: "Opeth", title: "Still Life" },
  { artist: "Opeth", title: "Ghost Reveries" },
  { artist: "Mastodon", title: "Leviathan" },
  { artist: "Mastodon", title: "Crack the Skye" },
  { artist: "Between the Buried and Me", title: "Colors" },
  { artist: "Meshuggah", title: "Destroy Erase Improve" },
  { artist: "Meshuggah", title: "ObZen" },
  { artist: "Gojira", title: "From Mars to Sirius" },
  { artist: "Gojira", title: "The Way of All Flesh" },
  // Power Metal
  { artist: "Helloween", title: "Keeper of the Seven Keys: Part II" },
  { artist: "Helloween", title: "Keeper of the Seven Keys: Part I" },
  { artist: "Blind Guardian", title: "Nightfall in Middle-Earth" },
  { artist: "Blind Guardian", title: "Imaginations from the Other Side" },
  { artist: "Stratovarius", title: "Visions" },
  { artist: "Rhapsody of Fire", title: "Symphony of Enchanted Lands" },
  { artist: "Gamma Ray", title: "Land of the Free" },
  // Sludge / Post-Metal
  { artist: "Neurosis", title: "Through Silver in Blood" },
  { artist: "Neurosis", title: "Times of Grace" },
  { artist: "Isis", title: "Oceanic" },
  { artist: "Isis", title: "Panopticon" },
  { artist: "Converge", title: "Jane Doe" },
  { artist: "The Dillinger Escape Plan", title: "Calculating Infinity" },
  { artist: "Baroness", title: "Purple" },
  { artist: "Deafheaven", title: "Sunbather" },
  { artist: "Pallbearer", title: "Sorrow and Extinction" },
  // Modern / 2010s-2020s Metal
  { artist: "Power Trip", title: "Nightmare Logic" },
  { artist: "Tomb Mold", title: "Manor of Infinite Forms" },
  { artist: "Blood Incantation", title: "Hidden History of the Human Race" },
  { artist: "Undeath", title: "It's Time... to Rise from the Grave" },
  { artist: "Liturgy", title: "Aesthethica" },
  { artist: "Lorna Shore", title: "Pain Remains" },
  { artist: "Knocked Loose", title: "A Tear in the Fabric of Life" },
  { artist: "Spiritbox", title: "Eternal Blue" },
  { artist: "Rammstein", title: "Mutter" },
  { artist: "System of a Down", title: "Toxicity" },
  { artist: "Deftones", title: "White Pony" },
  { artist: "Deftones", title: "Around the Fur" },
  { artist: "Lamb of God", title: "Ashes of the Wake" },
  { artist: "High on Fire", title: "De Vermis Mysteriis" },
  { artist: "Mastodon", title: "Blood Mountain" },
  { artist: "The Sword", title: "Age of Winters" },
  { artist: "Kvelertak", title: "Kvelertak" },
  { artist: "Vektor", title: "Terminal Redux" },
  { artist: "Horrendous", title: "Idol" },
  { artist: "Cattle Decapitation", title: "Death Atlas" },
  { artist: "Ulcerate", title: "Stare into Death and Be Still" },
  { artist: "Oranssi Pazuzu", title: "Mestarin kynsi" },
  { artist: "Imperial Triumphant", title: "Alphaville" },
  { artist: "Full of Hell", title: "Garden of Burning Apparitions" },
  { artist: "Zeal & Ardor", title: "Zeal & Ardor" },
  { artist: "Wormrot", title: "Voices" },
  { artist: "Archspire", title: "Bleed the Future" },

  // --- Discovered via Last.fm ---
  { artist: "Korn", title: "Korn" },
  { artist: "Bullet for My Valentine", title: "Scream Aim Fire" },
  { artist: "BABYMETAL", title: "BABYMETAL" },
  { artist: "Pantera", title: "Far Beyond Driven" },
  { artist: "Disturbed", title: "Believe" },
  { artist: "Kittie", title: "Oracle" },
  { artist: "Sevendust", title: "Home" },
  { artist: "Five Finger Death Punch", title: "The Way Of The Fist" },
  { artist: "Atreyu", title: "A Death-Grip on Yesterday" },
  { artist: "Metallica", title: "St. Anger" },
  { artist: "Metallica", title: "Garage, Inc." },
  { artist: "Rammstein", title: "Liebe ist für alle da" },
  { artist: "All That Remains", title: "Overcome" },
  { artist: "Nightwish", title: "Dark Passion Play" },
  { artist: "Mudvayne", title: "The End of All Things to Come" },
  { artist: "Mudvayne", title: "Mudvayne" },
  { artist: "Killswitch Engage", title: "The End of Heartache" },
  { artist: "Apocalyptica", title: "Apocalyptica" },
  { artist: "Otep", title: "Sevas Tra" },
  { artist: "Rammstein", title: "RAMMSTEIN" },
  { artist: "Rammstein", title: "Herzeleid" },
  { artist: "Rob Zombie", title: "Educated Horses" },
  { artist: "Static-X", title: "Start a War" },
  { artist: "Sentenced", title: "The Cold White Light" },
  { artist: "Mudvayne", title: "The New Game" },
  { artist: "Static-X", title: "Cannibal" },
  { artist: "Trivium", title: "Ascendancy" },
  { artist: "Static-X", title: "Shadow Zone" },
  { artist: "Nightwish", title: "Century Child" },
  { artist: "Marilyn Manson", title: "Antichrist Superstar" },
  { artist: "Hellyeah", title: "HELLYEAH" },
  { artist: "Kittie", title: "Until the End" },
  { artist: "Within Temptation", title: "The Silent Force" },
  { artist: "DragonForce", title: "Inhuman Rampage" },
  { artist: "Megadeth", title: "Youthanasia" },
  { artist: "Metallica", title: "Beyond Magnetic" },
  { artist: "Genitorturers", title: "Blackheart Revolution" },
  { artist: "Parkway Drive", title: "Don't Close Your Eyes" },
  { artist: "Paradise Lost", title: "Symbol of Life" },
  { artist: "Mushroomhead", title: "XIII" },
  { artist: "Lacuna Coil", title: "Karmacode" },
  { artist: "Five Finger Death Punch", title: "War Is the Answer" },
  { artist: "Trivium", title: "Shogun" },
  { artist: "Machine Head", title: "The Blackening" },
  { artist: "Suicide Silence", title: "No Time to Bleed" },
  { artist: "White Zombie", title: "Let Sleeping Corpses Lie" },
  { artist: "Mudvayne", title: "The Beginning of All Things to End" },
  { artist: "Disturbed", title: "Indestructible" },
  { artist: "Sodom", title: "M-16" },
  { artist: "Civil War", title: "The Killer Angels" },
  { artist: "Within Temptation", title: "The Heart of Everything" },
  { artist: "Godsmack", title: "IV" },
  { artist: "Megadeth", title: "The System Has Failed" },
  { artist: "Machine Head", title: "Through the Ashes of Empires" },
  { artist: "Iron Maiden", title: "Piece of Mind" },
  { artist: "Kreator", title: "Enemy of God" },
  { artist: "Testament", title: "The Formation of Damnation" },
  { artist: "Iron Maiden", title: "Somewhere In Time" },
  { artist: "Halestorm", title: "ReAnimate: The Covers EP" },
  { artist: "Sonata Arctica", title: "Stones Grow Her Name" },
  { artist: "Haste The Day", title: "When Everything Falls" },
  { artist: "Nargaroth", title: "Black Metal ist Krieg" },
  { artist: "Judas Priest", title: "Firepower" },
  { artist: "Slipknot", title: "Vol. 3: (The Subliminal Verses)" },
  { artist: "Trivium", title: "The Crusade" },
  { artist: "Edguy", title: "Rocket Ride" },
  { artist: "Machine Head", title: "The Burning Red" },
  { artist: "Amorphis", title: "Eclipse" },
  { artist: "Lordi", title: "The Arockalypse" },
  { artist: "Trivium", title: "Silence In The Snow" },
  { artist: "Skindred", title: "Roots Rock Riot" },
  { artist: "Architects", title: "Hollow Crown" },
  { artist: "My Ruin", title: "A Prayer Under Pressure Of Violent Anguish" },
  { artist: "Slayer", title: "World Painted Blood" },
  { artist: "Arch Enemy", title: "Anthems of Rebellion" },
  { artist: "Bullet for My Valentine", title: "Temper Temper (Deluxe Version)" },
  { artist: "Killswitch Engage", title: "As Daylight Dies" },
  { artist: "Parkway Drive", title: "Horizons" },
  { artist: "DevilDriver", title: "The Last Kind Words" },
  { artist: "Killswitch Engage", title: "Killswitch Engage" },
  { artist: "Misery Signals", title: "Controller" },
  { artist: "Disturbed", title: "Divisive" },
  { artist: "Angra", title: "Freedom Call" },
  { artist: "After the Burial", title: "Forging A Future Self" },
  { artist: "Slayer", title: "Hell Awaits" },
  { artist: "Nightwish", title: "Over the Hills and Far Away" },
  { artist: "Bullet for My Valentine", title: "Bullet For My Valentine" },
  { artist: "Edguy", title: "Vain Glory Opera" },
  { artist: "Evanescence", title: "Bring Me to Life" },
  { artist: "Slayer", title: "Divine Intervention" },
  { artist: "Atreyu", title: "The Curse" },
  { artist: "Alter Bridge", title: "Fortress" },
  { artist: "Haste The Day", title: "Dreamer" },
  { artist: "Fear Factory", title: "Demanufacture" },
  { artist: "Dead by April", title: "Dead by April" },
  { artist: "Paradise Lost", title: "Draconian Times" },
  { artist: "Lacuna Coil", title: "Shallow Life" },
  { artist: "Judas Priest", title: "Killing Machine" },
  { artist: "For Today", title: "Breaker" },
  { artist: "Bullet for My Valentine", title: "The Poison (Deluxe Version)" },
  { artist: "Edguy", title: "Hellfire Club" },
  { artist: "Static-X", title: "Cult of Static" },
  { artist: "Amorphis", title: "Skyforger" },
  { artist: "Death", title: "Spiritual Healing" },
  { artist: "CKY", title: "Infiltrate-Destroy-Rebuild" },
  { artist: "Mnemic", title: "The Audio Injected Soul" },
  { artist: "Slipknot", title: ".5: The Gray Chapter" },
  { artist: "Gamma Ray", title: "Somewhere Out in Space" },
  { artist: "Vader", title: "Litany" },
  { artist: "Powerman 5000", title: "Transform" },
  { artist: "Lamb of God", title: "Ashes of the Wake (15th Anniversary)" },
  { artist: "Motörhead", title: "No Remorse" },
  { artist: "The Vision Bleak", title: "The Unknown" },
  { artist: "Sepultura", title: "Schizophrenia" },
  { artist: "Black Label Society", title: "Hangover Music Vol. VI" },
  { artist: "American Head Charge", title: "The War Of Art" },
  { artist: "As Blood Runs Black", title: "Allegiance" },
  { artist: "Texas in July", title: "I Am" },
  { artist: "Lindemann", title: "Skills in Pills" },
  { artist: "Slayer", title: "Christ Illusion" },
  { artist: "Metallica", title: "Hardwired…To Self-Destruct" },
  { artist: "Sonata Arctica", title: "Ecliptica" },
  { artist: "Haste The Day", title: "Pressure The Hinges" },
  { artist: "In Flames", title: "A Sense of Purpose" },
  { artist: "Ozzy Osbourne", title: "The OZZman Cometh" },
  { artist: "In Flames", title: "Whoracle" },
  { artist: "Fit For A King", title: "Dark Skies" },
  { artist: "Hatebreed", title: "Supremacy" },
  { artist: "Skindred", title: "Union Black" },
  { artist: "Arch Enemy", title: "Wages of Sin" },
  { artist: "Textures", title: "Silhouettes" },
  { artist: "Killswitch Engage", title: "Killswitch Engage (Special Edition)" },
  { artist: "Satyricon", title: "Now, Diabolical" },
  { artist: "Fear Factory", title: "Obsolete" },
  { artist: "Danzig", title: "Danzig II: Lucifuge" },
  { artist: "Cradle of Filth", title: "Nymphetamine" },
  { artist: "Soulfly", title: "3" },
  { artist: "Poppy", title: "Fear of Dying" },
  { artist: "Suicide Silence", title: "The Cleansing" },
  { artist: "Exodus", title: "Fabulous Disaster" },
  { artist: "Megadeth", title: "Dystopia" },
  { artist: "Gamma Ray", title: "Power Plant" },
  { artist: "Otep", title: "Smash the Control Machine" },
  { artist: "Haste The Day", title: "Burning Bridges" },
  { artist: "Celtic Frost", title: "Into The Pandemonium" },
  { artist: "Rob Zombie", title: "Past, Present & Future" },
  { artist: "Skindred", title: "Babylon" },
  { artist: "Jinjer", title: "King of Everything" },
  { artist: "HammerFall", title: "No Sacrifice, No Victory" },
  { artist: "36 Crazyfists", title: "A Snow Capped Romance" },
  { artist: "Iron Maiden", title: "Killers" },
  { artist: "Fear Factory", title: "Mechanize" },
  { artist: "Spineshank", title: "The Height of Callousness" },
  { artist: "Killswitch Engage", title: "(Set This) World Ablaze" },
  { artist: "Nightwish", title: "Oceanborn" },
  { artist: "Venom", title: "In League With Satan" },
  { artist: "Amaranthe", title: "Amaranthe" },
  { artist: "Rammstein", title: "Liebe ist fur alle da" },
  { artist: "DevilDriver", title: "DevilDriver" },
  { artist: "Arch Enemy", title: "Doomsday Machine" },
  { artist: "Still Remains", title: "Of Love and Lunacy" },
  { artist: "Black Sabbath", title: "Heaven and Hell" },
  { artist: "Iron Maiden", title: "The Final Frontier" },
  { artist: "Iron Maiden", title: "Dance of Death" },
  { artist: "Megadeth", title: "Rust In Peace (2004 Remix / Expanded Edition)" },
  { artist: "The Black Dahlia Murder", title: "Miasma" },
  { artist: "36 Crazyfists", title: "The Tide and Its Takers" },
  { artist: "Accept", title: "Balls to the Wall" },
  { artist: "Chimaira", title: "Resurrection" },
  { artist: "Anthrax", title: "Spreading the Disease" },
  { artist: "Dream Evil", title: "The Book Of Heavy Metal" },
  { artist: "The Gathering", title: "Mandylion" },
  { artist: "Primordial", title: "Where Greater Men Have Fallen" },
  { artist: "Strapping Young Lad", title: "City" },
  { artist: "August Burns Red", title: "Thrill Seeker" },
  { artist: "Death Angel", title: "Frolic Through the Park" },
  { artist: "Sonic Syndicate", title: "We Rule The Night" },
  { artist: "Dystopia", title: "Dystopia" },
  { artist: "Versailles", title: "Holy Grail" },
  { artist: "Megadeth", title: "Cryptic Writings" },
  { artist: "Bullet for My Valentine", title: "Hand of Blood" },
  { artist: "Running Wild", title: "Under Jolly Roger" },
  { artist: "Gamma Ray", title: "No World Order" },
  { artist: "Black Sabbath", title: "13" },
  { artist: "Nothingface", title: "Violence" },
  { artist: "Fear Factory", title: "Hatefiles" },
  { artist: "Edguy", title: "Tinnitus Sanctus" },
  { artist: "Morbid Angel", title: "Covenant" },
  { artist: "Volbeat", title: "Rock The Rebel / Metal The Devil" },
  { artist: "As I Lay Dying", title: "An Ocean Between Us" },
  { artist: "Dorothy", title: "ROCKISDEAD" },
  { artist: "Norma Jean", title: "Meridional" },
  { artist: "Delain", title: "Lucidity" },
  { artist: "Cannibal Corpse", title: "The Bleeding" },
  { artist: "Thy Art Is Murder", title: "Godlike" },
  { artist: "Iron Maiden", title: "No Prayer For The Dying" },
  { artist: "Machine Head", title: "Unto the Locust (Special Edition)" },
  { artist: "Rammstein", title: "Live aus Berlin" },
  { artist: "Darkthrone", title: "Eternal Hails......" },
  { artist: "Electric Wizard", title: "Come My Fanatics(Remaster)" },
  { artist: "Breaking Benjamin", title: "Phobia (Collector Edition)" },
  { artist: "Drowning Pool", title: "Desensitized" },
  { artist: "Ministry", title: "Land of Rape and Honey" },
  { artist: "Racer X", title: "Superheroes" },
  { artist: "Stone Sour", title: "House of Gold & Bones Part 1" },
  { artist: "Infected Rain", title: "86" },
  { artist: "Judas Priest", title: "Defenders of the Faith" },
  { artist: "Motörhead", title: "Bomber" },
  { artist: "Black Sabbath", title: "Dehumanizer" },
  { artist: "Five Finger Death Punch", title: "A Decade Of Destruction" },
  { artist: "My Ruin", title: "Speak & Destroy" },
  { artist: "Iron Maiden", title: "The X Factor" },
  { artist: "Destruction", title: "The Antichrist" },
  { artist: "Anthrax", title: "State of Euphoria" },
  { artist: "OOMPH!", title: "GlaubeLiebeTod" },
  { artist: "Skindred", title: "Babylon (Revised Online Music)" },
  { artist: "The Ghost Inside", title: "Returners" },
  { artist: "OOMPH!", title: "Unrein" },
  { artist: "Disturbed", title: "Immortalized" },
  { artist: "Ozzy Osbourne", title: "Scream" },
  { artist: "The Devil Wears Prada", title: "Plagues" },
  { artist: "Genitorturers", title: "120 Days of Genitorture" },
  { artist: "Helloween", title: "7 Sinners" },
  { artist: "Killswitch Engage", title: "The End of Heartache (Special Edition)" },
  { artist: "Gojira", title: "Terra Incognita" },
  { artist: "Death", title: "The Sound of Perseverance - Reissue" },
  { artist: "Sepultura", title: "Blood-Rooted" },
  { artist: "Saxon", title: "Denim And Leather" },
  { artist: "Vampires Everywhere!", title: "Kiss the Sun Goodbye" },
  { artist: "MyChildren MyBride", title: "Unbreakable" },
  { artist: "DragonForce", title: "Ultra Beatdown" },
  { artist: "Sentenced", title: "Frozen" },
  { artist: "Fantômas", title: "The Director's Cut" },
  { artist: "Ancient Ceremony", title: "Fallen Angel's Symphony" },
  { artist: "Dope", title: "Group Therapy" },
  { artist: "Ratos De Porão", title: "Brasil" },
  { artist: "Bring Me the Horizon", title: "This Is What the Edge of Your Seat Was Made For" },
  { artist: "Xandria", title: "Neverworld's End" },
  { artist: "Evergreen Terrace", title: "Wolfbiker" },
  { artist: "Korpiklaani", title: "Manala" },
  { artist: "Kreator", title: "Hordes of Chaos" },
  { artist: "Tiamat", title: "Skeleton Skeletron" },
  { artist: "Demon Hunter", title: "The Triptych" },
  { artist: "Confide", title: "Shout The Truth" },
  { artist: "Moonspell", title: "Wolfheart" },
  { artist: "DIR EN GREY", title: "DUM SPIRO SPERO" },
  { artist: "Within the Ruins", title: "Invade" },
  { artist: "Strapping Young Lad", title: "The New Black" },
  { artist: "Devin Townsend", title: "Ziltoid the Omniscient" },
  { artist: "Chimaira", title: "Chimaira" },
];
