export const pop: Array<{ artist: string; title: string }> = [
  // 60s Pop
  { artist: "The Beach Boys", title: "Pet Sounds" },
  { artist: "The Beatles", title: "A Hard Day's Night" },
  { artist: "Simon & Garfunkel", title: "Bridge over Troubled Water" },
  { artist: "Simon & Garfunkel", title: "Bookends" },
  { artist: "Dusty Springfield", title: "Dusty in Memphis" },
  { artist: "Dionne Warwick", title: "Make Way for Dionne Warwick" },
  { artist: "Petula Clark", title: "Downtown" },
  { artist: "The Mamas & the Papas", title: "If You Can Believe Your Eyes and Ears" },
  { artist: "The Zombies", title: "Odessey and Oracle" },
  // 70s Pop
  { artist: "Carole King", title: "Tapestry" },
  { artist: "Joni Mitchell", title: "Blue" },
  { artist: "Joni Mitchell", title: "Court and Spark" },
  { artist: "Joni Mitchell", title: "Hejira" },
  { artist: "Elton John", title: "Goodbye Yellow Brick Road" },
  { artist: "Elton John", title: "Honky Château" },
  { artist: "Billy Joel", title: "The Stranger" },
  { artist: "ABBA", title: "Arrival" },
  { artist: "ABBA", title: "The Album" },
  { artist: "Bee Gees", title: "Saturday Night Fever" },
  { artist: "Stevie Wonder", title: "Songs in the Key of Life" },
  { artist: "Harry Nilsson", title: "Nilsson Schmilsson" },
  { artist: "Todd Rundgren", title: "Something/Anything?" },
  { artist: "10cc", title: "The Original Soundtrack" },
  { artist: "Sparks", title: "Kimono My House" },
  // 80s Pop / Synth-Pop
  { artist: "Michael Jackson", title: "Thriller" },
  { artist: "Prince", title: "Purple Rain" },
  { artist: "Madonna", title: "Like a Prayer" },
  { artist: "Madonna", title: "Ray of Light" },
  { artist: "Madonna", title: "True Blue" },
  { artist: "George Michael", title: "Faith" },
  { artist: "Whitney Houston", title: "Whitney Houston" },
  { artist: "Cyndi Lauper", title: "She's So Unusual" },
  { artist: "Pet Shop Boys", title: "Actually" },
  { artist: "Pet Shop Boys", title: "Behaviour" },
  { artist: "Tears for Fears", title: "Songs from the Big Chair" },
  { artist: "a-ha", title: "Hunting High and Low" },
  { artist: "Phil Collins", title: "Face Value" },
  { artist: "Peter Gabriel", title: "So" },
  { artist: "Kate Bush", title: "Hounds of Love" },
  { artist: "Kate Bush", title: "The Kick Inside" },
  { artist: "Kate Bush", title: "The Dreaming" },
  { artist: "Annie Lennox", title: "Diva" },
  { artist: "Eurythmics", title: "Touch" },
  { artist: "The Human League", title: "Dare" },
  { artist: "Yazoo", title: "Upstairs at Eric's" },
  // 90s Pop
  { artist: "Mariah Carey", title: "Daydream" },
  { artist: "Mariah Carey", title: "The Emancipation of Mimi" },
  { artist: "Britney Spears", title: "...Baby One More Time" },
  { artist: "TLC", title: "CrazySexyCool" },
  { artist: "Spice Girls", title: "Spice" },
  { artist: "No Doubt", title: "Tragic Kingdom" },
  { artist: "Sheryl Crow", title: "Sheryl Crow" },
  { artist: "Alanis Morissette", title: "Jagged Little Pill" },
  { artist: "Tori Amos", title: "Little Earthquakes" },
  { artist: "Björk", title: "Debut" },
  { artist: "Björk", title: "Post" },
  { artist: "Everything but the Girl", title: "Amplified Heart" },
  { artist: "The Cranberries", title: "No Need to Argue" },
  { artist: "Fiona Apple", title: "Tidal" },
  { artist: "Fiona Apple", title: "When the Pawn..." },
  // 2000s Pop
  { artist: "Beyoncé", title: "Dangerously in Love" },
  { artist: "OutKast", title: "Speakerboxxx/The Love Below" },
  { artist: "Justin Timberlake", title: "FutureSex/LoveSounds" },
  { artist: "Gwen Stefani", title: "Love. Angel. Music. Baby." },
  { artist: "Amy Winehouse", title: "Back to Black" },
  { artist: "Robyn", title: "Body Talk" },
  { artist: "Rihanna", title: "Good Girl Gone Bad" },
  { artist: "Rihanna", title: "Anti" },
  { artist: "Nelly Furtado", title: "Loose" },
  { artist: "Lily Allen", title: "Alright, Still" },
  { artist: "M.I.A.", title: "Kala" },
  { artist: "M.I.A.", title: "Arular" },
  // Art Pop / Indie Pop
  { artist: "Sufjan Stevens", title: "Carrie & Lowell" },
  { artist: "Sufjan Stevens", title: "Illinois" },
  { artist: "Vampire Weekend", title: "Modern Vampires of the City" },
  { artist: "Vampire Weekend", title: "Vampire Weekend" },
  { artist: "Grizzly Bear", title: "Veckatimest" },
  { artist: "Beach House", title: "Teen Dream" },
  { artist: "Beach House", title: "Depression Cherry" },
  { artist: "Fleet Foxes", title: "Fleet Foxes" },
  { artist: "Bon Iver", title: "For Emma, Forever Ago" },
  { artist: "Bon Iver", title: "22, A Million" },
  { artist: "St. Vincent", title: "St. Vincent" },
  { artist: "St. Vincent", title: "Actor" },
  { artist: "FKA twigs", title: "LP1" },
  { artist: "FKA twigs", title: "Magdalene" },
  { artist: "Perfume Genius", title: "No Shape" },
  // 2010s-2020s Pop
  { artist: "Lady Gaga", title: "The Fame Monster" },
  { artist: "Lady Gaga", title: "Born This Way" },
  { artist: "Lorde", title: "Pure Heroine" },
  { artist: "Lorde", title: "Melodrama" },
  { artist: "Carly Rae Jepsen", title: "Emotion" },
  { artist: "Taylor Swift", title: "1989" },
  { artist: "Taylor Swift", title: "Folklore" },
  { artist: "Taylor Swift", title: "Red" },
  { artist: "Adele", title: "21" },
  { artist: "Adele", title: "25" },
  { artist: "Ariana Grande", title: "Thank U, Next" },
  { artist: "Ariana Grande", title: "Sweetener" },
  { artist: "Dua Lipa", title: "Future Nostalgia" },
  { artist: "Billie Eilish", title: "When We All Fall Asleep, Where Do We Go?" },
  { artist: "Billie Eilish", title: "Happier Than Ever" },
  { artist: "Charli XCX", title: "Pop 2" },
  { artist: "Charli XCX", title: "How I'm Feeling Now" },
  { artist: "Charli XCX", title: "Brat" },
  { artist: "Olivia Rodrigo", title: "SOUR" },
  { artist: "Weyes Blood", title: "Titanic Rising" },
  { artist: "Caroline Polachek", title: "Pang" },
  { artist: "Magdalena Bay", title: "Mercurial World" },
  { artist: "Rina Sawayama", title: "Sawayama" },
  { artist: "Rosalía", title: "El Mal Querer" },
  { artist: "Rosalía", title: "Motomami" },
  { artist: "Bad Bunny", title: "Un Verano Sin Ti" },
  { artist: "Harry Styles", title: "Harry's House" },
  { artist: "Troye Sivan", title: "Something to Give Each Other" },
  { artist: "Mitski", title: "Puberty 2" },
  { artist: "Mitski", title: "Be the Cowboy" },
  // K-Pop / J-Pop
  { artist: "BTS", title: "Map of the Soul: 7" },
  { artist: "NewJeans", title: "NewJeans" },
  { artist: "Utada Hikaru", title: "First Love" },
  // Chamber Pop / Orchestral Pop
  { artist: "Scott Walker", title: "Scott 4" },
  { artist: "Rufus Wainwright", title: "Want One" },
  { artist: "The Divine Comedy", title: "Casanova" },
  { artist: "Haim", title: "Women in Music Pt. III" },
  { artist: "Phoebe Bridgers", title: "Punisher" },
  { artist: "boygenius", title: "the record" },
  { artist: "Chappell Roan", title: "The Rise and Fall of a Midwest Princess" },
  { artist: "Janelle Monáe", title: "The ArchAndroid" },
  { artist: "Lizzo", title: "Cuz I Love You" },
  { artist: "Kim Petras", title: "Feed the Beast" },
  { artist: "Christine and the Queens", title: "Chaleur Humaine" },
  { artist: "Robyn", title: "Robyn" },
  { artist: "The Weeknd", title: "Starboy" },
  { artist: "SZA", title: "Ctrl" },
  { artist: "Bruno Mars", title: "24K Magic" },
  { artist: "Lana Del Rey", title: "Norman Fucking Rockwell!" },
  { artist: "Lana Del Rey", title: "Born to Die" },
  { artist: "Sky Ferreira", title: "Night Time, My Time" },
  { artist: "Grimes", title: "Art Angels" },
  { artist: "Grimes", title: "Visions" },
  { artist: "The 1975", title: "A Brief Inquiry into Online Relationships" },
  { artist: "BROCKHAMPTON", title: "Saturation II" },
  { artist: "Glass Animals", title: "Dreamland" },
  { artist: "Tame Impala", title: "Currents" },
  { artist: "Jessie Ware", title: "What's Your Pleasure?" },
  { artist: "Raye", title: "My 21st Century Blues" },
  { artist: "Sabrina Carpenter", title: "Short n' Sweet" },
  { artist: "Clairo", title: "Sling" },
  { artist: "Japanese Breakfast", title: "Jubilee" },

  // --- Discovered via Last.fm ---
  { artist: "Natasha Bedingfield", title: "Unwritten" },
  { artist: "Natalie Imbruglia", title: "Left of the Middle" },
  { artist: "Madonna", title: "Like a Virgin" },
  { artist: "Jennifer Lopez", title: "LOVE?" },
  { artist: "Miley Cyrus", title: "The Time of Our Lives" },
  { artist: "Kelly Clarkson", title: "Stronger (Deluxe Version)" },
  { artist: "Madonna", title: "Hard Candy" },
  { artist: "Backstreet Boys", title: "Black & Blue" },
  { artist: "Fifth Harmony", title: "7/27 (Deluxe)" },
  { artist: "Take That", title: "Beautiful World" },
  { artist: "Adam Lambert", title: "For Your Entertainment" },
  { artist: "Backstreet Boys", title: "Backstreet Boys" },
  { artist: "Katy Perry", title: "Smile" },
  { artist: "Céline Dion", title: "Let's Talk About Love" },
  { artist: "Alizée", title: "Gourmandises" },
  { artist: "Ashley Tisdale", title: "Headstrong" },
  { artist: "Enrique Iglesias", title: "Escape" },
  { artist: "Taylor Swift", title: "1989 (Taylor's Version)" },
  { artist: "Sugababes", title: "Angels with Dirty Faces" },
  { artist: "Céline Dion", title: "A New Day Has Come" },
  { artist: "Michelle Branch", title: "The Spirit Room" },
  { artist: "Natasha Bedingfield", title: "Pocketful of Sunshine" },
  { artist: "Natalia Kills", title: "Trouble" },
  { artist: "Ace of Base", title: "Happy Nation" },
  { artist: "Sugababes", title: "Three" },
  { artist: "Maroon 5", title: "It Won't Be Soon Before Long." },
  { artist: "Gwen Stefani", title: "This Is What the Truth Feels Like" },
  { artist: "Daniel Powter", title: "Daniel Powter" },
  { artist: "Britney Spears", title: "Circus" },
  { artist: "Madonna", title: "Madonna" },
  { artist: "Lady Gaga", title: "The Cure" },
  { artist: "Cyndi Lauper", title: "True Colors" },
  { artist: "Ashley Tisdale", title: "Guilty Pleasure" },
  { artist: "The Corrs", title: "In Blue" },
  { artist: "Phillip Phillips", title: "The World from the Side of the Moon" },
  { artist: "Modern Talking", title: "Let's Talk About Love" },
  { artist: "Cher Lloyd", title: "Sticks & Stones" },
  { artist: "Take That", title: "The Circus" },
  { artist: "ABBA", title: "Waterloo" },
  { artist: "Annie Lennox", title: "Medusa" },
  { artist: "Tegan and Sara", title: "Heartthrob" },
  { artist: "James Morrison", title: "Undiscovered" },
  { artist: "Nelly Furtado", title: "Folklore" },
  { artist: "Anahí", title: "Mi Delirio" },
  { artist: "Christina Aguilera", title: "Christina Aguilera" },
  { artist: "Nena", title: "Nena" },
  { artist: "Lene Marlin", title: "Playing My Game" },
  { artist: "Belinda", title: "Carpe Diem" },
  { artist: "Ariana Grande", title: "No Tears Left to Cry" },
  { artist: "Carpenters", title: "Carpenters" },
  { artist: "Lady Gaga", title: "Just Dance" },
  { artist: "Anna Nalick", title: "Wreck of the Day" },
  { artist: "Lily Allen", title: "Alright, Still (Deluxe)" },
  { artist: "Reneé Rapp", title: "Snow Angel" },
  { artist: "Christopher Cross", title: "Christopher Cross" },
  { artist: "Céline Dion", title: "The Colour of My Love" },
  { artist: "Jão", title: "PIRATA" },
  { artist: "Britney Spears", title: "Oops!...I Did It Again" },
  { artist: "Girls Aloud", title: "Sound of the Underground" },
  { artist: "Red Velvet", title: "Rookie - The 4th Mini Album" },
  { artist: "One Direction", title: "Take Me Home: Yearbook Edition" },
  { artist: "Alessia Cara", title: "Know-It-All (Deluxe)" },
  { artist: "Atomic Kitten", title: "Feels So Good" },
  { artist: "Craig David", title: "Born to Do It" },
  { artist: "t.A.T.u.", title: "200 по встречной" },
  { artist: "Melanie Martinez", title: "Cry Baby" },
  { artist: "Texas", title: "The Hush" },
  { artist: "Angèle", title: "Nonante-cinq" },
  { artist: "Little Mix", title: "LM5 (Deluxe)" },
  { artist: "Mika", title: "The Boy Who Knew Too Much" },
  { artist: "Ava Max", title: "Heaven & Hell" },
  { artist: "Chappell Roan", title: "Good Luck, Babe!" },
  { artist: "Carly Rae Jepsen", title: "EMOTION Side B" },
  { artist: "ABBA", title: "ABBA Gold" },
  { artist: "Alexander Rybak", title: "Fairytales" },
  { artist: "Stacey Q", title: "Better than Heaven" },
  { artist: "Lewis Capaldi", title: "Divinely Uninspired to a Hellish Extent (Extended Edition)" },
  { artist: "Manu Gavassi", title: "Manu Gavassi" },
  { artist: "Hailee Steinfeld", title: "HAIZ" },
  { artist: "Shakira", title: "Pies Descalzos" },
  { artist: "Vanessa Hudgens", title: "V" },
  { artist: "Ashlee Simpson", title: "Bittersweet World" },
  { artist: "Niall Horan", title: "Flicker (Deluxe)" },
  { artist: "Wham!", title: "The Final" },
  { artist: "Victoria Beckham", title: "Victoria Beckham" },
  { artist: "Kylie Minogue", title: "Kiss Me Once" },
  { artist: "Ashlee Simpson", title: "I Am Me" },
  { artist: "Selena Gomez", title: "Bad Liar" },
  { artist: "Kris Allen", title: "Kris Allen" },
  { artist: "Delta Goodrem", title: "Innocent Eyes" },
  { artist: "King Dude", title: "Sex" },
  { artist: "Lenka", title: "Lenka" },
  { artist: "Las Ketchup", title: "Hijas Del Tomate" },
  { artist: "Britney Spears", title: "Femme Fatale" },
  { artist: "Marjorie Estiano", title: "Marjorie Estiano" },
  { artist: "Neon Trees", title: "Pop Psychology" },
  { artist: "Mike Patton", title: "Mondo cane" },
  { artist: "Maria Mena", title: "Apparently Unaffected" },
  { artist: "Haddaway", title: "The Album" },
  { artist: "Wilson Phillips", title: "Wilson Phillips" },
  { artist: "Jessica Simpson", title: "A Public Affair" },
  { artist: "Take That", title: "Progress" },
  { artist: "Jennifer Lopez", title: "Brave" },
  { artist: "Lights", title: "Siberia" },
  { artist: "Shakira", title: "She Wolf" },
  { artist: "Backstreet Boys", title: "This Is Us" },
  { artist: "Trevor Daniel", title: "Nicotine" },
  { artist: "Scouting for Girls", title: "Scouting for Girls" },
  { artist: "Geri Halliwell", title: "Schizophonic" },
  { artist: "Janet Jackson", title: "janet." },
  { artist: "Boa", title: "BoA" },
  { artist: "Sia", title: "Some People Have Real Problems" },
  { artist: "Robbie Williams", title: "Rudebox" },
  { artist: "Sandra", title: "The Long Play" },
  { artist: "F.R. David", title: "Words" },
  { artist: "Reik", title: "Reik" },
  { artist: "Lana Del Rey", title: "Born to Die (Bonus Track Version)" },
  { artist: "a-ha", title: "Foot Of The Mountain" },
  { artist: "Luísa Sonza", title: "Pandora" },
  { artist: "Miley Cyrus", title: "Something Beautiful" },
  { artist: "Hannah Montana", title: "Hannah Montana 2 / Meet Miley Cyrus" },
  { artist: "Nessa Barrett", title: "young forever" },
  { artist: "Tegan and Sara", title: "Love You to Death" },
  { artist: "Kim Carnes", title: "Mistaken Identity" },
  { artist: "Red Velvet", title: "The Red - The 1st Album" },
  { artist: "Jewel", title: "Pieces of You" },
  { artist: "Portugal. The Man", title: "Woodstock" },
  { artist: "Girls Aloud", title: "Out of Control" },
  { artist: "Nicola Roberts", title: "Cinderella's Eyes" },
  { artist: "La Bouche", title: "Sweet Dreams" },
  { artist: "Big Time Rush", title: "Elevate" },
  { artist: "Sara Bareilles", title: "The Blessed Unrest" },
  { artist: "Karmin", title: "Pulses" },
  { artist: "Franco Battiato", title: "La voce del padrone" },
  { artist: "Bee Gees", title: "Number Ones" },
  { artist: "Lea Michele", title: "Louder" },
  { artist: "Christina Aguilera", title: "Liberation" },
  { artist: "Wham!", title: "Fantastic" },
  { artist: "a-ha", title: "Scoundrel Days" },
  { artist: "Enrique Iglesias", title: "Enrique" },
  { artist: "Marisa Monte", title: "Infinito Particular" },
  { artist: "Elvis Presley", title: "ELV1S: 30 #1 Hits" },
  { artist: "Christina Perri", title: "Head or Heart" },
  { artist: "Laura Pausini", title: "Laura Pausini" },
  { artist: "Alphabeat", title: "This Is Alphabeat" },
  { artist: "Michelle Branch", title: "Hotel Paper" },
  { artist: "One Direction", title: "What Makes You Beautiful" },
  { artist: "Mylène Farmer", title: "Innamoramento" },
  { artist: "Simply Red", title: "Stars" },
  { artist: "Alexander Rybak", title: "Fairytale" },
  { artist: "Colbie Caillat", title: "Breakthrough" },
  { artist: "Jennifer Lopez", title: "On the Floor" },
  { artist: "Hanson", title: "This Time Around" },
  { artist: "Karmin", title: "Hello" },
  { artist: "Missy Higgins", title: "The Sound of White" },
  { artist: "Cher", title: "Dancing Queen" },
  { artist: "Harry Styles", title: "Sign of the Times" },
  { artist: "Jack Stauber", title: "Pop Food" },
  { artist: "Rufus Wainwright", title: "Release The Stars" },
  { artist: "Erasure", title: "Pop! The First 20 Hits" },
  { artist: "Lena", title: "My Cassette Player" },
  { artist: "YOASOBI", title: "THE BOOK" },
  { artist: "Passion Pit", title: "Gossamer" },
  { artist: "Utada", title: "This Is The One" },
  { artist: "The Saturdays", title: "Chasing Lights" },
  { artist: "Katy Perry", title: "Part of Me" },
  { artist: "Backstreet Boys", title: "Unbreakable" },
  { artist: "Studio Killers", title: "Studio Killers" },
  { artist: "La Oreja de Van Gogh", title: "Guapa" },
  { artist: "Black", title: "Wonderful Life" },
  { artist: "TWICE", title: "Feel Special" },
  { artist: "Kylie Minogue", title: "Ultimate Kylie" },
  { artist: "Miley Cyrus", title: "Meet Miley Cyrus" },
  { artist: "Roxette", title: "The Ballad Hits" },
  { artist: "Jessica Simpson", title: "Sweet Kisses" },
  { artist: "The Walker Brothers", title: "Nite Flights" },
  { artist: "Laura Pausini", title: "Tra te e il mare" },
  { artist: "Eli", title: "stage girl" },
  { artist: "Fefe Dobson", title: "Joy" },
  { artist: "September", title: "In Orbit" },
  { artist: "Silbermond", title: "Nichts Passiert" },
  { artist: "Dua Lipa", title: "Radical Optimism (Extended Versions)" },
  { artist: "Debbie Gibson", title: "Out of the Blue" },
  { artist: "Tokio Hotel", title: "Kings of Suburbia" },
  { artist: "KT Tunstall", title: "Drastic Fantastic" },
  { artist: "JLS", title: "JLS" },
  { artist: "Allison Iraheta", title: "Just Like You" },
  { artist: "Boys Like Girls", title: "Love Drunk" },
  { artist: "Cinema Bizarre", title: "Final Attraction" },
  { artist: "Mimi Webb", title: "Amelia" },
  { artist: "Carly Rae Jepsen", title: "Dedicated Side B" },
  { artist: "Kylie Minogue", title: "Disco (Deluxe)" },
  { artist: "ZAYN", title: "Mind of Mine" },
  { artist: "Céline Dion", title: "One Heart" },
  { artist: "P!nk", title: "Trustfall" },
  { artist: "Katy Perry", title: "Never Really Over" },
  { artist: "One Direction", title: "Take Me Home" },
  { artist: "ABBA", title: "The Visitors" },
  { artist: "Cymbals", title: "Love You" },
  { artist: "Paula Abdul", title: "Spellbound" },
  { artist: "Aly & AJ", title: "Into the Rush" },
  { artist: "Kylie Minogue", title: "Kiss Me Once (Special Edition)" },
  { artist: "Mitski", title: "LUSH" },
  { artist: "The Saturdays", title: "Wordshaker" },
  { artist: "AJR", title: "Living Room" },
  { artist: "Kerli", title: "Utopia" },
  { artist: "Girls Aloud", title: "Tangled Up" },
  { artist: "Винтаж", title: "Sex" },
  { artist: "Kate Ryan", title: "Free" },
  { artist: "Lianne La Havas", title: "Blood" },
  { artist: "Sandy e Junior", title: "Identidade" },
  { artist: "Panjabi MC", title: "The Album" },
  { artist: "Robbie Williams", title: "Reality Killed the Video Star" },
  { artist: "Britney Spears", title: "Britney Jean" },
  { artist: "Madonna", title: "The Confessions Tour" },
  { artist: "Rachel Stevens", title: "Funky Dory" },
  { artist: "69 Danguje", title: "69 DANGUJE" },
  { artist: "One Direction", title: "Midnight Memories" },
  { artist: "The Aces", title: "When My Heart Felt Volcanic" },
  { artist: "Britney Spears", title: "Baby One More Time" },
  { artist: "Janet Jackson", title: "20 Y.O." },
  { artist: "XTC", title: "Skylarking" },
  { artist: "Cassandra Steen", title: "Darum leben wir" },
  { artist: "Carly Rae Jepsen", title: "E•MO•TION" },
  { artist: "Feargal Sharkey", title: "Feargal Sharkey" },
  { artist: "Sandy", title: "Meu Canto - EP" },
  { artist: "The Blue Nile", title: "Hats" },
  { artist: "Bratz", title: "Rock Angelz" },
  { artist: "Rina Sawayama", title: "Cherry" },
  { artist: "Kylie Minogue", title: "The Abbey Road Sessions" },
  { artist: "Anahí", title: "Inesperado" },
  { artist: "Jesse McCartney", title: "Right Where You Want Me" },
  { artist: "Perfume Genius", title: "Set My Heart on Fire Immediately" },
  { artist: "Britney Spears", title: "3" },
  { artist: "Katy Perry", title: "Roar" },
  { artist: "Kate Nash", title: "Made of Bricks" },
  { artist: "Aurora", title: "A Different Kind of Human – Step 2" },
  { artist: "Labi Siffre", title: "Crying Laughing Loving Lying" },
  { artist: "Belinda", title: "Utopia" },
  { artist: "Cyndi Lauper", title: "Bring Ya to the Brink" },
  { artist: "Maria Mena", title: "Cause and Effect" },
  { artist: "Jessica Simpson", title: "Irresistible" },
  { artist: "Kim Wilde", title: "Another Step" },
  { artist: "Veronica Maggio", title: "Handen i fickan fast jag bryr mig" },
  { artist: "Sarah McLachlan", title: "Fumbling Towards Ecstasy" },
  { artist: "Troye Sivan", title: "TRXYE" },
  { artist: "Echt", title: "Freischwimmer" },
  { artist: "Take That", title: "Nobody Else" },
  { artist: "Bruno Mars", title: "The Grenade Sessions" },
  { artist: "Kelly Key", title: "Kelly Key" },
];
