export const rbSoul: Array<{ artist: string; title: string }> = [
  // Classic Soul / Motown
  { artist: "Marvin Gaye", title: "What's Going On" },
  { artist: "Marvin Gaye", title: "Let's Get It On" },
  { artist: "Marvin Gaye", title: "I Want You" },
  { artist: "Marvin Gaye", title: "Here, My Dear" },
  { artist: "Stevie Wonder", title: "Songs in the Key of Life" },
  { artist: "Stevie Wonder", title: "Innervisions" },
  { artist: "Stevie Wonder", title: "Talking Book" },
  { artist: "Stevie Wonder", title: "Music of My Mind" },
  { artist: "Aretha Franklin", title: "I Never Loved a Man the Way I Love You" },
  { artist: "Aretha Franklin", title: "Lady Soul" },
  { artist: "Aretha Franklin", title: "Young, Gifted and Black" },
  { artist: "Otis Redding", title: "Otis Blue: Otis Redding Sings Soul" },
  { artist: "Otis Redding", title: "The Dock of the Bay" },
  { artist: "Sam Cooke", title: "Live at the Harlem Square Club, 1963" },
  { artist: "Sam Cooke", title: "Night Beat" },
  { artist: "Ray Charles", title: "Modern Sounds in Country and Western Music" },
  { artist: "Ray Charles", title: "The Genius of Ray Charles" },
  { artist: "The Temptations", title: "Cloud Nine" },
  { artist: "The Supremes", title: "Where Did Our Love Go" },
  { artist: "Smokey Robinson & The Miracles", title: "Going to a Go-Go" },
  { artist: "The Four Tops", title: "Reach Out" },
  { artist: "The Isley Brothers", title: "3 + 3" },
  { artist: "Curtis Mayfield", title: "Superfly" },
  { artist: "Curtis Mayfield", title: "Curtis" },
  { artist: "Al Green", title: "Let's Stay Together" },
  { artist: "Al Green", title: "Call Me" },
  { artist: "Al Green", title: "I'm Still in Love with You" },
  { artist: "Bill Withers", title: "Still Bill" },
  { artist: "Bill Withers", title: "Just as I Am" },
  { artist: "Donny Hathaway", title: "Live" },
  { artist: "Donny Hathaway", title: "Everything Is Everything" },
  { artist: "Bobby Womack", title: "Understanding" },
  { artist: "Isaac Hayes", title: "Hot Buttered Soul" },
  { artist: "Isaac Hayes", title: "Shaft" },
  { artist: "Gil Scott-Heron", title: "Pieces of a Man" },
  { artist: "Nina Simone", title: "I Put a Spell on You" },
  // Funk
  { artist: "James Brown", title: "Live at the Apollo" },
  { artist: "James Brown", title: "Star Time" },
  { artist: "Sly & The Family Stone", title: "There's a Riot Goin' On" },
  { artist: "Sly & The Family Stone", title: "Stand!" },
  { artist: "Parliament", title: "Mothership Connection" },
  { artist: "Funkadelic", title: "Maggot Brain" },
  { artist: "Funkadelic", title: "One Nation Under a Groove" },
  { artist: "Earth, Wind & Fire", title: "That's the Way of the World" },
  { artist: "Earth, Wind & Fire", title: "All 'N All" },
  { artist: "The Meters", title: "Rejuvenation" },
  { artist: "War", title: "The World Is a Ghetto" },
  { artist: "Tower of Power", title: "Tower of Power" },
  { artist: "Chaka Khan", title: "Chaka" },
  { artist: "Rick James", title: "Street Songs" },
  { artist: "Bootsy Collins", title: "Ahh...The Name Is Bootsy, Baby!" },
  // Disco
  { artist: "Donna Summer", title: "Bad Girls" },
  { artist: "Donna Summer", title: "I Remember Yesterday" },
  { artist: "Chic", title: "Risqué" },
  { artist: "Chic", title: "C'est Chic" },
  { artist: "Sister Sledge", title: "We Are Family" },
  { artist: "Gloria Gaynor", title: "Love Tracks" },
  // 80s R&B
  { artist: "Prince", title: "Purple Rain" },
  { artist: "Prince", title: "Sign o' the Times" },
  { artist: "Prince", title: "1999" },
  { artist: "Prince", title: "Dirty Mind" },
  { artist: "Michael Jackson", title: "Thriller" },
  { artist: "Michael Jackson", title: "Off the Wall" },
  { artist: "Michael Jackson", title: "Bad" },
  { artist: "Whitney Houston", title: "Whitney Houston" },
  { artist: "Whitney Houston", title: "Whitney" },
  { artist: "Luther Vandross", title: "Never Too Much" },
  { artist: "Anita Baker", title: "Rapture" },
  { artist: "Sade", title: "Diamond Life" },
  { artist: "Sade", title: "Love Deluxe" },
  { artist: "Janet Jackson", title: "Rhythm Nation 1814" },
  { artist: "Janet Jackson", title: "Control" },
  { artist: "Janet Jackson", title: "The Velvet Rope" },
  { artist: "Teena Marie", title: "Wild and Peaceful" },
  { artist: "Alexander O'Neal", title: "Hearsay" },
  // 90s R&B
  { artist: "TLC", title: "CrazySexyCool" },
  { artist: "Mary J. Blige", title: "My Life" },
  { artist: "Mary J. Blige", title: "What's the 411?" },
  { artist: "R. Kelly", title: "12 Play" },
  { artist: "Toni Braxton", title: "Toni Braxton" },
  { artist: "Aaliyah", title: "One in a Million" },
  { artist: "Aaliyah", title: "Aaliyah" },
  { artist: "Brandy", title: "Never Say Never" },
  { artist: "Destiny's Child", title: "The Writing's on the Wall" },
  { artist: "Boyz II Men", title: "II" },
  { artist: "Jodeci", title: "Diary of a Mad Band" },
  { artist: "Maxwell", title: "Maxwell's Urban Hang Suite" },
  // Neo-Soul
  { artist: "D'Angelo", title: "Voodoo" },
  { artist: "D'Angelo", title: "Brown Sugar" },
  { artist: "D'Angelo and The Vanguard", title: "Black Messiah" },
  { artist: "Erykah Badu", title: "Baduizm" },
  { artist: "Erykah Badu", title: "Mama's Gun" },
  { artist: "Erykah Badu", title: "New Amerykah Part One (4th World War)" },
  { artist: "Lauryn Hill", title: "The Miseducation of Lauryn Hill" },
  { artist: "Jill Scott", title: "Who Is Jill Scott? Words and Sounds Vol. 1" },
  { artist: "India.Arie", title: "Acoustic Soul" },
  { artist: "Musiq Soulchild", title: "Aijuswanaseing" },
  { artist: "Anthony Hamilton", title: "Comin' from Where I'm From" },
  // 2000s R&B
  { artist: "Beyoncé", title: "Lemonade" },
  { artist: "Beyoncé", title: "Beyoncé" },
  { artist: "Beyoncé", title: "Renaissance" },
  { artist: "Beyoncé", title: "B'Day" },
  { artist: "Usher", title: "Confessions" },
  { artist: "Alicia Keys", title: "Songs in A Minor" },
  { artist: "Amy Winehouse", title: "Back to Black" },
  { artist: "Janelle Monáe", title: "The ArchAndroid" },
  { artist: "Janelle Monáe", title: "Dirty Computer" },
  // 2010s-2020s R&B
  { artist: "Frank Ocean", title: "Blonde" },
  { artist: "Frank Ocean", title: "Channel Orange" },
  { artist: "The Weeknd", title: "House of Balloons" },
  { artist: "The Weeknd", title: "After Hours" },
  { artist: "SZA", title: "Ctrl" },
  { artist: "SZA", title: "SOS" },
  { artist: "Solange", title: "A Seat at the Table" },
  { artist: "Blood Orange", title: "Negro Swan" },
  { artist: "Blood Orange", title: "Freetown Sound" },
  { artist: "Anderson .Paak", title: "Malibu" },
  { artist: "Anderson .Paak", title: "Ventura" },
  { artist: "H.E.R.", title: "H.E.R." },
  { artist: "Summer Walker", title: "Over It" },
  { artist: "Jazmine Sullivan", title: "Heaux Tales" },
  { artist: "Ravyn Lenae", title: "Hypnos" },
  { artist: "Steve Lacy", title: "Gemini Rights" },
  { artist: "Daniel Caesar", title: "Freudian" },
  { artist: "Giveon", title: "Give or Take" },
  { artist: "Lucky Daye", title: "Painted" },
  { artist: "Snoh Aalegra", title: "Ugh, those feels again" },
  { artist: "Silk Sonic", title: "An Evening with Silk Sonic" },
  { artist: "Victoria Monét", title: "Jaguar" },
  // Gospel
  { artist: "Mahalia Jackson", title: "The World's Greatest Gospel Singer" },
  { artist: "The Staple Singers", title: "Be Altitude: Respect Yourself" },
  { artist: "Kirk Franklin", title: "The Nu Nation Project" },
  // International R&B/Soul
  { artist: "Fela Kuti", title: "Zombie" },
  { artist: "Fela Kuti", title: "Expensive Shit" },
  { artist: "Mulatu Astatke", title: "Mulatu of Ethiopia" },
  { artist: "Cesária Évora", title: "Miss Perfumado" },
  { artist: "Angélique Kidjo", title: "Logozo" },
  { artist: "Roberta Flack", title: "First Take" },
  { artist: "Teddy Pendergrass", title: "Teddy Pendergrass" },
  { artist: "The O'Jays", title: "Back Stabbers" },
  { artist: "Harold Melvin & the Blue Notes", title: "I Miss You" },
  { artist: "Minnie Riperton", title: "Perfect Angel" },
  { artist: "Phyllis Hyman", title: "Goddess of Love" },
  { artist: "Teena Marie", title: "Starchild" },
  { artist: "Keith Sweat", title: "Make It Last Forever" },
  { artist: "New Edition", title: "Heart Break" },
  { artist: "En Vogue", title: "Funky Divas" },
  { artist: "Xscape", title: "Off the Hook" },
  { artist: "112", title: "Room 112" },
  { artist: "Ciara", title: "Goodies" },

  // --- Discovered via Last.fm ---
  { artist: "Minnie Riperton", title: "Come to My Garden" },
  { artist: "Sade", title: "Lovers Rock" },
  { artist: "Sam Cooke", title: "Mr. Soul" },
  { artist: "Destiny's Child", title: "Destiny Fulfilled" },
  { artist: "Charles Bradley", title: "No Time for Dreaming" },
  { artist: "Adele", title: "Skyfall" },
  { artist: "Brenton Wood", title: "Oogum Boogum" },
  { artist: "Roberta Flack", title: "Killing Me Softly" },
  { artist: "Ann Peebles", title: "I Can't Stand The Rain" },
  { artist: "Earth, Wind & Fire", title: "I Am" },
  { artist: "Curtis Mayfield", title: "There's No Place Like America Today" },
  { artist: "Michael Jackson", title: "Got To Be There" },
  { artist: "Wilson Pickett", title: "The Exciting Wilson Pickett" },
  { artist: "Jazmine Sullivan", title: "Fearless" },
  { artist: "Macy Gray", title: "On How Life Is" },
  { artist: "Diana Ross", title: "Diana" },
  { artist: "Barry White", title: "I've Got So Much To Give" },
  { artist: "Black Pumas", title: "Black Pumas" },
  { artist: "Stevie Wonder", title: "Hotter Than July" },
  { artist: "Aloe Blacc", title: "Lift Your Spirit" },
  { artist: "Stevie Wonder", title: "Fulfillingness' First Finale" },
  { artist: "Sam & Dave", title: "Hold on, I'm Comin'" },
  { artist: "James Carr", title: "You Got My Mind Messed Up" },
  { artist: "SWV", title: "It's About Time" },
  { artist: "Alicia Keys", title: "As I Am" },
  { artist: "Joss Stone", title: "The Soul Sessions" },
  { artist: "Donny Hathaway", title: "Extension of a Man" },
  { artist: "Camille Yarbrough", title: "The Iron Pot Cooker" },
  { artist: "The Jacksons", title: "Triumph" },
  { artist: "The Temptations", title: "The Temptations Sing Smokey" },
  { artist: "Fitz and the Tantrums", title: "Pickin' Up the Pieces" },
  { artist: "Shuggie Otis", title: "Inspiration Information" },
  { artist: "The Isley Brothers", title: "3+3" },
  { artist: "Allen Toussaint", title: "Southern Nights" },
  { artist: "Ohio Players", title: "Honey" },
  { artist: "Kehlani", title: "SweetSexySavage (Deluxe)" },
  { artist: "Eddie Holman", title: "I Love You" },
  { artist: "Irma Thomas", title: "Wish Someone Would Care" },
  { artist: "Leon Bridges", title: "Coming Home" },
  { artist: "Paloma Faith", title: "Do You Want the Truth or Something Beautiful?" },
  { artist: "Plan B", title: "The Defamation of Strickland Banks" },
  { artist: "Jennifer Hudson", title: "Jennifer Hudson" },
  { artist: "Lionel Richie", title: "Can't Slow Down" },
  { artist: "Stevie Wonder", title: "For Once in My Life" },
  { artist: "D'Angelo", title: "Black Messiah" },
  { artist: "Chrisette Michele", title: "Epiphany" },
  { artist: "Stevie Wonder", title: "My Cherie Amour" },
  { artist: "Michael Jackson", title: "Forever, Michael" },
  { artist: "Stevie Wonder", title: "In Square Circle" },
  { artist: "Jerry Butler", title: "The Ice Man Cometh" },
  { artist: "Michael Kiwanuka", title: "Home Again" },
  { artist: "Prince", title: "For You" },
  { artist: "SWV", title: "New Beginning" },
  { artist: "Darondo", title: "Let My People Go" },
  { artist: "The Temptations", title: "Gettin' Ready" },
  { artist: "Terry Callier", title: "Occasional Rain" },
  { artist: "Seal", title: "Seal" },
  { artist: "Merry Clayton", title: "Merry Clayton" },
  { artist: "Solomon Burke", title: "Don't Give Up on Me" },
  { artist: "Jamie Woon", title: "Mirrorwriting" },
  { artist: "Smokey Robinson", title: "A Quiet Storm" },
  { artist: "Alexander O'Neal", title: "Alexander O'Neal" },
  { artist: "Amel Larrieux", title: "Infinite Possibilities" },
  { artist: "India.Arie", title: "Voyage To India" },
  { artist: "The Emotions", title: "Rejoice" },
  { artist: "The Isley Brothers", title: "Go For Your Guns" },
  { artist: "Seal", title: "Soul" },
  { artist: "Little Beaver", title: "Party Down" },
  { artist: "Res", title: "How I Do" },
  { artist: "Esther Phillips", title: "From a Whisper to a Scream" },
  { artist: "Brownstone", title: "From The Bottom Up" },
  { artist: "Mariah the Scientist", title: "MASTER" },
  { artist: "Aretha Franklin", title: "Spirit in the Dark" },
  { artist: "Stevie Wonder", title: "Journey Through the Secret Life of Plants" },
  { artist: "Joss Stone", title: "Colour Me Free" },
  { artist: "Prince", title: "Musicology" },
  { artist: "Anastacia", title: "Pieces of a Dream" },
  { artist: "Michael Jackson", title: "Music & Me" },
  { artist: "Anthony Hamilton", title: "Ain't Nobody Worryin'" },
  { artist: "Jessie Ware", title: "Devotion" },
  { artist: "War", title: "Why Can't We Be Friends?" },
  { artist: "Gil Scott-Heron", title: "Reflections" },
  { artist: "Prince", title: "3121" },
  { artist: "Kehlani", title: "It Was Good Until It Wasn't" },
  { artist: "Babyface", title: "For the Cool in You" },
  { artist: "Stevie Wonder", title: "I Was Made to Love Her" },
  { artist: "Otis Redding", title: "The Great Otis Redding Sings Soul Ballads" },
  { artist: "Betty Davis", title: "Betty Davis" },
  { artist: "Natalie Cole", title: "Good to Be Back" },
  { artist: "Kali Uchis", title: "Por Vida" },
  { artist: "Lianne La Havas", title: "Lianne La Havas" },
  { artist: "Emeli Sandé", title: "Our Version of Events" },
  { artist: "Blu Cantrell", title: "So Blu" },
  { artist: "Ben E. King", title: "Don't Play That Song" },
  { artist: "Lee Fields & The Expressions", title: "My World" },
  { artist: "LADIES' CODE", title: "STRANG3R" },
  { artist: "Stevie Wonder", title: "Where I'm Coming From" },
  { artist: "Maxwell", title: "Embrya" },
  { artist: "Raphael Saadiq", title: "Stone Rollin'" },
  { artist: "Corinne Bailey Rae", title: "The Sea" },
  { artist: "Roberta Flack", title: "Feel Like Makin' Love" },
  { artist: "Bobby Womack", title: "Fly Me To The Moon" },
  { artist: "Belleruche", title: "The Express" },
  { artist: "The Temptations", title: "Masterpiece" },
  { artist: "Bill Withers", title: "'Justments" },
  { artist: "Oceana", title: "Love Supply" },
  { artist: "Maroon 5", title: "Hands All Over" },
  { artist: "Hot Chocolate", title: "Hot Chocolate" },
  { artist: "Jill Scott", title: "Beautifully Human: Words and Sounds Vol. 2" },
  { artist: "Jazmine Sullivan", title: "Love Me Back" },
  { artist: "Labelle", title: "Nightbirds" },
  { artist: "Incognito", title: "Positivity" },
  { artist: "Paulina Rubio", title: "La Chica Dorada" },
  { artist: "Beyoncé", title: "HOMECOMING: THE LIVE ALBUM" },
  { artist: "Summer Walker", title: "Last Day of Summer" },
  { artist: "Mariah Carey", title: "Butterfly" },
  { artist: "Eddie Floyd", title: "Knock On Wood" },
  { artist: "Mayer Hawthorne", title: "A Strange Arrangement" },
  { artist: "The Isley Brothers", title: "The Heat Is On" },
  { artist: "Sam Cooke", title: "Portrait of a Legend 1951-1964" },
  { artist: "Eliza Doolittle", title: "Eliza Doolittle" },
  { artist: "The Temptations", title: "All Directions" },
  { artist: "Ben l'Oncle Soul", title: "Ben L'Oncle Soul" },
  { artist: "The Neville Brothers", title: "Yellow Moon" },
  { artist: "The Temptations", title: "Sky's The Limit" },
  { artist: "Remy Shand", title: "The Way I Feel" },
  { artist: "Curtis Mayfield", title: "Back to the World" },
  { artist: "Seal", title: "Seal IV" },
  { artist: "Edwin Starr", title: "25 Miles" },
  { artist: "Tevin Campbell", title: "I'm Ready" },
  { artist: "112", title: "Part III" },
  { artist: "Bobby Womack", title: "My Prescription" },
  { artist: "The Delfonics", title: "La La Means I Love You" },
  { artist: "The Impressions", title: "Keep on Pushing" },
  { artist: "Marvin Gaye", title: "Trouble Man" },
  { artist: "Syreeta", title: "Syreeta" },
  { artist: "Ohio Players", title: "Skin Tight" },
  { artist: "DeBarge", title: "In A Special Way" },
  { artist: "The Stylistics", title: "The Stylistics" },
  { artist: "Sam Cooke", title: "The Man and His Music" },
  { artist: "Anthony Hamilton", title: "The Point Of It All" },
  { artist: "Isaac Hayes", title: "Black Moses" },
  { artist: "Ruby Johnson", title: "I'll Run Your Hurt Away" },
  { artist: "Soul II Soul", title: "Keep On Movin'" },
  { artist: "Red Velvet", title: "‘The ReVe Festival’ Day 2" },
  { artist: "Dionne Warwick", title: "Here I Am" },
  { artist: "Terence Trent D'Arby", title: "Introducing The Hardline According To Terence Trent D'Arby" },
  { artist: "Cymande", title: "Cymande" },
  { artist: "Karyn White", title: "Ritual Of Love" },
  { artist: "The Delfonics", title: "The Delfonics" },
  { artist: "Snoh Aalegra", title: "- Ugh, those feels again" },
  { artist: "Wilson Pickett", title: "The Wicked Pickett" },
  { artist: "Solange", title: "Sol-Angel and the Hadley St. Dreams (Deluxe)" },
  { artist: "Chrisette Michele", title: "I Am" },
  { artist: "Dionne Warwick", title: "Presenting Dionne Warwick" },
  { artist: "Ann Peebles", title: "Straight From The Heart" },
  { artist: "Ace Spectrum", title: "Inner Spectrum" },
  { artist: "The Dramatics", title: "Whatcha See Is Whatcha Get" },
  { artist: "Mary J. Blige", title: "Stronger withEach Tear" },
  { artist: "Diana Ross", title: "Diana Ross" },
  { artist: "Simply Red", title: "Home" },
  { artist: "Silk", title: "Tonight" },
  { artist: "Regina Belle", title: "Stay With Me" },
  { artist: "Leon Bridges", title: "Good Thing" },
  { artist: "The Jacksons", title: "The Jacksons" },
  { artist: "Al Green", title: "Full of Fire" },
  { artist: "Stevie Wonder", title: "Down to Earth" },
  { artist: "Aretha Franklin", title: "Respect" },
  { artist: "The Impressions", title: "This Is My Country" },
  { artist: "Brian McKnight", title: "Brian McKnight" },
  { artist: "Merry Clayton", title: "Gimme Shelter" },
  { artist: "Barry White", title: "Stone Gon'" },
  { artist: "Mavis Staples", title: "We'll Never Turn Back" },
  { artist: "Hozier", title: "Hozier (Expanded Edition)" },
  { artist: "The Supremes", title: "More Hits by The Supremes" },
  { artist: "Heatwave", title: "Too Hot To Handle" },
  { artist: "James Brown", title: "Sex Machine" },
  { artist: "Curtis Mayfield", title: "Roots" },
  { artist: "Ohio Players", title: "Pleasure" },
  { artist: "Chaka Khan", title: "Funk This" },
  { artist: "Fontella Bass", title: "The New Look" },
  { artist: "Tank", title: "Now or Never" },
  { artist: "Raw Soul Express", title: "Raw Soul Express" },
  { artist: "The Stylistics", title: "Round 2" },
  { artist: "Isaac Hayes", title: "Joy" },
  { artist: "Essosa", title: "Waste My Time" },
  { artist: "Dwele", title: "Sketches Of A Man" },
  { artist: "Beyoncé", title: "I Am... Sasha Fierce" },
  { artist: "Billy Paul", title: "360 Degrees of Billy Paul" },
  { artist: "Kwabs", title: "Love + War" },
  { artist: "Roberto Carlos", title: "Roberto Carlos (1971 Remasterizado)" },
  { artist: "Ayo", title: "Joyful" },
  { artist: "Ohio Players", title: "Gold" },
  { artist: "The Budos Band", title: "The Budos Band III" },
  { artist: "Nneka", title: "Victim Of Truth" },
  { artist: "Lenny Kravitz", title: "Raise Vibration" },
  { artist: "Van Hunt", title: "Van Hunt" },
  { artist: "Keyshia Cole", title: "Just Like You" },
  { artist: "Aretha Franklin", title: "Aretha Arrives" },
  { artist: "Cleo Sol", title: "Rose in the Dark" },
  { artist: "Tank", title: "SAVAGE" },
  { artist: "Ray LaMontagne", title: "Gossip in the Grain" },
  { artist: "Justin Timberlake", title: "The 20/20 Experience" },
  { artist: "Sly & The Family Stone", title: "Stand" },
  { artist: "Gabrielle", title: "Find Your Way" },
  { artist: "Minnie Riperton", title: "Perfect Angel / Adventures in Paradise" },
  { artist: "Jamie Lidell", title: "Multiply" },
  { artist: "Jodeci", title: "The Show, The After Party, The Hotel" },
  { artist: "Randy Crawford", title: "Secret Combination" },
  { artist: "Robin Thicke", title: "Something Else" },
  { artist: "Crush", title: "Crush on You" },
  { artist: "Kool & the Gang", title: "Something Special" },
  { artist: "Marvin Gaye", title: "Every Great Motown Hit of Marvin Gaye" },
  { artist: "Kendra Morris", title: "Banshee" },
  { artist: "Jackie Ross", title: "Full Bloom" },
  { artist: "Van Morrison", title: "Hard Nose the Highway" },
  { artist: "Alice Smith", title: "For Lovers, Dreamers & Me" },
  { artist: "Next", title: "Rated Next" },
  { artist: "James Brown", title: "Get On The Good Foot" },
  { artist: "Jamie Lidell", title: "Jim" },
  { artist: "Stephanie Mills", title: "Gold" },
  { artist: "Gil Scott-Heron", title: "The Revolution Will Not Be Televised" },
  { artist: "Duffy", title: "Endlessly" },
  { artist: "LADIES' CODE", title: "MYST3RY" },
  { artist: "Syreeta", title: "Stevie Wonder Presents Syreeta" },
  { artist: "Donna Summer", title: "A Love Trilogy" },
  { artist: "Whitney Houston", title: "I Wish You Love: More From the Bodyguard" },
  { artist: "New Edition", title: "Candy Girl" },
  { artist: "Marvin Gaye & Tammi Terrell", title: "United" },
  { artist: "Bobby Caldwell", title: "Cat in the Hat" },
  { artist: "Paolo Nutini", title: "Sunny Side Up" },
  { artist: "Detroit Emeralds", title: "You Want It, You Got It" },
  { artist: "Jackson Sisters", title: "Jackson Sisters" },
  { artist: "Alice Russell", title: "Pot Of Gold" },
  { artist: "Donna Summer", title: "Once Upon a Time" },
  { artist: "Prince", title: "Planet Earth" },
  { artist: "The Isley Brothers", title: "Harvest For The World" },
  { artist: "Charles Bradley", title: "Victim of Love" },
  { artist: "Harold Melvin & The Blue Notes", title: "Harold Melvin & The Blue Notes" },
  { artist: "Anastacia", title: "Not That Kind" },
  { artist: "DeBarge", title: "All This Love" },
  { artist: "Arthur Conley", title: "Sweet Soul Music" },
  { artist: "George Michael", title: "Patience" },
  { artist: "Floetry", title: "Flo'Ology" },
  { artist: "The Supremes", title: "Gold" },
  { artist: "Aretha Franklin", title: "Soul '69" },
  { artist: "Syl Johnson", title: "Back for a Taste of Your Love" },
  { artist: "Anita Ward", title: "Ring My Bell" },
  { artist: "William Bell", title: "The Soul Of A Bell" },
  { artist: "Rag'n'Bone Man", title: "Human (Deluxe)" },
];
