export const rock: Array<{ artist: string; title: string }> = [
  // Classic Rock / 60s-70s
  { artist: "The Beatles", title: "Abbey Road" },
  { artist: "The Beatles", title: "Revolver" },
  { artist: "The Beatles", title: "Sgt. Pepper's Lonely Hearts Club Band" },
  { artist: "The Beatles", title: "The White Album" },
  { artist: "The Beatles", title: "Rubber Soul" },
  { artist: "Led Zeppelin", title: "Led Zeppelin IV" },
  { artist: "Led Zeppelin", title: "Physical Graffiti" },
  { artist: "Led Zeppelin", title: "Houses of the Holy" },
  { artist: "Pink Floyd", title: "The Dark Side of the Moon" },
  { artist: "Pink Floyd", title: "Wish You Were Here" },
  { artist: "Pink Floyd", title: "The Wall" },
  { artist: "The Rolling Stones", title: "Exile on Main St." },
  { artist: "The Rolling Stones", title: "Let It Bleed" },
  { artist: "The Rolling Stones", title: "Sticky Fingers" },
  { artist: "The Who", title: "Who's Next" },
  { artist: "The Who", title: "Tommy" },
  { artist: "Jimi Hendrix", title: "Are You Experienced" },
  { artist: "Jimi Hendrix", title: "Electric Ladyland" },
  { artist: "The Doors", title: "The Doors" },
  { artist: "The Velvet Underground", title: "The Velvet Underground & Nico" },
  { artist: "David Bowie", title: "The Rise and Fall of Ziggy Stardust and the Spiders From Mars" },
  { artist: "David Bowie", title: "Low" },
  { artist: "David Bowie", title: "Heroes" },
  { artist: "David Bowie", title: "Station to Station" },
  { artist: "King Crimson", title: "In the Court of the Crimson King" },
  { artist: "Yes", title: "Close to the Edge" },
  { artist: "Genesis", title: "The Lamb Lies Down on Broadway" },
  { artist: "Cream", title: "Disraeli Gears" },
  { artist: "The Kinks", title: "The Kinks Are the Village Green Preservation Society" },
  { artist: "The Band", title: "Music from Big Pink" },
  { artist: "Creedence Clearwater Revival", title: "Cosmo's Factory" },
  { artist: "Fleetwood Mac", title: "Rumours" },
  { artist: "Neil Young", title: "After the Gold Rush" },
  { artist: "Neil Young & Crazy Horse", title: "Rust Never Sleeps" },
  { artist: "Black Sabbath", title: "Paranoid" },
  { artist: "Deep Purple", title: "Machine Head" },
  { artist: "AC/DC", title: "Back in Black" },
  { artist: "The Stooges", title: "Fun House" },
  { artist: "MC5", title: "Kick Out the Jams" },
  { artist: "Can", title: "Tago Mago" },
  { artist: "Can", title: "Ege Bamyasi" },
  { artist: "Neu!", title: "Neu!" },
  { artist: "Faust", title: "Faust IV" },
  { artist: "Bruce Springsteen", title: "Born to Run" },
  { artist: "Bruce Springsteen", title: "Darkness on the Edge of Town" },
  { artist: "Television", title: "Marquee Moon" },
  // Punk / Post-Punk / New Wave
  { artist: "The Clash", title: "London Calling" },
  { artist: "Sex Pistols", title: "Never Mind the Bollocks, Here's the Sex Pistols" },
  { artist: "Ramones", title: "Ramones" },
  { artist: "Joy Division", title: "Unknown Pleasures" },
  { artist: "Joy Division", title: "Closer" },
  { artist: "Talking Heads", title: "Remain in Light" },
  { artist: "Talking Heads", title: "Fear of Music" },
  { artist: "Wire", title: "Pink Flag" },
  { artist: "Siouxsie and the Banshees", title: "Juju" },
  { artist: "Bauhaus", title: "In the Flat Field" },
  { artist: "The Cure", title: "Disintegration" },
  { artist: "The Cure", title: "Pornography" },
  { artist: "The Smiths", title: "The Queen Is Dead" },
  { artist: "The Smiths", title: "Meat Is Murder" },
  { artist: "Echo & the Bunnymen", title: "Ocean Rain" },
  { artist: "Cocteau Twins", title: "Heaven or Las Vegas" },
  { artist: "New Order", title: "Power, Corruption & Lies" },
  // Alternative / Indie / 80s-90s
  { artist: "R.E.M.", title: "Murmur" },
  { artist: "R.E.M.", title: "Automatic for the People" },
  { artist: "Pixies", title: "Doolittle" },
  { artist: "Pixies", title: "Surfer Rosa" },
  { artist: "Sonic Youth", title: "Daydream Nation" },
  { artist: "Dinosaur Jr.", title: "You're Living All Over Me" },
  { artist: "The Replacements", title: "Let It Be" },
  { artist: "Hüsker Dü", title: "Zen Arcade" },
  { artist: "Minutemen", title: "Double Nickels on the Dime" },
  { artist: "My Bloody Valentine", title: "Loveless" },
  { artist: "Slowdive", title: "Souvlaki" },
  { artist: "Ride", title: "Nowhere" },
  { artist: "The Jesus and Mary Chain", title: "Psychocandy" },
  { artist: "Pavement", title: "Slanted and Enchanted" },
  { artist: "Pavement", title: "Crooked Rain, Crooked Rain" },
  { artist: "Guided by Voices", title: "Bee Thousand" },
  { artist: "Built to Spill", title: "Perfect from Now On" },
  { artist: "Fugazi", title: "Repeater" },
  { artist: "PJ Harvey", title: "Rid of Me" },
  { artist: "PJ Harvey", title: "Stories from the City, Stories from the Sea" },
  // Grunge / 90s Rock
  { artist: "Nirvana", title: "Nevermind" },
  { artist: "Nirvana", title: "In Utero" },
  { artist: "Pearl Jam", title: "Ten" },
  { artist: "Soundgarden", title: "Superunknown" },
  { artist: "Alice in Chains", title: "Dirt" },
  { artist: "Smashing Pumpkins", title: "Siamese Dream" },
  { artist: "Smashing Pumpkins", title: "Mellon Collie and the Infinite Sadness" },
  { artist: "Weezer", title: "Weezer (Blue Album)" },
  { artist: "Radiohead", title: "OK Computer" },
  { artist: "Radiohead", title: "The Bends" },
  { artist: "Radiohead", title: "Kid A" },
  { artist: "Radiohead", title: "In Rainbows" },
  { artist: "Jeff Buckley", title: "Grace" },
  { artist: "Neutral Milk Hotel", title: "In the Aeroplane Over the Sea" },
  { artist: "Elliott Smith", title: "Either/Or" },
  { artist: "Modest Mouse", title: "The Lonesome Crowded West" },
  { artist: "The Flaming Lips", title: "The Soft Bulletin" },
  { artist: "Wilco", title: "Yankee Hotel Foxtrot" },
  { artist: "Tool", title: "Lateralus" },
  { artist: "Tool", title: "Ænima" },
  { artist: "Rage Against the Machine", title: "Rage Against the Machine" },
  { artist: "Nine Inch Nails", title: "The Downward Spiral" },
  // 2000s Rock
  { artist: "The Strokes", title: "Is This It" },
  { artist: "Interpol", title: "Turn On the Bright Lights" },
  { artist: "The White Stripes", title: "White Blood Cells" },
  { artist: "The White Stripes", title: "Elephant" },
  { artist: "Arcade Fire", title: "Funeral" },
  { artist: "Arcade Fire", title: "The Suburbs" },
  { artist: "Arctic Monkeys", title: "Whatever People Say I Am, That's What I'm Not" },
  { artist: "Queens of the Stone Age", title: "Songs for the Deaf" },
  { artist: "Muse", title: "Origin of Symmetry" },
  { artist: "Yeah Yeah Yeahs", title: "Fever to Tell" },
  { artist: "LCD Soundsystem", title: "Sound of Silver" },
  { artist: "The National", title: "Boxer" },
  { artist: "The National", title: "High Violet" },
  { artist: "TV on the Radio", title: "Return to Cookie Mountain" },
  { artist: "Deerhunter", title: "Halcyon Digest" },
  { artist: "Animal Collective", title: "Merriweather Post Pavilion" },
  { artist: "Sufjan Stevens", title: "Illinois" },
  { artist: "Sigur Rós", title: "( )" },
  { artist: "Sigur Rós", title: "Ágætis byrjun" },
  { artist: "Godspeed You! Black Emperor", title: "Lift Your Skinny Fists Like Antennas to Heaven" },
  // 2010s-2020s Rock
  { artist: "Tame Impala", title: "Lonerism" },
  { artist: "Tame Impala", title: "Currents" },
  { artist: "King Gizzard & The Lizard Wizard", title: "Nonagon Infinity" },
  { artist: "Fontaines D.C.", title: "Dogrel" },
  { artist: "IDLES", title: "Joy as an Act of Resistance" },
  { artist: "Shame", title: "Songs of Praise" },
  { artist: "black midi", title: "Cavalcade" },
  { artist: "Black Country, New Road", title: "Ants From Up There" },
  { artist: "Dry Cleaning", title: "New Long Leg" },
  { artist: "Parquet Courts", title: "Wide Awake!" },
  { artist: "Car Seat Headrest", title: "Twin Fantasy" },
  { artist: "Courtney Barnett", title: "Sometimes I Sit and Think, and Sometimes I Just Sit" },
  { artist: "St. Vincent", title: "Strange Mercy" },
  { artist: "War on Drugs", title: "Lost in the Dream" },
  { artist: "Turnstile", title: "Glow On" },
  { artist: "Big Thief", title: "Dragon New Warm Mountain I Believe in You" },
  { artist: "Japanese Breakfast", title: "Jubilee" },
  { artist: "Alvvays", title: "Antisocialites" },
  { artist: "King Krule", title: "The OOZ" },
  { artist: "Boris", title: "Flood" },
  { artist: "Thee Oh Sees", title: "Floating Coffin" },
  { artist: "Ty Segall", title: "Manipulator" },
  { artist: "Mac DeMarco", title: "Salad Days" },
  { artist: "Protomartyr", title: "Relatives in Descent" },
  { artist: "Preoccupations", title: "Viet Cong" },
  { artist: "Ought", title: "More than Any Other Day" },
  { artist: "Cloud Nothings", title: "Attack on Memory" },
  { artist: "Dinosaur Jr.", title: "Bug" },
  { artist: "Superchunk", title: "No Pocky for Kitty" },
  { artist: "Yo La Tengo", title: "I Can Hear the Heart Beating as One" },

  // --- Discovered via Last.fm ---
  { artist: "Paramore", title: "RIOT!" },
  { artist: "Red Hot Chili Peppers", title: "Stadium Arcadium" },
  { artist: "Paramore", title: "All We Know Is Falling" },
  { artist: "Staind", title: "14 Shades of Grey" },
  { artist: "Oasis", title: "(What's the Story) Morning Glory?" },
  { artist: "Incubus", title: "Morning View" },
  { artist: "U2", title: "The Joshua Tree" },
  { artist: "Oasis", title: "Heathen Chemistry" },
  { artist: "Cake", title: "Fashion Nugget" },
  { artist: "Hinder", title: "Extreme Behavior" },
  { artist: "Rage Against the Machine", title: "The Battle of Los Angeles" },
  { artist: "The Used", title: "Lies for the Liars" },
  { artist: "Lenny Kravitz", title: "Mama Said" },
  { artist: "The Beatles", title: "The Beatles" },
  { artist: "Daughtry", title: "Daughtry" },
  { artist: "Cake", title: "Comfort Eagle" },
  { artist: "Coldplay", title: "X&Y" },
  { artist: "The Rasmus", title: "Dead Letters" },
  { artist: "AFI", title: "Decemberunderground" },
  { artist: "Linkin Park", title: "Hybrid Theory" },
  { artist: "Bruce Springsteen", title: "The River" },
  { artist: "Placebo", title: "Without You I'm Nothing" },
  { artist: "Midnight Oil", title: "Diesel and Dust" },
  { artist: "Live", title: "Throwing Copper" },
  { artist: "Pitty", title: "Anacrônico" },
  { artist: "The Rolling Stones", title: "Out of Our Heads" },
  { artist: "Franz Ferdinand", title: "Tonight" },
  { artist: "Bon Jovi", title: "Keep The Faith" },
  { artist: "Creed", title: "My Own Prison" },
  { artist: "Andrew W.K.", title: "I Get Wet" },
  { artist: "Dave Matthews Band", title: "Crash" },
  { artist: "The Runaways", title: "The Runaways" },
  { artist: "Simple Plan", title: "Still Not Getting Any..." },
  { artist: "Kings of Leon", title: "Because of the Times" },
  { artist: "WZRD", title: "WZRD" },
  { artist: "Red Hot Chili Peppers", title: "I'm With You" },
  { artist: "The Black Crowes", title: "Shake Your Money Maker" },
  { artist: "The Raconteurs", title: "Broken Boy Soldiers" },
  { artist: "Pearl Jam", title: "Vitalogy" },
  { artist: "AC/DC", title: "Highway to Hell" },
  { artist: "Oasis", title: "Definitely Maybe" },
  { artist: "Incubus", title: "Light Grenades" },
  { artist: "Maroon 5", title: "Songs About Jane" },
  { artist: "Nick Cave & the Bad Seeds", title: "Abattoir Blues / The Lyre of Orpheus" },
  { artist: "U2", title: "How to Dismantle an Atomic Bomb" },
  { artist: "Kid Rock", title: "Rock N Roll Jesus" },
  { artist: "Oasis", title: "Dig Out Your Soul" },
  { artist: "Pearl Jam", title: "Backspacer" },
  { artist: "Pink Floyd", title: "A Momentary Lapse of Reason" },
  { artist: "Los Hermanos", title: "Ventura" },
  { artist: "Santana", title: "Abraxas" },
  { artist: "Creedence Clearwater Revival", title: "Pendulum" },
  { artist: "Paul McCartney", title: "McCartney" },
  { artist: "Dire Straits", title: "Love Over Gold" },
  { artist: "Myslovitz", title: "Happiness Is Easy" },
  { artist: "The Hives", title: "The Black and White Album" },
  { artist: "The Rolling Stones", title: "Between the Buttons" },
  { artist: "Panic! at the Disco", title: "Vices & Virtues" },
  { artist: "Razorlight", title: "Razorlight" },
  { artist: "Daughtry", title: "Leave This Town" },
  { artist: "No Doubt", title: "Return of Saturn" },
  { artist: "The Beatles", title: "Love" },
  { artist: "Chris Cornell", title: "Carry On" },
  { artist: "The Raconteurs", title: "Consolers of the Lonely" },
  { artist: "The Who", title: "It's Hard" },
  { artist: "Legião Urbana", title: "As Quatro Estações" },
  { artist: "3 Doors Down", title: "Time of My Life" },
  { artist: "Cutting Crew", title: "Broadcast" },
  { artist: "The All-American Rejects", title: "The All-American Rejects" },
  { artist: "Nickelback", title: "Here and Now" },
  { artist: "You Me at Six", title: "Hold Me Down" },
  { artist: "Jane's Addiction", title: "Ritual de lo Habitual" },
  { artist: "Alanis Morissette", title: "Under Rug Swept" },
  { artist: "Aerosmith", title: "Big Ones" },
  { artist: "Matchbox Twenty", title: "Mad Season" },
  { artist: "The Velvet Underground", title: "The Velvet Underground & Nico 45th Anniversary" },
  { artist: "Alanis Morissette", title: "Supposed Former Infatuation Junkie" },
  { artist: "Stone Temple Pilots", title: "Core" },
  { artist: "Bloodhound Gang", title: "One Fierce Beer Coaster" },
  { artist: "Meat Loaf", title: "Bat Out of Hell II: Back Into Hell" },
  { artist: "Foo Fighters", title: "Foo Fighters" },
  { artist: "John Mayer", title: "Continuum" },
  { artist: "AC/DC", title: "Black Ice" },
  { artist: "Eric Johnson", title: "Ah Via Musicom" },
  { artist: "The Who", title: "Who Are You" },
  { artist: "Kings of Leon", title: "Aha Shake Heartbreak" },
  { artist: "Alice Cooper", title: "Trash" },
  { artist: "Royal Republic", title: "We Are the Royal" },
  { artist: "Rick Springfield", title: "Working Class Dog" },
  { artist: "U2", title: "Achtung Baby" },
  { artist: "Queen", title: "The Game" },
  { artist: "Black Rebel Motorcycle Club", title: "B.R.M.C." },
  { artist: "The Beatles", title: "Help!" },
  { artist: "Guano Apes", title: "Proud Like a God" },
  { artist: "Matchbox Twenty", title: "Exile On Mainstream" },
  { artist: "Neil Young", title: "Everybody Knows This Is Nowhere" },
  { artist: "Simple Plan", title: "Simple Plan" },
  { artist: "The Beatles", title: "Let It Be" },
  { artist: "Steely Dan", title: "Gaucho" },
  { artist: "Red Hot Chili Peppers", title: "Unlimited Love" },
  { artist: "Tom Petty", title: "Wildflowers" },
  { artist: "Genesis", title: "We Can't Dance" },
  { artist: "Jonas Brothers", title: "Jonas Brothers" },
  { artist: "Coma", title: "Pierwsze wyjście z mroku" },
  { artist: "Hoobastank", title: "The Reason" },
  { artist: "The White Stripes", title: "Icky Thump" },
  { artist: "The Rolling Stones", title: "Beggars Banquet" },
  { artist: "U2", title: "No Line on the Horizon" },
  { artist: "Vertical Horizon", title: "Everything You Want" },
  { artist: "Scorpions", title: "Lovedrive" },
  { artist: "PJ Harvey", title: "Dry" },
  { artist: "Billy Talent", title: "Billy Talent II" },
  { artist: "Skunk Anansie", title: "Stoosh" },
  { artist: "Sum 41", title: "Chuck" },
  { artist: "Butthole Surfers", title: "Independent Worm Saloon" },
  { artist: "Bon Jovi", title: "Bounce" },
  { artist: "Weezer", title: "Weezer (White Album)" },
  { artist: "Anouk", title: "Together Alone" },
  { artist: "Sugar Ray", title: "14:59" },
  { artist: "Emarosa", title: "Emarosa" },
  { artist: "The Rasmus", title: "Black Roses" },
  { artist: "Goo Goo Dolls", title: "Dizzy Up the Girl" },
  { artist: "El Cuarteto De Nos", title: "Bipolar" },
  { artist: "Poets of the Fall", title: "Carnival of Rust" },
  { artist: "Get Scared", title: "Best Kind Of Mess" },
  { artist: "Titãs", title: "A Melhor Banda de Todos os Tempos da Última Semana" },
  { artist: "P!nk", title: "Try This" },
  { artist: "Foo Fighters", title: "One by One" },
  { artist: "Bon Jovi", title: "Cross Road" },
  { artist: "Breaking Benjamin", title: "Phobia" },
  { artist: "The Beatles", title: "1" },
  { artist: "Paul McCartney", title: "Band on the Run" },
  { artist: "Franz Ferdinand", title: "You Could Have It So Much Better" },
  { artist: "Green Day", title: "International Superhits!" },
  { artist: "Oasis", title: "Standing on the Shoulder of Giants" },
  { artist: "Yellowcard", title: "Lights and Sounds" },
  { artist: "Plain White T's", title: "Every Second Counts" },
  { artist: "Guns N' Roses", title: "The Spaghetti Incident?" },
  { artist: "Foo Fighters", title: "Concrete and Gold" },
  { artist: "Stereophonics", title: "You Gotta Go There to Come Back" },
  { artist: "El Cuarteto De Nos", title: "Porfiado" },
  { artist: "Poppy", title: "Flux" },
  { artist: "Queen", title: "Absolute Greatest" },
  { artist: "Papa Roach", title: "The Paramour Sessions" },
  { artist: "Jimmy Eat World", title: "Futures" },
  { artist: "Dave Matthews Band", title: "Busted Stuff" },
  { artist: "Foreigner", title: "4 (Expanded)" },
  { artist: "John Lennon", title: "Walls and Bridges" },
  { artist: "Rita Lee", title: "Fruto Proibido" },
  { artist: "Veruca Salt", title: "Eight Arms to Hold You" },
  { artist: "Fresno", title: "Revanche" },
  { artist: "Fleetwood Mac", title: "Fleetwood Mac" },
  { artist: "The Police", title: "Outlandos D'Amour" },
  { artist: "Soundgarden", title: "Down on the Upside" },
  { artist: "Red", title: "End Of Silence" },
  { artist: "Lostprophets", title: "Start Something" },
  { artist: "David Gilmour", title: "On an Island" },
  { artist: "Carolina Liar", title: "Coming To Terms" },
  { artist: "Lenny Kravitz", title: "It Is Time for a Love Revolution" },
  { artist: "Seether", title: "Finding Beauty in Negative Spaces" },
  { artist: "Coma", title: "Hipertrofia" },
  { artist: "Creedence Clearwater Revival", title: "Bayou Country" },
  { artist: "Nazareth", title: "Hair of the Dog" },
  { artist: "Tally Hall", title: "Good & Evil" },
  { artist: "The Velvet Underground", title: "The Velvet Underground" },
  { artist: "Saliva", title: "Back Into Your System" },
  { artist: "David Cook", title: "David Cook" },
  { artist: "Crazy Town", title: "The Gift of Game" },
  { artist: "Alkaline Trio", title: "Crimson" },
  { artist: "Juli", title: "Es ist Juli" },
  { artist: "Guns N' Roses", title: "G N' R Lies" },
  { artist: "Queen", title: "Jazz" },
  { artist: "Poets of the Fall", title: "Signs of Life" },
  { artist: "Eels", title: "Hombre Lobo" },
  { artist: "Theory of a Deadman", title: "Scars & Souvenirs" },
  { artist: "The Police", title: "Reggatta de Blanc" },
  { artist: "Alter Bridge", title: "Blackbird" },
  { artist: "Geese", title: "3D Country" },
  { artist: "Greta Van Fleet", title: "Anthem of the Peaceful Army" },
  { artist: "Metric", title: "Fantasies" },
  { artist: "Toadies", title: "Rubberneck" },
  { artist: "Oasis", title: "The Masterplan" },
  { artist: "The Stone Roses", title: "Second Coming" },
  { artist: "Bruce Springsteen", title: "Nebraska" },
  { artist: "Wolfmother", title: "Cosmic Egg" },
  { artist: "Rainbow", title: "Ritchie Blackmore's Rainbow" },
  { artist: "Bryan Adams", title: "On a Day Like Today" },
  { artist: "Theory of a Deadman", title: "Savages" },
  { artist: "Stereophonics", title: "Performance and Cocktails" },
  { artist: "Lou Reed", title: "New York" },
  { artist: "T. Rex", title: "Electric Warrior" },
  { artist: "Bryan Adams", title: "So Far So Good" },
  { artist: "Kasabian", title: "Kasabian" },
  { artist: "Pescado Rabioso", title: "Artaud" },
  { artist: "Gary Moore", title: "Wild Frontier" },
  { artist: "Lostprophets", title: "Liberation Transmission" },
  { artist: "Bruce Springsteen", title: "Wrecking Ball" },
  { artist: "Mumford & Sons", title: "Wilder Mind" },
  { artist: "Alabama Shakes", title: "Sound & Color" },
  { artist: "Queen", title: "A Night at the Opera" },
  { artist: "Ben Harper", title: "Diamonds On The Inside" },
  { artist: "AC/DC", title: "Iron Man 2" },
  { artist: "Train", title: "Train" },
  { artist: "The Doors", title: "Morrison Hotel" },
  { artist: "Creedence Clearwater Revival", title: "Willy and the Poor Boys" },
  { artist: "U2", title: "War" },
  { artist: "U2", title: "Pop" },
  { artist: "Journey", title: "Escape" },
  { artist: "Incubus", title: "Monuments And Melodies" },
  { artist: "Lenny Kravitz", title: "Baptism" },
  { artist: "Travis", title: "The Invisible Band" },
  { artist: "Quicksand", title: "Slip" },
  { artist: "Weezer", title: "Weezer (Green Album)" },
  { artist: "Ashlee Simpson", title: "Autobiography" },
  { artist: "Avril Lavigne", title: "The Best Damn Thing" },
  { artist: "Green Day", title: "¡Uno!" },
  { artist: "The Tragically Hip", title: "Fully Completely" },
  { artist: "Aerosmith", title: "Nine Lives" },
  { artist: "Ugly Kid Joe", title: "America's Least Wanted" },
  { artist: "Supertramp", title: "Breakfast in America" },
  { artist: "Hole", title: "Nobody's Daughter" },
  { artist: "Faith No More", title: "Angel Dust" },
  { artist: "Yeah Yeah Yeahs", title: "Show Your Bones" },
  { artist: "Rod Stewart", title: "Every Picture Tells A Story" },
  { artist: "Guano Apes", title: "Don't Give Me Names" },
  { artist: "Queen", title: "The Works" },
  { artist: "Cream", title: "Goodbye" },
  { artist: "Loverboy", title: "Get Lucky" },
  { artist: "Kings of Leon", title: "Walls" },
  { artist: "Audioslave", title: "Revelations" },
  { artist: "David Bowie", title: "Heathen" },
  { artist: "Pat Benatar", title: "Crimes of Passion" },
  { artist: "Shinedown", title: "Amaryllis" },
  { artist: "Beady Eye", title: "Different Gear, Still Speeding" },
  { artist: "Kings of Leon", title: "Come Around Sundown" },
  { artist: "Ted Nugent", title: "Ted Nugent" },
  { artist: "The Police", title: "Synchronicity" },
  { artist: "Switchfoot", title: "Hello Hurricane" },
  { artist: "Foo Fighters", title: "Sonic Highways" },
  { artist: "AC/DC", title: "Let There Be Rock" },
  { artist: "Girlfriends", title: "Girlfriends" },
  { artist: "Bright Eyes", title: "Cassadaga" },
  { artist: "Kult", title: "Tata Kazika" },
  { artist: "Neil Young", title: "Freedom" },
  { artist: "Five for Fighting", title: "America Town" },
  { artist: "Manfred Mann's Earth Band", title: "The Roaring Silence" },
  { artist: "Hey", title: "Miłość! Uwaga! Ratunku! Pomocy!" },
  { artist: "Steelheart", title: "Steelheart" },
  { artist: "Mother Mother", title: "The Sticks" },
  { artist: "Lifehouse", title: "No Name Face" },
];
